### ISSUE TITLE
Why NuGet Gallery not updated to the real 2.0.0 ?

### ISSUE THREAD

**Issue by ArielZhang** [box/box-windows-sdk-v2#100]
Version	Downloads	Last updated
Box Windows SDK V2 2.0.0 (this version)	620	Thursday, January 08 2015

https://www.nuget.org/packages/Box.V2/

**Comment by ArielZhang** [comment]
does anyone can help push the new build to NuGet? our package reference really depends on NuGet...

**Comment by brianytang** [comment]
Apologies for the delay. The nuget package has now been updated.
