### ISSUE TITLE
Box.v2: Support for Box Content Shared Items Content API

### ISSUE THREAD

**Issue by chandan-casahl** [box/box-windows-sdk-v2#102]
Is there anyway we can retrieve Shared Link information using Box.V2 ? I noticed there is content API for Shared Item but it is not handle in Box.v2. (reference : https://box-content.readme.io/#get-a-shared-item)
Is there any plan to enhance Box.v2 to support Shared Item content API ?

**Comment by chandan-casahl** [comment]
Is there anyway we can retrieve Shared Link information using Box.V2 ? I noticed there is content API for Shared Item but it is not handle in Box.v2. (reference : https://box-content.readme.io/#get-a-shared-item)
Is there any plan to enhance Box.v2 to support Shared Item content API ?

**Comment by itrackssoft** [comment]
I am also curious as to any plans for this.

**Comment by coolboy** [comment]
Closing old issues

Feel free to reopen it.
