### ISSUE TITLE
'ModifiedAt' property of the folder is not changed when containing file is renamed

### ISSUE THREAD

**Issue by Rod-Sychev** [box/box-windows-sdk-v2#103]
I expect that folder's ModifiedAt property being updated once the file inside that folder is renamed.

Interestingly enough this also applies to renaming the folder itself and any files.
So if you access your files or folders from the web and rename them Box won't update the ModifiedAt property of those renamed entities and that is rather bizarre to my thinking.
For instance, Dropbox doesn't have this issue.

**Comment by coolboy** [comment]
Hi @Rod-Sychev ,

Are you still having this issue?

Closing old ticket, feel free to reopen it

**Comment by Rod-Sychev** [comment]
Hi @coolboy ,

Since no one has fixed it I don't see how would I not have this issue anymore.

**Comment by mattwiller** [comment]
@Rod-Sychev I just checked and this does not appear to be the case currently.  I ran the following code to rename a file and observed that the `ModifiedAt` timestamp was updated as expected:

```c#
// Get the original timestamp
var file = await client.FilesManager.GetInformationAsync(fileID);
var before = file.ModifiedAt.Value; // gets old value

// Rename the file
var updateRequest = new BoxFileRequest();
updateRequest.Id = fileID;
updateRequest.Name = "New Name.pdf";
await client.FilesManager.UpdateInformationAsync(updateRequest);

// Check if the timestamp was updated
file = await client.FilesManager.GetInformationAsync(fileID);
var after = file.ModifiedAt.Value; // gets current time
```

**Comment by Rod-Sychev** [comment]
@mattwiller It's not file's property that doesn't update but the folder's that contains the file that's being changed.

**Comment by mattwiller** [comment]
@Rod-Sychev Oh, sorry!  I misread the issue — my bad.  The folder's `ModifiedAt` timestamp only refers to the folder object itself, and not all of the items in it.  This field is not expected to update whenever anything inside of the folder changes, since it's just used to track changes to the folder object.

**Comment by Rod-Sychev** [comment]
@mattwiller I respectfully disagree. That falls out of the OS folder change principle. I've implemented integration of Dropbox file service as well and it does change the folder modification time once any file or folder inside is changed. Same applies to Windows folders/files.

The idea being to get all the files and folders that were changed from the last time the client's Box folder was synchronized with whatever the app currently holds so those folders/files could be updated or created.

If there is a better way of doing so please let me know.

**Comment by mattwiller** [comment]
@Rod-Sychev  Ahh, I see what you're trying to do — the [folder API documentation](https://developer.box.com/v2.0/reference/#folder-object) shows that there is a separate timestamp called `ContentModifiedAt` in the .NET SDK that should give you the information that you're looking for (updates on either the folder or any of its contents).  I just ran a quick test and renaming a file in the folder does update the folder's `content_modified_at` field in the API.

**Comment by Rod-Sychev** [comment]
@mattwiller Thanks again for the tip Matt, that should do the trick.
Cheers,
Rod.
