### ISSUE TITLE
Setting description and tags when uploading new file

### ISSUE THREAD

**Issue by netinept** [box/box-windows-sdk-v2#105]
As a continuation on the same theme (but different issue) from Issue #4, the description does not get set when using the example from the readme:

    using (FileStream fs = File.Open(in_filepath + "\\" + in_filename, FileMode.Open, FileAccess.Read))
    {
        BoxFileRequest request = new BoxFileRequest()
        {
            Name = in_filename,
            Parent = new BoxRequestEntity() { Id = boxFolderId },
            Description = @"Sample picture of a flower",
            Tags = new string[2] { "flower", "cloud" }
        };
        
        BoxFile f = await client.FilesManager.UploadAsync(request, fs);
    }

The result is that the file gets uploaded, but the description and tags are blank when viewing it in the Box website.

**Comment by cburnette** [comment]
the REST api does not support setting the description when you upload.  That field is present on the class for parsing response data only.
