### ISSUE TITLE
Implementing Box Developer Edition

### ISSUE THREAD

**Issue by bgoldman** [box/box-windows-sdk-v2#106]
CODE CHANGES

Existing class BoxClient:

1. Create new public static method GetAppAuthConnection: Args for enterpriseId, config (BoxConfig), privateKey, privateKeyPassword. Requests enterprise token using new AuthRepository.AuthenticateAsync method. Instantiates and returns new BoxClient.
2. Create new public static method GetAppUserConnection: Args for userId, config (BoxConfig), privateKey, privateKeyPassword. Requests user token using new AuthRepository.AuthenticateAsync method. Instantiates and returns new BoxClient.

Existing class AuthRepository:

1. Create new public AuthenticateAsync method. Args for entityId, type, private key. Creates a JWT assertion and then uses that assertion to request an auth token. Called by BoxClient.GetAppAuthConnection and BoxClient.GetAppUserConnection.
2. Create new private method ReadPrivateKey: No args. Converts the private key string and returns SigningCredentials instance, decrypting if necessary. Called by AuthenticateAsync.

Existing class BoxUsersManager:

1. Create new public method CreateEnterpriseUserAsync: Args for userRequest (BoxUserRequest), fields (List<string>). Creates a new user.
2. Create new public method CreateAppUser: Same args as CreateEnterpriseUserAsync. Calls CreateEnterpriseUserAsync, setting is_platform_access_only=true.

NOTES

1. Creating an app user will be done by pass-through using BoxUsersManager.CreateEnterpriseUserAsync, without needing to modify this method beyond adding one param. It will authenticate using a BoxClient instance created from GetAppAuthConnection. Since BoxUsersManager.CreateEnterpriseUserAsync doesn’t exist, that will be created as well.

2. Getting an app user will be done using client.UsersManager, without needing to modify any methods. It will authenticate using a BoxClient instance created from GetAppUserConnection.

3. Getting an app user’s info will be done using client.UsersManager, without needing to modify any methods. It will authenticate using a BoxClient instance created from GetAppUserConnection.

4. Editing an app user will be done using client.UsersManager.UpdateUserInformationAsync, without needing to modify this method. It will authenticate using a BoxClient instance created from GetAppUserConnection.

5. Deleting an app user will be done using client.UsersManager.DeleteEnterpriseUserAsync, without needing to modify this method. It will authenticate using a BoxClient instance created from GetAppUserConnection.

**Comment by Rod-Sychev** [comment]
Brandon, 
Is this for creating users on the fly?

**Comment by bgoldman** [comment]
Yes. Box has created new App Auth and App Users functionality, but the SDKs have not been updated yet to support it. I will be implementing this functionality in the .NET and Java SDKs. These are my proposed changes for implementation.

**Comment by brianytang** [comment]
Not sure I agree with the "GetAppAuthConnection" and "GetAppUserConnection" static methods. I know the Java SDK uses an APIConnection object to represent the information that is sent with each request -- but the Windows SDK does not have this concept.

I'm thinking it might be cleaner if we extend off of the existing classes (eg. BoxClient and AuthRepository with something like BoxAppClient and AppAuthRepository respectively). The authentication flow is quite different, and you would need to override the methods that no longer make sense in this context. Off the top of my head, the RefreshAsync should be overriden to throw an expired token exception as the current client logic will attempt to call a refresh whenever an access token is expired.

**Comment by box-platform-demo** [comment]
In terms of refreshing, the way I did it in the ruby SDK is that if I know it's a JWT-based auth token and I get an expired token exception I simply request a new token (either enterprise or user as appropriate).  This way if the client is being used by a long running process, like for listening to the event stream, it can self-refresh even with the new JWT-based auth model.

**Comment by bgoldman** [comment]
@brianytang That was a naming issue that I forgot to update. I intended to call them GetAppAuthClient and GetAppUserClient - would that make more sense? I originally was going to suggest separate classes, but then decided against it, to keep things simpler.

I actually have a potentially better idea. Let me know what you think.

Rather than call BoxClient.GetAppAuthClient and BoxClient.GetAppUserClient, we'd overload the either the BoxConfig constructor or the AuthenticateAsync method to add the extra params. These two options are outlined below, with what you suggested as Option 3 (please let me know if you had intended it to look differently).

Option 1 (leaving BoxConfig alone and passing in the extra args to AuthenticateAsync)

```csharp
var config = new BoxConfig(clientId, clientSecret, redirectUri);
var client = new BoxClient(config);
await client.Auth.AuthenticateAsync(entityId, type, privateKey, privateKeyPassword);
BoxFolder f = await client.FoldersManager.GetItemsAsync("0", 50, 0);
```

Option 2 (passing in the extra args to BoxConfig and leaving AuthenticateAsync alone)

```csharp
var config = new BoxConfig(entityId, type, clientId, clientSecret, privateKey, privateKeyPassword redirectUri);
var client = new BoxClient(config);
await client.Auth.AuthenticateAsync();
BoxFolder f = await client.FoldersManager.GetItemsAsync("0", 50, 0);
```

Option 3 (making a new class for BoxAppClient and leaving BoxConfig and AuthenticateAsync alone)

```csharp
var config = new BoxConfig(clientId, clientSecret, redirectUri);
var client = new BoxAppClient(config, entityId, type, privateKey, privateKeyPassword);
await client.Auth.AuthenticateAsync();
BoxFolder f = await client.FoldersManager.GetItemsAsync("0", 50, 0);
```

In all three cases, there is a new overload for AuthenticateAsync, only differing in the args. Additionally, in all three cases, there is a new overload for RefreshAccessTokenAsync which doesn't need an access token.

I'm happy to do either of these three, just let me know your preference and I'll do it that way.

**Comment by bgoldman** [comment]
@box-platform-demo That sounds perfect, I can refresh for expired auth tokens the same way here as well.

**Comment by bgoldman** [comment]
@brianytang thoughts on this?

**Comment by brianytang** [comment]
I'm still under the impression that you would have to extend off of BoxClient and AuthRepository -- how else would the logic to refresh the JWT token be handled?

**Comment by bgoldman** [comment]
Here's the code so far (incomplete) https://github.com/box/box-windows-sdk-v2/pull/109
