### ISSUE TITLE
Web Links Manager

### ISSUE THREAD

**Issue by bloody-peanuts** [box/box-windows-sdk-v2#108]
Unless I'm mistaken there doesn't seem to be a way to create new web links. Please correct me if this is already in place. Otherwise, I would like to implement a new Manager, BoxWebLinksManager.

Following the docs box has provided it appears this manager would be similar to the files manager. Supported actions include Create, Get, Update, Delete, Share, Copy, Permanent Delete, and Restore.  From the box Documentation:

"Web links are objects that point to URLs. These objects are also known as bookmarks within the Box web application. Web link objects are treated similarly to file objects, so they will also support shared links, copy, permanent delete, and restore with the format /web_links/{WEB_LINK_ID} in place of /files/{FILE_ID}."

 https://box-content.readme.io/reference#web-link-object

**Comment by coolboy** [comment]
Closing old issues

Feel free to reopen it.
