### ISSUE TITLE
Xamarin: Box.V2.JWTAuth

### ISSUE THREAD

**Issue by australsystems** [box/box-windows-sdk-v2#114]
Hi,

Some time ago I added Box.V2 to our Xamarin.Forms project and I had it working, but we couldn't use it because we didn't want to have the user grant the access in a webview before uploading files, so we were checking other options instead of Box, but now you added Box.V2.JWTAuth. Unfortunately I wasn't able to add Box.V2.JWTAuth to our Xamarin.Forms project. It's returning this error after trying to add it from nuget:

Adding Box.V2.JWTAuth...
Attempting to resolve dependency 'BouncyCastle (≥ 1.7.0)'.
Attempting to resolve dependency 'jose-jwt (≥ 1.9.0)'.
Attempting to resolve dependency 'Microsoft.Net.Http (≥ 2.2.29)'.
Attempting to resolve dependency 'Microsoft.Bcl (≥ 1.1.10)'.
Attempting to resolve dependency 'Microsoft.Bcl.Build (≥ 1.0.14)'.
Attempting to resolve dependency 'Newtonsoft.Json (≥ 6.0.8)'.
Adding 'BouncyCastle 1.7.0' to Lennar.
Could not install package 'BouncyCastle 1.7.0'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I believe the problem is in the BouncyCastle, could you change it to use BouncyCastle PCL version or point another way to solve it?

Regards,

**Comment by cburnette** [comment]
The issue is actually with the jose-jwt library (which would fail as well).  Unfortunately, there are no portable compatible libraries that support constructing the JWT assertion with RSA private key.  That’s actually why we created a separate Nuget package for JWT support instead of just adding it to the portable Box.V2 library.

thanks,
Chad

**Comment by australsystems** [comment]
Yes, when I was trying to add I also thought that jose-jwt would fail, but I was able to add it to my Xamarin.Forms project. Maybe another option would be using Xamarin.JOSE.JWT if jose-jwt fails.

In case you can't use these packages to make it compatible with Xamarin, would you say that we can't use this new kind of auth with Xamarin?

**Comment by cburnette** [comment]
Well, one thing to keep in mind is that with this new auth model (JWT), you do not ever want to store the private key in code that you are distributing (like a forms app).  The private key is required to retrieve tokens, and it should always be kept on a secure server that your app is communicating with to retrieve tokens.  That server code can be “normal” .NET (i.e. not portable code) and hence use the Box.V2.JWT package.  This new auth model is very different from the user going through OAuth2 and granting your app access to their Box account.  You are calling into your own box account and you should absolutely keep the credentials (private key, client secret, enterprise ID, etc) on a secure server, not ever in distributed code.

Chad

**Comment by australsystems** [comment]
Thanks, Chad.
