### ISSUE TITLE
How to use with Proxy

### ISSUE THREAD

**Issue by ranjeetkaur** [box/box-windows-sdk-v2#12]
I need to use Proxy for all requests, how can I use SDK with Proxy?

**Comment by iknowcodesoup** [comment]
Also in need of proxy configuration. Currently using a modified handler. Any chance of this feature being implemented?

**Comment by coolboy** [comment]
Hi @iknowcodesoup 

Try use "WebRequest.DefaultWebProxy = new WebProxy("hostname", portnum);"

And you can set any proxy type as long as WebProxy class supports

**Comment by cburnette** [comment]
There is also a way to do it using app.config. Just google it. The sdk uses the standard net.http library.
