### ISSUE TITLE
Get Enterprise Users Method [Enhancement]

### ISSUE THREAD

**Issue by iLovebooks100per** [box/box-windows-sdk-v2#120]
Will the "Get Enterprise Users" method be added to the .NET SDK anytime soon?
https://box-content.readme.io/reference#get-all-users-in-an-enterprise

Also, is there a way to get a list of external users who are collaborators in a folder (or it's subfolders)?

**Comment by cburnette** [comment]
Hey, best way to track this stuff is to create an issue in github. I can add that in the next week or so. 

Chad

**Comment by cburnette** [comment]
sorry didn't realize that this was an issue!

**Comment by cburnette** [comment]
this method is already implemented (upgrade to latest version of Nuget package)
