### ISSUE TITLE
Admin token does not have sufficient scope

### ISSUE THREAD

**Issue by itrackssoft** [box/box-windows-sdk-v2#122]
Hi, trying to run the example given:

```
var adminToken = boxJWT.AdminToken(); //valid for 60 minutes so should be cached and re-used
var adminClient = boxJWT.AdminClient(adminToken);

//for example, get the admin's root folder items
var items = await adminClient.FoldersManager.GetFolderItemsAsync("0", 500);
```

I can retrieve admintoken, but when I attempt the GetFolderItemsAsync call I get this:

> Bearer realm="Service", error="insufficient_scope", error_description="The request requires higher privileges than provided by the access token."

I can use that admintoken to do things like list enterprise users though.
I can also follow the example to create a new app user and list **THAT** user's folders using that user's token.

I'm using a new developer account with no other users, and am syncing my folders to my desktop.
I have enabled all scope options that I can:
![box scope example](https://cloud.githubusercontent.com/assets/8103638/11693477/bbe4a060-9e6a-11e5-94be-23f0e9de9b1e.png)

Even though I'm getting this far, I assume I'm still missing something in my account setup to enable listing of the folders from the admin token?

**Comment by ykapps** [comment]
...I'm also experiencing this same issue. I'm getting the error message you got when the GetFolderItemsAsync("0", 500) method is called.  Did you figure out the cause or fix of this issue? Thanks!

**Comment by hossambarakat** [comment]
Hey @itrackssoft,
have you managed to find solution for this issue?

**Comment by cburnette** [comment]
Actually there was a change made several months ago that the admin account cannot create  folders or files or own any content. This example just needs to be updated to reflect that. Sorry for the confusion.
Chad

**Comment by hossambarakat** [comment]
Thanks @cburnette for the clarification

**Comment by hossambarakat** [comment]
Hey Chard @cburnette.
Does your input means that if my application using App Auth & App User, the content must be below an app user ?

**Comment by cburnette** [comment]
Yes, exactly.  If you have content that you historically would have had the admin account own (like it’s shared across all app users) you should create a dedicated app user for that content.  The app admin account, for security reasons, is no longer allowed to own content.

**Comment by metalphoenix** [comment]
For anyone else following, this is caused by the fact that the app has it's own context in the BoxClient object which you declared and used to create your tokens.

    var adminToken = boxJWT.AdminToken(); //valid for 60 minutes so should be cached and re-used
    var adminClient = boxJWT.AdminClient(adminToken);

Admins and Apps can not only not own content, they can't manipulate content. Users and App Users must be used. It's not currently very clear in the example code, but you must create a "user context"...

    //get a user client
    var userToken = boxJWT.UserToken(appUser.Id); //valid for 60 minutes so should be cached and re-used
    var userClient = boxJWT.UserClient(userToken, appUser.Id);

While it's possible to "switch" that BoxClient context from that of an admin to that of a user, it is also just fine and dandy to have a BoxClient object for each context and use the appropriate object for specific actions. For example, you would use the adminClient for user CRUD while you'd use the userClient for file and folder CRUD.

**Comment by coolboy** [comment]
Closing old issues

Feel free to reopen it.
