### ISSUE TITLE
ASP.net C# RefreshAccessTokenAsync

### ISSUE THREAD

**Issue by robinthomas** [box/box-windows-sdk-v2#124]
Hi!,

I'm new to Box API SDK.

I'm using VS 2015 and .net 4.5.2 with Box.V2 SDK (https://github.com/box/box-windows-sdk-v2)

I'm trying to integrate Box with an ASP.net Web project

I'm following this (https://cloud.app.box.com/s/190xmx0h1pwy4hmp2xeddwwfm57fsg7c) to start the integration 

First I created the Access and Refresh token from https://box-token-generator.herokuapp.com/, and saved the Access and Refresh tokens to database.

then using this code 

var boxConfig = new BoxConfig(sClientID, sClientSecret, uriRedirect);
OAuthSession oAuthSession = new OAuthSession(sAccessToken, sRefreshToken, iExpiresIn, sTokenType);
BoxClient boxClient = new BoxClient(boxConfig, oAuthSession);
boxClient.Auth.SessionAuthenticated += Auth_SessionAuthenticated;
boxClient.Auth.SessionInvalidated += Auth_SessionInvalidated;

var items = await boxClient.FoldersManager.GetFolderItemsAsync("0", 1);

i'm able to connect to Box and list the folders etc.

But after couple of days when i try to use the code it gives me SessionInvalidated error. I know the combination lasts for 60mins and two months.

So i tried this method

var boxConfig = new BoxConfig(sClientID, sClientSecret, uriRedirect);
OAuthSession oAuthSession = new OAuthSession(sAccessToken, sRefreshToken, iExpiresIn, sTokenType);
BoxClient boxClient = new BoxClient(boxConfig, oAuthSession);
boxClient.Auth.SessionAuthenticated += Auth_SessionAuthenticated;
boxClient.Auth.SessionInvalidated += Auth_SessionInvalidated;

try
{
    /// Make a fake call to check whether its working
    await boxClient.FoldersManager.GetFolderItemsAsync("0", 1);
}
catch (Exception ex)
{
    string sError = ex.Message;

```
/// Try to refresh the access token
oAuthSession = await boxClient.Auth.RefreshAccessTokenAsync(oAuthSession.AccessToken);
/// Create the client again
boxClient = new BoxClient(boxConfig, oAuthSession);

await boxClient.FoldersManager.GetFolderItemsAsync("0", 1);
```

}

I'm not able to get the new Refresh/Access tokens once the previous ones has expired, is there a way to do it using sdk, 'cause now again i've to go to https://box-token-generator.herokuapp.com/ to re-create the refresh/access tokens.

**Comment by Rod-Sychev** [comment]
Hello there,

Once you make a call to the API using outdated access token, it's being refreshed behind the scenes.
Basically you need to update your DB access and refresh tokens values upon firing the OnSessionAuthenticated event. 
New values would be in the OAuthSession object.

Good luck,
Rodion.

**Comment by robinthomas** [comment]
Hi, thanks for the reply, but i'm already doing it in here

boxClient.Auth.SessionAuthenticated += Auth_SessionAuthenticated;
in the event method implementation.

and saving the AccessToken and RefreshToken in the database as well.

My question was whether it can be done by a manual call by the SDK and not happen on its own or what is the use of this method RefreshAccessTokenAsync as it sounds to do as it is named.

**Comment by mschroeppel** [comment]
Just to be clear: I need to capture the OnSessionAuthenticated event to get the new access/refresh tokens? This really doesn't seem "managed" to me, because I have to write more code than if there was an obvious method that provided me with the new tokens. Or just provide the new tokens in the existing OAuth object as new properties. 

I've spent I don't know how much time looking at the different / old SDKs where this is a much simpler process.

**Comment by coolboy** [comment]
closing due to last activity is more than 30 days
