### ISSUE TITLE
Access a list of external collaborators

### ISSUE THREAD

**Issue by YakkingYak** [box/box-windows-sdk-v2#126]
We are attempting to control / manage external collaboration to a bunch of sub-folders. Is there a way to get a list of external collaborators? Basically, this list: https://xxxxx.app.box.com/master/unlinked

An option we have, which I am not a fan of, is recursing through each folder and calling
_Client.CollaborationsManager.GetCollaborationAsync()

**Comment by coolboy** [comment]
@YakkingYak 

Currently our API doesn't support that, see https://developer.box.com/reference#get-all-users-in-an-enterprise

Closing old issues

Feel free to reopen it.
