### ISSUE TITLE
Object reference not set to an instance of an object. _auth.Session is null

### ISSUE THREAD

**Issue by ArvindThinkBridge** [box/box-windows-sdk-v2#128]
static void Main(string[] args)
    {
            //Task t = MainGitHubAsync();
            //t.Wait();
           Task t = MainGitHubAsync();
            t.Wait();
    }

    static async Task MainGitHubAsync()
    {
            var config = new BoxConfig(CLIENT_ID, CLIENT_SECRET, new Uri("http://google.com"));
            var client = new BoxClient(config);

            // Get root folder with default properties
            var items =await client.FoldersManager.GetFolderItemsAsync("0", 500);
            
    }

Cause:
box.v2\managers\boxfoldersmanager.cs line 91,  _auth.Session is null.
But could not determine the cause of _auth.Session being null.

**Comment by Rod-Sychev** [comment]
Hi Arvind,

Which authentication method you were thinking to use?
Should it be OAuth2 then you would have to pass the OAuthSession object to the BoxClient constructor as a second parameter.

Hopefully this would give you some leads on the issue.

**Comment by ArvindThinkBridge** [comment]
Hi Rod,
My mistake, I did not pass OAuthSession object. 
I though sdk must have mechanism to provide authenticate, but it's not so.
Thanks.
