### ISSUE TITLE
FileLoadException - System.Net.Http.Primitives

### ISSUE THREAD

**Issue by MonkeySeeMonkeyDo** [box/box-windows-sdk-v2#131]
Hi,
We're using the latest NuGet package (2.6.2). When adding this package in VS2013 for a .NET 4.5 class library project, the project automatically gets a new dependency added to System.Net.Http.Primitives with version 4.2.29.0. If we reuse that library in an exe, it fails with this exception:

System.IO.FileLoadException : Could not load file or assembly 'System.Net.Http.Primitives, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

Although it works to set up an explicit assembly redirection, it is kind of a hassle as its being run from different hosts and environments. Please fix this issue.

Thanks!

**Comment by coolboy** [comment]
@MonkeySeeMonkeyDo 

Are you still seeing this issue?

Please feel free to reopen
