### ISSUE TITLE
GetFolderItemsAsync fails if offset is above 100,000

### ISSUE THREAD

**Issue by saguiitay** [box/box-windows-sdk-v2#132]
I have a folder with more than 100K items.

I use the method GetFolderItemsAsync() to get the items, using limit/offset to do it by getting the items in chunks of 1000 each. Getting the first 100 pages (100K) items works perfectly well. One the 101th request, I get the following error:

```
{
    "type" : "error",
    "status" : 400,
    "code" : "bad_request",
    "context_info" :
    {
        "errors" : [
            {
                "reason" : "invalid_parameter",
                "name" : "offset",
                "message" : "Invalid value '101000'. The offset must not exceed the maximum offset of 100000"
            }
        ]
    },
    "help_url" : "http:\/\/developers.box.com\/docs\/#errors",
    "message" : "Bad Request",
    "request_id" : "2116225221568ed2860ec9b"
}
```

This appears to be a limitation of the API itself, but there's no way around this - I have no way to provide the method any filtering (e.g. get only folders), and I don't seem to have any way to force it to retrieve items 101000 to 101999.

Notice that the request for the 100000 to 100999 items works fine...

**Comment by coolboy** [comment]
hi @saguiitay 

Sorry for the late reply

This is the hard limit on the API instead of the SDK, what's your use case here? Why do you need to loop through more than 100k files? Why they could not be broken down into subfolders?

**Comment by saguiitay** [comment]
I've moved on to a different job, so this is less relevant for me, but for completion sake: the problem is that we have customers with that many files in a single folder. If I remember correctly, those files were generated by some automatic tool, and where accessed directly (and never iterated over), so that didn't pose any issue for them...

**Comment by coolboy** [comment]
Hi @saguiitay 

Congratulation on your new job, since this is the API related issue not SDK

I will close the issue now and fwd it to the related team to think about the limitation on the API

Thank you again for the reply

**Comment by coolboy** [comment]
Leave this comment here if anyone may have similar problem in the future

Use the marker-based end point, which is more performant, and doesn't have this constraint.

https://developer.box.com/v2.0/reference#get-a-folders-items
