### ISSUE TITLE
UsersManager.GetEnterpriseUsersAsync("filter") does not seem to filter

### ISSUE THREAD

**Issue by cori** [box/box-windows-sdk-v2#135]
in my somewhat limited testing of the above-mentioned method, when I supply a filter value the set of users returned from the method are not filtered by the value.

I have 2 Application / Enterprise users as follows:
1. "My Application User"
2. "nobody"

When I execute UsersManager.GetEnterpriseUsersAsync("My Application User") i get back a collection with both users in it. As I understand what I've read about the method it seems like I should only get back the first one.

Unit test also fails this, but based on how it;s constructed I would expect it to.

If this is recognized as a bug I may be able to submit a pull request for a fix.

**Comment by coolboy** [comment]
Hi @cori 

I can confirm filter works, see below for example (5 users in the enterprise, 3 begins with `First`)

![image](https://cloud.githubusercontent.com/assets/404691/26223453/eb7f8cde-3bd2-11e7-950a-24034796bb2e.png)

**Comment by coolboy** [comment]
feel free to reopen it if you could provide us more detail
