### ISSUE TITLE
BoxFile model does not allow for Extension field

### ISSUE THREAD

**Issue by ajweber** [box/box-windows-sdk-v2#136]
I pulled, forked and patched BoxFile.cs to allow for the "extension" field.

Pretty trivial change: added a new constant for the field and added a class Property to capture the json returned from the REST call.  Unit tested to work fine.  (Did not actually update any Test project tests, etc.)

What's the easiest way to supply the edit/patch to the project?

Thanks,
AJ

**Comment by ajweber** [comment]
I updated the BoxFile.cs source and tested it.  It works fine in my testing.  Unfortunately, downloading and getting the project initially setup in my VS2015 updated a lot of the dependencies (which should have absolutely no impact on the actual changes).

I have no good way to selectively pull/checkin the change to one file and there's no reason for me to update the .csproj files, etc.  Any ideas how to submit the changes?

**Comment by coolboy** [comment]
Hi @ajweber 

Sorry for the late reply, a PR is always welcome, here is an exmaple https://github.com/box/box-windows-sdk-v2/pull/300

Ref:
https://developer.box.com/reference#file-object
