### ISSUE TITLE
SHA Param - File Manager

### ISSUE THREAD

**Issue by john-potter** [box/box-windows-sdk-v2#141]
Upload, Upload New Version, etc. does not allow passing in of SHA value. API does.

https://github.com/box/box-windows-sdk-v2/blob/master/Box.V2/Managers/BoxFilesManager.cs

**Comment by john-potter** [comment]
Any word on implementing this? We're hoping to implement it in an upcoming release.

Thanks!

John

**Comment by cburnette** [comment]
Ah, sorry I had to implement a few other things for ‘hot’ issues over the past few weeks.  I can add this in the next few days (I might be able to do it today).  I’ll also try and hook up the pre-flight call though that is a tad bit trickier, but nothing crazy.

Hope things are going well.  Drink some beers for me down there

Chad

**Comment by cburnette** [comment]
Just a quick update.  Almost have this completed. Ran into a few issues with http header types in .net that took a while to figure out.  I think I'll be able to push this by tomorrow afternoon.

**Comment by cburnette** [comment]
Added with 2.10.0
