### ISSUE TITLE
"Preflight Check" - File Manager

### ISSUE THREAD

**Issue by john-potter** [box/box-windows-sdk-v2#142]
Preflight check not exposed via SDK. It is available via API.

https://github.com/box/box-windows-sdk-v2/blob/master/Box.V2/Managers/BoxFilesManager.cs

https://docs.box.com/reference-edit/preflight-check

**Comment by cburnette** [comment]
Hey John, hope you're doing well! I'm actually getting ready to add metadata support to the suk over the next few days so I'll add these two features as well. I think I should have the release out by end of next week. 

Chad

**Comment by erniebahr** [comment]
Hello Chad,

Thanks for the metadata support.  I have been using it and it works great!  Any updates on adding "Preflight Check" support?

**Comment by john-potter** [comment]
Hey Chad. 

Any word on preflight check? We're looking to implement that + SHA checking in an upcoming release.

Thanks!

John

**Comment by cburnette** [comment]
Added with 2.10.0

**Comment by tnlthanzeel** [comment]
why does PreflightCheck throw an error on Donet sdk? its supposed to say if a file could be uploaded or not ryt? i think its a bug
