### ISSUE TITLE
Unable to parse BoxCollection<BoxFile>

### ISSUE THREAD

**Issue by jimmyfakedev** [box/box-windows-sdk-v2#152]
Hi,

I try to throw the BoxConflictException<T> exception when user try to upload an existing file but unfortunatelly, the Exception thrown is a BoxException type.

After debugging the project, I found the error in the BoxResponseExtensions.cs file at line 60:

`BoxConflictError<T> error = converter.Parse<BoxConflictError<T>>(response.ContentString);`

Am I doing something wrong or is it a real bug?

Regards,
Jimmy

**Comment by coolboy** [comment]
hi @jimmyfakedev 

To be clear, you were expecting BoxConflictException for uploading a file with name already exist in that folder.

But the SDK gave you BoxException instead, correct?
