### ISSUE TITLE
How to send Box-Notifications header with the value off in BOX API .Net??

### ISSUE THREAD

**Issue by dkalrasam** [box/box-windows-sdk-v2#153]
Hi,
 
I am making administrative API calls to download the box files, and the user signing in is a co-admin with the correct "Edit settings for your company" permission and I want to suppress email notifications.
 
I am making Box API call (in C#) as mentioned below
 
**BoxSession** boxsession = new **BoxSession**("AccessToken","RefreshToken","ExpiresIn","TokenType")
**BoxConfig**  Config = new **BoxConfig**(ClientId, ClientSecret, RedirectUri) { AcceptEncoding = CompressionType.gzip };
**BoxClient**  Client = new **BoxClient**(Config, boxSession);
 
Stream stream = await Client.FilesManager.DownloadStreamAsync(fileId)
 
Query: how to send Box-Notifications header with above request???
 
Thanks in advance.

**Comment by cburnette** [comment]
fixed with PR #155. Will push Nuget release shortly
