### ISSUE TITLE
Upload fails if filename contains double quotes

### ISSUE THREAD

**Issue by Kyrodan** [box/box-windows-sdk-v2#156]
The following code snippet throws an exception. Filenames with double quotes could be created via the Web UI.

```
   var request = new BoxFileRequest()
   {
      Name = "\"test\"",
      Parent = new BoxRequestEntity { Id = "0" },
   };

   var item = await client.FilesManager.UploadAsync(request, stream);
```

**Comment by iLovebooks100per** [comment]
,A double-quote is an illegal character in NTFS, just like :, \, /, *, ?, <, >, and | .

**Comment by Kyrodan** [comment]
@YakkingYak: Whether it is allowed in NTFS or not is not of interesent, I think.

From Box Developer Documentation (https://docs.box.com/reference#page-file-object):

> Supported Filenames:
Box only supports file names of 255 characters or less. Names that will not be supported are those that contain non-printable ascii, / or \, names with leading or trailing spaces, and the special names “.” and “..”.

Because it is not disallowed, it should work with my above mentioned request.

Remarks: It also works in Box Web UI and the REST call iteself - so it seems a only a problem of the .Net-SDK

**Comment by coolboy** [comment]
@Kyrodan 

This is a corner use case, and I don't see the majority of the customer needs the " in the filename also.

I am closing it now, but would like to learn your use case to see if this worth the time to fix.

**Comment by crazymonk** [comment]
Please re-open this as a bug. Double quotes in filenames are not unusual nor a corner case and it's causing confusion among our users.

Thanks!
-marco
