### ISSUE TITLE
.NET SDK Collaboration Email Notify (bool)

### ISSUE THREAD

**Issue by gmegerian** [box/box-windows-sdk-v2#157]
With the .net SDK - When creating a collaboration please add a boolean field "notify" to be able to disable the email notification...

The following link:
https://docs.box.com/reference#add-a-collaboration - mentions there is a boolean field "notify" for this, but the .NET class BoxCollaborationRequest does not have this field?

**Comment by cburnette** [comment]
This was just added in the latest Nuget release. Just update your reference and you'll see it.

**Comment by gmegerian** [comment]
Chad, I just updated to Box.V2\2.11.0 and I do not see this Notify field. 

This is the BoxCollaborationRequest class I see:
    public class BoxCollaborationRequest : BoxRequestEntity
    {
        public BoxCollaborationRequest();

        [JsonProperty(PropertyName = "accessible_by")]
        public BoxCollaborationUserRequest AccessibleBy { get; set; }
        [JsonProperty(PropertyName = "item")]
        public BoxRequestEntity Item { get; set; }
        [JsonProperty(PropertyName = "role")]
        public string Role { get; set; }
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }
    }

**Comment by cburnette** [comment]
It's a parameter to create collaboration method as it ends up being a query parameter and not part of the body

**Comment by gmegerian** [comment]
Thank you I just found it and its working properly. Thanks!!
