### ISSUE TITLE
Incorrect Space Used return from API GetEnterpriseUsersAsync

### ISSUE THREAD

**Issue by bahushekh** [box/box-windows-sdk-v2#159]
hi 
I am using Administrative Client.UsersManager.GetEnterpriseUsersAsync API call to fetch all enterprise users list.
It is returning All users successfully but space use variable contains incorrect values.
It is showing space used 0 although these users owned files in MBs and GBs. also for some users size displayed is not equals to actual size.

Is it not returning real time data?

**Comment by coolboy** [comment]
@bahushekh 

This more like an API issue instead of SDK problem, are you still facing this issue?

If so, please reopen this issue with screenshot & sample request/response, and I will follow up with our internal team who owns this API
