### ISSUE TITLE
Not getting retry time for 429 errors

### ISSUE THREAD

**Issue by samiringo** [box/box-windows-sdk-v2#166]
We are receiving 429 errors, but the error response does not include any "time-to-retry" property (or "retry-after") as defined here: https://community.box.com/t5/Developer-Forum/Rate-limit-exceeded/td-p/19920

Here is a sample of the error we see: 
Box.V2.Exceptions.BoxException: {"type":"error","status":429,"code":"rate_limit_exceeded","help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"Request rate limit exceeded, please try again later","request_id":"96893023457c59cadcd7c2"}

**Comment by coolboy** [comment]
@samiringo try our new version should fix the problem https://www.nuget.org/packages/Box.V2/2.15.4
