### ISSUE TITLE
Upload from WS much slower than Web

### ISSUE THREAD

**Issue by YakkingYak** [box/box-windows-sdk-v2#199]
Upload using bow-windows-sdk-v2 seems to be extremely slow compared to file dragged and dropped in a browser:

3.5 MB => 25s vs 3s on a browser.
26 MB => 175s vs 14s on a browser.
47 MB => (Timed out after 5 mins) vs ~40s on a browser.

Is this a normal behavior? Can something be done to make it faster?

My code:
C# .net, v4.5.2
Box.V2, v2.10.0

`
int UploadDownloadTimeOut = 600;
...

```
            if (FileId == "")
            {

                boxFile = await _Client.FilesManager.UploadAsync(
                    new BoxFileRequest()
                    {
                        Parent = new BoxRequestEntity() { Id = FolderId },
                        Type = BoxType.file,
                        Name = FileName,
                    }
                    , FileStream
                    , null
                    , TimeSpan.FromSeconds(UploadDownloadTimeOut));
            }
            else
            {
                boxFile = await _Client.FilesManager.UploadNewVersionAsync(FileName, FileId, FileStream, null, null, TimeSpan.FromSeconds(UploadDownloadTimeOut));
            }
```

`

**Comment by aamave** [comment]
@iLovebooks100per where are you trying to upload from (geographically) via the API and webapp? Thanks!

**Comment by iLovebooks100per** [comment]
Hanover, MD, USA.

Content API Access

**Comment by iLovebooks100per** [comment]
Also, the "accelerator" is enabled. And we are uploading many files. So, I am sure the minimum threshold is met.

**Comment by iLovebooks100per** [comment]
Folks, any update on this?

**Comment by iLovebooks100per** [comment]
Update from v2.10.0 to v2.12.1 from nuget. No improve in performance. Performed 5-6 rounds of test. No change in the speed...

3.5 MB => ~25s
26 MB => 171s - 185s
47 MB => Did not attempt

**Comment by iLovebooks100per** [comment]
Same speed with the latest code from GitHub.
3.5 MB => 25s to 30s

**Comment by coolboy** [comment]
Hi @YakkingYak 

I have created a sample app for investigation and could not repo your issue

My result:
30 MB => ~10s on webpp
           => ~10s on my c# demo app

1. Could you provide me a minimal version of your c# code (and also your demo file) which has the slow upload problem?
2. Try to uncheck the Box Accelerator in https://app.box.com/settings/collaboration

Let me know if Box Accelerator setting helps.

Ref:
https://community.box.com/t5/Managing-Your-Content/How-can-I-optimize-my-upload-speeds/ta-p/311

**Comment by coolboy** [comment]
@YakkingYak 

Now we have UploadUsingSessionAsync()

Do you want to try again?

Closing this issue, but feel free to reopen
