### ISSUE TITLE
BoxFilesManager.DownloadStreamAsync Does Not Expose Range Query Param

### ISSUE THREAD

**Issue by brianheinz** [box/box-windows-sdk-v2#211]
There is currently no way to download a byte range of the file using the SDK. The API has a query param for range if you GET a file but it is not exposed via the SDK:

https://docs.box.com/reference#download-a-file

**Comment by coolboy** [comment]
@brianheinz 

We hear you, adding it to our backlog

**Comment by coolboy** [comment]
PR #332
