### ISSUE TITLE
New Project Runtime Error

### ISSUE THREAD

**Issue by bkbroughton68** [box/box-windows-sdk-v2#213]
Hello,

I have created a new WPF project using v4.6.1 of the framework. I have brought in the latest version of the Box SDK via Nuget. The project compiles fine. However, at run time, I receive the following error when I try to upload a file via FileManager.UploadAsync:

"Could not load file or assembly 'Microsoft.Threading.Tasks, Version=1.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."

I have tried several other version of the .NET Framework (4, 4.5, 4.51, etc) but always receive this error.

Any ideas?

Thank you,
Brian

**Comment by iLovebooks100per** [comment]
Are you adding the Box dll to your solution or are you using nuget? The box has dependencies (Microsoft.Net.Http (>= 2.2.20), Newtonsoft.Json (>= 6.0.2), Nito.AsyncEx (>= 2.1.3)). If you use nuget, the decencies will be added to your project automatically.

**Comment by bkbroughton68** [comment]
I'm using Nuget so that the dependencies will be added automatically.

**Comment by maboivin** [comment]
I had the same issue with a project using .NET 4.6. Try adding the Nuget package Microsoft.Bcl.Async and see if it works

**Comment by MajorWalrus** [comment]
I had the same problem in 4.5.1. Installing the Microsoft.Bcl.Async package via Nuget resolved it. Thanks, maboivin, for the suggestion.
