### ISSUE TITLE
Get User's Info

### ISSUE THREAD

**Issue by vishwanthpvr** [box/box-windows-sdk-v2#218]
I dont see any implementation for "Get User's Info" in the current sdk. Am I missing something or is it not implemented yet?

**Comment by john-potter** [comment]
GetCurrentUserInformationAsync or GetUserInformationAsync within UsersManager should give you what you're looking for.

**Comment by coolboy** [comment]
Try GetUserInformationAsync()

**Comment by coolboy** [comment]
@vishwanthpvr ^
