### ISSUE TITLE
Asynchronous Call Does Not Work

### ISSUE THREAD

**Issue by andrzej54** [box/box-windows-sdk-v2#222]
We want to send our files through using APIs of this project. For the test I am checking some APIs, but it seems they do not work. For instance, when I try to find the enterprise users, I never received the message back and my application did not receive the error message as well. My test Enterprise Id is 6152079 and the box application I created is MyFirstTest10. I believe you can find this in your database. Below is the code fragment showing where the process stops:
static async Task MainAsync()
{
var boxConfig = new BoxConfig(clientId, clientSecret, enterpriseId, privateKey, JWTPrivateKeyPassword, JWTPublicKeyId);
var boxJWT = new BoxJWTAuth(boxConfig);
var adminToken = boxJWT.AdminToken(); //valid for 60 minutes so should be cached and re-used
var adminClient = boxJWT.AdminClient(adminToken);
**var users = await adminClient.UsersManager.GetEnterpriseUsersAsync(); //Here the process stops; never finishing its call**
var userRequest = new BoxUserRequest() { Name = "MyFirstTest10", IsPlatformAccessOnly = true };
var appUser = await adminClient.UsersManager.CreateEnterpriseUserAsync(userRequest);
var userToken = boxJWT.UserToken(appUser.Id);
var userClient = boxJWT.UserClient(userToken, appUser.Id);
var userDetails = await userClient.UsersManager.GetCurrentUserInformationAsync();
var items = await adminClient.FoldersManager.GetFolderItemsAsync("0", 500);
items.Entries.ForEach(i =>
{
System.Diagnostics.Debug.WriteLine("\t{0}", i.Name);
});
await adminClient.UsersManager.DeleteEnterpriseUserAsync(appUser.Id, false, true);
}

Also, I attach the complete file that I am testing (you can change the file extention to be .cs because I can not attach the c# file.

Please, let me know what is wrong.

[Default1.aspx.txt](https://github.com/box/box-windows-sdk-v2/files/567324/Default1.aspx.txt)

**Comment by coolboy** [comment]
Hi @andrzej54 ,

1. Why do you need users? From the code you pasted above, looks like you want to create an app user and upload a file into the app user's folder.

You could find an example here -> https://github.com/box/box-windows-sdk-v2/tree/core-sdk/Box.V2.Samples.Core.AppUser.Create

2. I just tested GetEnterpriseUsersAsync(), which is working fine in my example above.

You could test by adding 
**var users = await client.UsersManager.GetEnterpriseUsersAsync();**

below line 33 

https://github.com/box/box-windows-sdk-v2/blob/core-sdk/Box.V2.Samples.Core.AppUser.Create/Program.cs#L33

Let me know if you have any more question

FYI @cburnette

**Comment by andrzej54** [comment]
Hi coolboy,

Thank you for your answer. I created the console project similar to yours, but I am receiving the following error: 
Box.V2.Exceptions.BoxException was caught
  HResult=-2146233088
  Message={"error":"invalid_grant","error_description":"Current date\/time MUST be before the expiration date\/time listed in the 'exp' claim"}
  Source=Box.V2
  StackTrace:
       at Box.V2.Extensions.BoxResponseExtensions.ParseResults[T](IBoxResponse`1 response, IBoxConverter converter)
       at Box.V2.JWTAuth.BoxJWTAuth.JWTAuthPost(String assertion)
       at Box.V2.JWTAuth.BoxJWTAuth.AdminToken()
       at TestBoxDotComConsole.Program.<ExecuteMainAsync>d__0.MoveNext() in c:\Projects\dev.ift.org\TestBoxDotCom\TestBoxDotComConsole\Program.cs:line 47
  InnerException: 
I do not manipulate the dates, so the error is not understandable to me.

I am attaching the file I created for your convenience.

[Program.txt](https://github.com/box/box-windows-sdk-v2/files/573909/Program.txt)

**Comment by coolboy** [comment]
Hi Andrzej54,

Have you updated to our newest version of SDK?

Or you can try my branch https://github.com/box/box-windows-sdk-v2/tree/core-sdk

**Comment by andrzej54** [comment]
Hi Yang,

I developed my version using your Program.cs file. Unfortunately, your Box.V2.Samples.core.AppUser.Create project is .xproj and it is not loaded with the solution in VS2012 that I am using. Could you update this project (and the others as well to the regular .csproj? Or could you give me information how to load this project into solution with VS2012?

Thanks,

Andrew
