### ISSUE TITLE
Could not load file or assembly Microsoft.Threading.Tasks, Version=1.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by vadwella703** [box/box-windows-sdk-v2#225]
I am attempting to recover the Admin Token but I keep getting this error. Can anyone assist in telling me what could be causing it? Below is a copy of my code. By the way, I am not sending in empty strings. I just removed them for this post. Thanks.

    <WebMethod()>
    Public Shared Function GetToken() As String
        Dim client_id As String = ""
        Dim client_secret As String = ""
        Dim privateKey = System.IO.File.ReadAllText("C:\Users\Hugh.Plummer\Desktop\box_private.pem")
        Dim privateKeyPassword = ""
        Dim enterprise_id = ""
        Dim key_id = ""
        Dim boxConfig = New BoxConfig(client_id, client_secret, enterprise_id, privateKey, privateKeyPassword, key_id)
        Dim boxJWT = New BoxJWTAuth(boxConfig)
        Return boxJWT.AdminToken()
    End Function

**Comment by zKarp** [comment]
Installing Microsoft Async solved it for me.

Install-Package Microsoft.Bcl.Async

**Comment by sergiorykov** [comment]
I think it's really simple thing to fix

**Comment by cburnette** [comment]
You need to import the package Microsoft.Bcl.Async

**Comment by sergiorykov** [comment]
I think it should be in package dependencies. Isn't it? 
Please, register it in nuspec-file and issue maintenance release.

**Comment by coolboy** [comment]
@cburnette ^^

**Comment by canbax** [comment]
when I tried to install Microsoft.Bcl.Async it says

Package 'Microsoft.Bcl.Async.1.0.168' already exists in project '...' any ideas ?
