### ISSUE TITLE
Deserialize webhook_event json to object

### ISSUE THREAD

**Issue by HeliosXlr8** [box/box-windows-sdk-v2#259]
When setting up a rest api that is supposed to receive a webhook object, how do you deserialize the json object to a proper C# object using the sdk? The problem is that we don't know which types of json messages/responses correspond to which objects in the sdk. I can't seem to find anywhere which object to use, and I don't want to design my own object to deserialize the json.

EDIT:
Might be good to mention we are looking for how to deserialize a webhook_event or a webhook notification. Not a webhook.

**Comment by cburnette** [comment]
We will be adding built in support for deserializing into existing box objects soon but in the meantime just use the dynamic keyword with the Newtonsoft library that is already in there to deserialize automatically into a map of keys and values. Google for more info on that.
