### ISSUE TITLE
Support multiple BoxMetadataFilterRequests in search

### ISSUE THREAD

**Issue by NeilMeredith** [box/box-windows-sdk-v2#260]
As mentioned in your examples, only one BoxMetadataFilterRequest is currently supported in search.  What is your planned timeline for supporting additional metadata filters?

```
//currently only one BoxMetadataFilterRequest element is supported; in the future multiple will be supported (hence the List)
var results = await client.SearchManager.SearchAsync(mdFilters: new List<BoxMetadataFilterRequest>() { mdFilter });
```

**Comment by coolboy** [comment]
hi @NeilMeredith 

We have updated the method, please find the code here https://github.com/box/box-windows-sdk-v2/blob/master/Box.V2/Managers/BoxSearchManager.cs#L62
