### ISSUE TITLE
The type 'System.Security.Cryptography.HMACSHA1' exists in both '..\BouncyCastle-PCL.1.0.0.6\lib\bouncy_castle_hmac_sha_pcl.dll' and '..\.NETFramework\v4.0\mscorlib.dll'

### ISSUE THREAD

**Issue by chessar** [box/box-windows-sdk-v2#262]
`error CS0433: The type 'System.Security.Cryptography.HMACSHA1' exists in both 'c:\Projects\WindowsFormsApplication1\packages\BouncyCastle-PCL.1.0.0.6\lib\bouncy_castle_hmac_sha_pcl.dll' and 'c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\mscorlib.dll'`

If the use of the code **System.Security.Cryptography** classes, for example:

`System.Security.Cryptography.HMACSHA1 hma
                = new System.Security.Cryptography.HMACSHA1(new byte[] { });`

**Comment by 23W** [comment]
I have the same problem. Is it safe to remove bouncy_castle_hmac_sha_pcl.dll from assembly?

**Comment by coolboy** [comment]
I will take look at it

**Comment by coolboy** [comment]
we are dropping the PCL support now, and should not depends on bouncy_castle_hmac_sha_pcl.dll

https://github.com/box/box-windows-sdk-v2/pull/357

Check out the latest code and let me know if you are still having this problem
