### ISSUE TITLE
The request requires higher privileges than provided by the access token

### ISSUE THREAD

**Issue by VN2606** [box/box-windows-sdk-v2#264]
Hi,
I am trying to to get enterprise users.I am using the following piece of code.

var adminToken = boxJWT.AdminToken(); 
var adminClient = boxJWT.AdminClient(adminToken);

var users=await adminClient.UsersManager.GetEnterpriseUsersAsync();

but when i attempt to make a call to get users i get this

Bearer realm="Service", error="insufficient_scope", error_description="The request requires higher privileges than provided by the access token."

i am making this call with the user account having co-Admin role.

box account settings:
![setting](https://cloud.githubusercontent.com/assets/24496525/21075234/7e6d75b0-bf32-11e6-97ee-7cc82431b46b.png)

Second Scenario:

I Changed the authentication to 3legged OAuth 2.0 Authentication
i used this piece of code to create BoxClient object
var session = new OAuthSession(accessToken, refreshToken, expireTime, tokenType);
BoxClient  client = new BoxClient(boxConfig, session,asUser:"123456");
var items =await client .FoldersManager.GetFolderItemsAsync("0");

In the  case i am making AsUser call to get contents of that user but in this case i am also getting same error "The request requires higher privileges than provided by the access token"

I dont know what i am missing while making Box API call.Please help

**Comment by coolboy** [comment]
Hi @VN2606 

Please reauthorize your app in the enterprise, and below is the link https://developer.box.com/v2.0/docs/configuring-box-platform
4. Grant Access in Enterprise Admin Console

Feel free to reopen the issue if you have more problem
