### ISSUE TITLE
calling AdminToken() generates grant error

### ISSUE THREAD

**Issue by wimdecorte** [box/box-windows-sdk-v2#265]
The simple code as per the sample generates a 'grant error':
(config and session declared earlier in the code)

                config = ConfigureBoxApi();
                session = new BoxJWTAuth(config);
                var adminToken = session.AdminToken();

immediately throws this on calling AdminToken()
{"error":"invalid_grant","error_description":"Current date\/time MUST be before the expiration date\/time listed in the 'exp' claim"}
<img width="879" alt="2016-12-20_10-53-21" src="https://cloud.githubusercontent.com/assets/5022743/21358166/dbf71040-c6a5-11e6-9619-ea04fede0f52.png">

**Comment by SeanLAllen** [comment]
I am experiencing the same issue. Any Updates?

**Comment by coolboy** [comment]
@SeanLAllen yes, this is the root cause

Thanks for posting the link
