### ISSUE TITLE
'System.Net.Http.Primitives, Version=1.5.0.0

### ISSUE THREAD

**Issue by jffcovey** [box/box-windows-sdk-v2#273]
Getting the following stack trace when I try to do an async call over http like  await BoxClient.SearchManager.SearchAsync("query")

Could not load file or assembly 'System.Net.Http.Primitives, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

-Async calls in my mvc webapp like this seem to work without issue, but when I install Box API into a console app I get these errors.

-using VS2015 and .NET 4.6.1

packages config:

```
<packages>
  <package id="BAT" version="2.0.9" targetFramework="net461" />
  <package id="BouncyCastle-PCL" version="1.0.0.6" targetFramework="net461" />
  <package id="Box.V2" version="2.13.0" targetFramework="net461" />
  <package id="EntityFramework" version="6.1.3" targetFramework="net461" />
  <package id="log4net" version="2.0.3" targetFramework="net461" />
  <package id="Microsoft.Bcl" version="1.1.10" targetFramework="net461" />
  <package id="Microsoft.Bcl.Build" version="1.0.14" targetFramework="net461" />
  <package id="Microsoft.Net.Http" version="2.2.29" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="6.0.2" targetFramework="net461" />
  <package id="Nito.AsyncEx" version="2.1.3" targetFramework="net461" />
  <package id="NLog" version="3.1.0.0" targetFramework="net461" />
  <package id="NLog.Config" version="3.1.0.0" targetFramework="net461" />
  <package id="NLog.Schema" version="3.1.0.0" targetFramework="net461" />
  <package id="RASD.Audit.EntityFramework" version="1.0.12" targetFramework="net461" />
  <package id="SlowCheetah" version="2.5.15" targetFramework="net461" />
</packages>

```

also added bindingredirect in app.config.

```
 <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.29.0" newVersion="4.2.29.0" />
      </dependentAssembly>
    </assemblyBinding>
```

**Comment by cburnette** [comment]
Install Microsoft.Bcl.Async

**Comment by jffcovey** [comment]
That package was already in the solution but wasn't being referenced in the packages.config.  Adding it didn't fix the issue.

**Comment by EliseoGaston** [comment]
Do we have a solution for this? i'm having the same problem with VS2015 and framework project .NET 4.6.2

**Comment by hadkins0617** [comment]
I'm running into the same issue. Was anybody able to resolve this issue?

**Comment by cburnette** [comment]
I just created a new console application in VS2015 using .NET 4.6.1 and I added the Nuget packages Box.V2 and Box.V2.JWTAuth and without doing anything further I was able to successfully connect and make api calls to Box.  When I look at the the packages.config file that was created by VS2015 I see the following:

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="BouncyCastle" version="1.8.1" targetFramework="net461" />
  <package id="BouncyCastle-PCL" version="1.0.0.6" targetFramework="net461" />
  <package id="Box.V2" version="2.15.6" targetFramework="net461" />
  <package id="Box.V2.JWTAuth" version="1.3.3" targetFramework="net461" />
  <package id="Microsoft.Bcl" version="1.1.10" targetFramework="net461" />
  <package id="Microsoft.Bcl.Async" version="1.0.168" targetFramework="net461" />
  <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="net461" />
  <package id="Microsoft.Net.Http" version="2.2.29" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="10.0.2" targetFramework="net461" />
  <package id="Nito.AsyncEx" version="2.1.3" targetFramework="net461" />
  <package id="System.IdentityModel.Tokens.Jwt" version="4.0.2.206221351" targetFramework="net461" />
</packages>
```

So it appears that VS is now correctly pulling in the various required Nuget packages.  Can you try creating a clean console app and just pull in the two Box Nuget packages and verify that VS2015 adds references to the other required dependencies?

**Comment by coolboy** [comment]
Just updated to net 461, let me know if this doesn't fix your problem

https://github.com/box/box-windows-sdk-v2/pull/357
