### ISSUE TITLE
Group invitibility_level of the new group & member_viewability_level of the new group missing 

### ISSUE THREAD

**Issue by kendomen** [box/box-windows-sdk-v2#274]
The api method available in box-java-sdk:

BoxGroup.Info boxGroupInfo = BoxGroup.createGroup(api, groupName, null, null, null, "admins_only", "admins_and_members");
            
is missing in the .NET box sdk.
Is there a way to add the invitibility_level & member_viewability_level to new group?

**Comment by coolboy** [comment]
Hi @kendomen fixed it in #277

**Comment by kendomen** [comment]
@coolboy thanks so much!
