### ISSUE TITLE
Missing dependencies in nuget package

### ISSUE THREAD

**Issue by prakashguru** [box/box-windows-sdk-v2#275]
Do I have to manually add "Microsoft.Bcl.Async" package to my .net 4.5 WPF application project? It is failing with "Could not load file or assembly 'Microsoft.Threading.Tasks, Version=1.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."

**Comment by coolboy** [comment]
Hi @prakashguru 

I don't think so, if you check our CI -> https://ci.appveyor.com/project/coolboy/box-windows-sdk-v2/branch/master, the build is passing.

Have you tried 'nuget.exe restore Box.V2.sln' before building?
