### ISSUE TITLE
RefreshAccessTokenAsync Stuck

### ISSUE THREAD

**Issue by paapfly** [box/box-windows-sdk-v2#278]
I changed my app to use Standard Authentication (3-legged OAuth2.0), and changed my code to do the easy code:
 
var config = new BoxConfig(CLIENT_ID, CLIENT_SECRET, new Uri("https://boxsdk"));
                var session = new OAuthSession(ACCESSTOKEN, REFRESHTOKEN, 3600, "bearer");
                var client = new BoxClient(config, session);
 
                //with the accesstoken and refreshtoken we are capable of ask for another token.
                await client.Auth.RefreshAccessTokenAsync(client.Auth.Session.AccessToken);

I can't come back from RefreshAccessTokenAsync, it seems my problem is related with any method async, they get stuck
 
I do not receive any error or exception, because it never comes back from the async method

**Comment by coolboy** [comment]
Hi @paapfly 

I just tried it on my side, everything is working fine for me.
Do you have a more detail repro step?

![2017-01-27_17-32-32](https://cloud.githubusercontent.com/assets/404691/22393128/c4ac08ee-e4b6-11e6-9d50-85c5790d047a.png)
