### ISSUE TITLE
Getting Shared Link Items in .NET

### ISSUE THREAD

**Issue by kendomen** [box/box-windows-sdk-v2#279]
There's a method implemented in box-java-sdk which doesn't seem to be implemented in .NET sdk.

       // Public link:  https://hpdnyc.app.box.com/s/zjq4iwixgn44gvqt43ou4jmiqfehemkc
        BoxItem.Info boxItem = BoxFolder.getSharedItem(api, "https://hpdnyc.app.box.com/s/zjq4iwixgn44gvqt43ou4jmiqfehemkc");
        BoxFolder publicFolder = (BoxFolder)boxItem.getResource();
        Iterable<com.box.sdk.BoxItem.Info> items = publicFolder.getChildren();

        for (BoxItem.Info item : items) {
            System.out.println("\t" + item.getName());
        }

When I try the same thing in .NET, I can get the folder ID but the items are null.

            
            Task<BoxItem> task = adminClient.SharedItemsManager.SharedItemsAsync("https://hpdnyc.app.box.com/s/zjq4iwixgn44gvqt43ou4jmiqfehemkc");
            task.Wait(-1);

            BoxFolder sharedFolder = (BoxFolder)task.Result;
            Console.WriteLine("Id: " + sharedFolder.Id);
            BoxCollection<BoxItem> items = sharedFolder.ItemCollection;
            Console.WriteLine("Items: " + items);

**Comment by coolboy** [comment]
Hi @kendomen 

I will look at it

**Comment by coolboy** [comment]
Hi @kendomen ,

I tested both your link and my own shared link, and I could confirm that Box API doesn't return items in the response, causing the items are missing in C# SDK response.

What's your setup for your Java SDK? Could you confirm that It will return a list of subitems to you?

Response from Box API:
`{
  "type": "folder",
  "id": "15069319032",
  "sequence_id": "1",
  "etag": "1",
  "name": "OpenData",
  "created_at": "2016-12-23T07:31:17-08:00",
  "modified_at": "2017-02-03T05:18:00-08:00",
  "description": "",
  "size": 15200355,
  "path_collection": {
    "total_count": 0,
    "entries": []
  },
  "created_by": {
    "type": "user",
    "id": "252078881",
    "name": "DocStore",
    "login": "docstore@hpd.nyc.gov"
  },
  "modified_by": {
    "type": "user",
    "id": "284134734",
    "name": "DocStoreUser1",
    "login": "AppUser_167905_qctijE9beK@boxdevedition.com"
  },
  "trashed_at": null,
  "purged_at": null,
  "content_created_at": "2016-12-23T07:31:17-08:00",
  "content_modified_at": "2017-02-03T05:18:00-08:00",
  "owned_by": {
    "type": "user",
    "id": "252078881",
    "name": "DocStore",
    "login": "docstore@hpd.nyc.gov"
  },
  "shared_link": {
    "url": "https://hpdnyc.box.com/s/zjq4iwixgn44gvqt43ou4jmiqfehemkc",
    "download_url": null,
    "vanity_url": null,
    "effective_access": "open",
    "is_password_enabled": false,
    "unshared_at": null,
    "download_count": 0,
    "preview_count": 0,
    "access": "open",
    "permissions": {
      "can_download": true,
      "can_preview": true
    }
  },
  "folder_upload_email": null,
  "parent": null,
  "item_status": "active"
}`

**Comment by kendomen** [comment]
I'm just using the box-java-sdk for my setup.  I have confirmed you can get subitems as well.

` BoxItem.Info boxItem = BoxFolder.getSharedItem(api, "https://nikedev.box.com/s/ddxxcbiajfs7y2c75ld952kkfwkq6ec3");
        BoxFolder publicFolder = (BoxFolder)boxItem.getResource();
        Iterable<com.box.sdk.BoxItem.Info> items = publicFolder.getChildren();
        for (BoxItem.Info item : items) {
            System.out.println("\t" + item.getName());

            if (item instanceof BoxFolder.Info) {
                BoxFolder subFolder = (BoxFolder)item.getResource();
                Iterable<BoxItem.Info> subItems = subFolder.getChildren();
                for (BoxItem.Info subItem : subItems) {
                    System.out.println("\t\t" + subItem.getName());
                }
            }
        }
`

**Comment by coolboy** [comment]
Hi @kendomen ,

We tested your code in java, and found out that our java SDK will call /folders/ endpoint implicitly to get all the subitems for that folder.
`    Iterable<com.box.sdk.BoxItem.Info> items = publicFolder.getChildren();

    for (BoxItem.Info item : items) {
        System.out.println("\t" + item.getName());
    }`

But in C# SDK, you have to call GetFolderItemsAsync() explicitly by using the folderId from SharedItemsAsync() to get all subitems
