### ISSUE TITLE
Refresh Token fails - BoxSessionInvalidatedException

### ISSUE THREAD

**Issue by jasonkimchi** [box/box-windows-sdk-v2#280]
API Key = 46sbsz762orr3hop3zqpsczlc440iskn

string refreshToken = "XXXXXXXXXXXXXXXXXXXX";
        string accessToken = "XXXXXXXXXXXXXXXXXXXX";
        public BoxClient CreateClientByToken()
        {
            BoxClient client;
            //var privateKey = File.ReadAllText("private_key.pem");
            //var boxConfig = new BoxConfig(Configurations.BoxClientId, Configurations.BoxClientSecret, Configurations.BoxEnterpriseId, privateKey, Configurations.BoxPrivateKeyPassword, Configurations.BoxPublicKeyId);
            //var boxJWT = new BoxJWTAuth(boxConfig);
            //var adminToken = boxJWT.AdminToken();
            //client = boxJWT.AdminClient(adminToken);
            var auth = new OAuthSession(accessToken, refreshToken, 3600, "bearer");
            var config = new BoxConfig(Configurations.BoxClientId, Configurations.BoxClientSecret, new Uri(Configurations.BoxRedirectUri));
            client = new BoxClient(config, auth);
            return client;
        }      

All calls succeed for the duration of the initial access token, but first refresh always fails with below exception:

'Box.V2.Exceptions.BoxSessionInvalidatedException' was thrown.

Exception.message to be added shortly

Initial access and refresh tokes are being generated by stepping through the OAuth flow manually outside of the application and fed in hard-coded as listed above.

Tokens generated with this method have been proven to refresh correctly in Postman.

**Comment by coolboy** [comment]
Hi @jasonkimchi 

I tested and it's working fine for me, please find my sample code below
![image](https://cloud.githubusercontent.com/assets/404691/22845886/a31d8f98-ef99-11e6-8629-a17ad65e2e4a.png)

**Comment by johnmay1** [comment]
Hi @coolboy,

Yes, it worked until the access token is valid. It will get the new access token from supplied refresh token and that refresh token is valid for one time use. So now once the newly received access token  is expired we can't get new access token as supplied refresh token is valid for onetime use only. 

My understanding is that Box.Net SDK handle such situation. So whenever we request for new access token using existing refresh token it will also store new refresh token internally. Which will be then use in future to get new access token and will continue updating stored refresh token with newly refresh token to be use in future.

Correct me if i am wrong.
