### ISSUE TITLE
Box Java SDK - EventLog.java Line 38 failing

### ISSUE THREAD

**Issue by mylimaye** [box/box-windows-sdk-v2#281]
While using the Java SDK for Box, I used the EventLog.getEnterpriseEvents() interface. It failed later while instantiating EventLog.

        this.nextStreamPosition = json.get("next_stream_position").asString();

On debugging the problem, it turned out that, json.get("next_stream_position") returns JsonNumber, so calling asString() results into UnsupportedOperationException().

Also, I noticed that - the SDK doesn't provide any API to get the User Events, so some interface like EventLog.getEnterpriseEvents() would be useful.

**Comment by coolboy** [comment]
Hi @mylimaye 

Please file an issue to our Java SDK -> https://github.com/box/box-java-sdk

Here is for .Net
