### ISSUE TITLE
Authentication problems / is the SDK invalidating my saved access and refresh tokens?

### ISSUE THREAD

**Issue by horacioj** [box/box-windows-sdk-v2#31]
Hi,

I think I'm doing the authentication workflow in the right way, but too ofter I get 'refresh token has expired'. It is supposed to last for two months, so it can't be that, because the problem happens within the same day (within hours).

This is what I do: The first time (just once), I get my first access and refresh tokens pair. This is working fine.

Then, in the following hours (and luckily days and so on) I get (and save) new access and refresh tokens doing this:

``` cs
var config = new BoxConfig(_settings.ClientId, _settings.ClientSecret, new Uri(RedirectUrl));
var sessionInfo = new OAuthSession(_settings.AccessToken, _settings.RefreshToken,
                                                       AccessTokenExpiresSeconds, "bearer");
_client = new BoxClient(config, sessionInfo);

var newSessionInfo = await client.Auth.RefreshAccessTokenAsync(client.Auth.Session.AccessToken);
// and I update _settings.AccessToken and _settings.RefreshToken 
// with the values found in newSessionInfo 
```

Why then, I'm getting the 'refresh token has expired'?
Digging into the SDK code, I see this in \Box.V2\Managers\BoxResourceManager.cs:

``` cs
            switch (response.Status)
            {
                // Refresh the access token if the status is "Unauthorized" (HTTP Status Code 401: Unauthorized)
                // This will only be attempted once as refresh tokens are single use
                case ResponseStatus.Unauthorized:
                    response = await RetryExpiredTokenRequest<T>(request).ConfigureAwait(false);
                    break;

...
...
...
        protected async Task<IBoxResponse<T>> RetryExpiredTokenRequest<T>(IBoxRequest request)
            where T : class
        {
            OAuthSession newSession = await _auth.RefreshAccessTokenAsync(request.Authorization).ConfigureAwait(false);
            AddAuthorization(request, newSession.AccessToken);
            return await _service.ToResponseAsync<T>(request).ConfigureAwait(false);
        }

```

Therefore, could it be, you are refreshing the access and refresh tokens when you identify an expired access token?
If so, you are getting a new  access and refresh tokens pair, but I never see nor get them; and my saved tokens are now invalid.
Am I right? If so, how to workaround this?
If I'm not right, why do you think I'm losing the authentication?

Thanks,
Horacio.-

**Comment by ptallett** [comment]
This really sucks. I think you should remove the boast on your homepage that "Box is the best files API".

Cheers,
Paul

**Comment by ptallett** [comment]
This really sucks. I think you should remove the boast on your homepage that "Box is the best files API".

A simple callback when the token is refreshed would solve this.

Cheers,
Paul

**Comment by ptallett** [comment]
Looks like this has been fixed:

      client = new BoxClient(config);
      client.Auth.SessionAuthenticated += Auth_SessionAuthenticated;
      session = await client.Auth.AuthenticateAsync(token);
...
       private async void Auth_SessionAuthenticated(object sender, SessionAuthenticatedEventArgs e)
        {
            // The SDK may refresh the tokens, so we have to save after every authentication https://github.com/box/box-windows-sdk-v2/issues/31
            await dispatcher.RunAsync(CoreDispatcherPriority.Normal, async () =>
            {
                AuthRepository repo = (AuthRepository)sender;
                SaveTokens(repo.Session.AccessToken, repo.Session.RefreshToken);
            });
        }

Cheers,
Paul
