### ISSUE TITLE
BoxJWTAuth constructor can give rise to System.NullReferenceException

### ISSUE THREAD

**Issue by Dave-Lowndes** [box/box-windows-sdk-v2#311]
Debugging into the constructor code, the following:

`            AsymmetricCipherKeyPair key;
            using (var reader = new StringReader(this.boxConfig.JWTPrivateKey))
            {
                key = (AsymmetricCipherKeyPair)new PemReader(reader, pwf).ReadObject();
            }
`

results in key being null, so that the next line of code:

`            var rsa = DotNetUtilities.ToRSA((RsaPrivateCrtKeyParameters)key.Private);
`

throws a NullReferenceException.

I'm presuming the information I've been given that populates JWTPrivateKey may be wrong, but fundamentally it seems amiss that the constructor doesn't handle the key variable being null and throwing a more specific exception that could explain the issue precisely.

Any thoughts?

**Comment by coolboy** [comment]
Hi @Dave-Lowndes ,

Thanks for the issue, will take look at it
