### ISSUE TITLE
Allow creating a JWT UserClient with a previously acquired JWT user token

### ISSUE THREAD

**Issue by brunzefb** [box/box-windows-sdk-v2#320]
Our team is creating one central web service that acts as an authentication broker -- that web service app has the full JWTAuth credentials required to obtain a token for a specific user. The web service exposes an API that apps can log into and which allows retrieval of box JWT auth user tokens for specific users. These JWT tokens are time-limited, and that's a good thing. We have other applications that need to do uploads/downloads listing of files/folders on behalf of users. Those apps make calls to the authentication broker, which hands them a fresh JWT token - these are using the full JWT functionality (with PEM certificate etc.) to get a user token. Using ONLY that JWT user token (and no other credentials), we have to create an instance of a BoxClient. That is done by first creating a instance of the BoxJWTAuth class. Now the constructor for that class takes all the credentials, and requires them to be valid, specifically the privateKey and JWTPrivateKey password. If those two are null, empty or invalid, you get a nasty exception. But we need an instance of the BoxJWTAuth class without providing any valid credentials. The code to get a UserClient (once you have a valid token) looks something like this then:

var boxConfig = new BoxConfig("", "", "", "", "", ""); // no passwords
var boxJwt = new BoxJWTAuth(boxConfig); // code blows up here - so changes to constructor needed
const string userToken = "TOKEN"; // we have a valid JWT token from our web service
UserClient = boxJwt.UserClient(userToken, null); // and use it to get a valid UserClient.

Having the credentials in one central place, and only retrieving a token when needed makes for much better security.

Submitted PR

**Comment by coolboy** [comment]
Hi @brunzefb 

I understand your use case now

You just want to use the userToken (from server) to create an UserClient on the client side w/o all the private key stuff which should only exist on the server side.

Please correct me if I am wrong

I think this is really a must have and let me think about what should be the right way of handing this, since I don't like the way of `var boxConfig = new BoxConfig("", "", "", "", "", ""); // no passwords`

**Comment by brunzefb** [comment]
That's exactly it, you do understand my use case now.

I agree that the implementation is conceptually not elegant - Ideally I would like to see the ability to create a UserClient with a valid JWT Token. ie. var userClient = new UserClient(boxConfig, jwtToken, goodUntil);  where goodUntil is a DataTime that says how long the token can be used for.

Best,

F.

**Comment by coolboy** [comment]
I agree with you, but I believe goodUntil will be in the token, not as an extra param
