### ISSUE TITLE
HttpRequestHandler runs out of memory on long running jobs

### ISSUE THREAD

**Issue by kendomen** [box/box-windows-sdk-v2#324]
I have a job that calls 
`adminClient.EventsManager.EnterpriseEventsAsync(MAX_ROWS, streamPosition, null, null, null);`
to load SQL DataWarehouse with box events.

When this method is called a lot, it runs out of memory.  The number of class LimitMemoryStream keeps growing.

The culprit seems to lie in HttpRequestHandler.ExecuteAsync(IBoxRequest request)
and there's a call
`boxResponse.ContentString = await response.Content.ReadAsStringAsync().ConfigureAwait(false);`

I'm wondering if there's a way to keep the memory from growing.

**Comment by coolboy** [comment]
which version of our are you using?
From the latest source code or nuget?

**Comment by kendomen** [comment]
I'm using https://github.com/box/box-windows-sdk-v2/commit/32d39dcb958d023958e9dc8bf4dc040e7a976305 from the #301 fix

**Comment by kendomen** [comment]
I'm testing right now but it seems like making HttpClient a singleton in HttpRequestHandler seems to protect against memory leaks.

**Comment by coolboy** [comment]
Hi @kendomen 

Thanks for the comment, we already aware of this issue, and here is the commit
https://github.com/box/box-windows-sdk-v2/pull/309

We are testing it right now, so it's not ready for production use

**Comment by kendomen** [comment]
Thanks!  I'll pull the latest and test it here as well.

**Comment by coolboy** [comment]
sure, let's know your result

**Comment by kendomen** [comment]
So my results still throws a StackOverflow on line 73 in HttpRequestHandler.cs after thousands of calls are made to EventsManager.EnterpriseEventsAsync(MAX_ROWS, streamPosition, null, null, null);

var response = await client.SendAsync(httpRequest, completionOption).ConfigureAwait(false);

**Comment by coolboy** [comment]
Hi @kendomen ,

So this StackOverflow problem only happens in my reuse HttpClient fix? or also in your reuse HttpClient fix?

Is the situation better after my fix? like from hundreds to thousands.

Will this also happen for UserEventsAsync as well?

**Comment by kendomen** [comment]
I got it from your fix.  I'm pretty sure it'll happen to my fix too.  
The situation got much better in terms of memory growth but it happens after thousands of calls.  Let me try with UserEventsAsync

**Comment by kendomen** [comment]
Is it possible that I get the stackoverflow because I'm calling Wait() on EventsManager.EnterpriseEventsAysnc()?

**Comment by coolboy** [comment]
Hi @kendomen 

I think there are two issues here
1. We should reuse the HttpClient.
2. HttpRequest & HttpResponse should dispose right after the completion of the call.

Now we have 1. which makes the problem better.

And for 2. I have a sample change here -> https://github.com/box/box-windows-sdk-v2/commit/a6f62319e704567835540ccf19f8432a7641c601#diff-11383506999ac25830734e9a4a378c39

I reverted it later since there are some problems, but would like if you could try 2. and let me know if this fix your problem.

**Comment by kendomen** [comment]
So I'll try this build:  https://github.com/box/box-windows-sdk-v2/tree/a6f62319e704567835540ccf19f8432a7641c601 and see if it works?

**Comment by coolboy** [comment]
Yes, and this build has some problem, not ready for prod use cases, but should enough for your test cases for EnterpriseEventsAsync()

**Comment by kendomen** [comment]
So this build seems to work and run all the way through with calling EnterpriseEventsAsync.  I'm beginning to think that the issue has to do with my code calling async EnterpriseEventsAsync - I was calling Wait() on it and after awhile, it threw a StackOverflowException().  Even though the code completed, memory grew considerably so I'll keep an eye on it.  Thanks for your help @coolboy!

**Comment by coolboy** [comment]
Hi @kendomen 
So does the dispose of HttpRequest & HttpResponse resolve your problem or not?
Or it's the same like last time.
