### ISSUE TITLE
TypeLoadException: Could not load type 'System.IdentityModel.Tokens.JwtPayload' from assembly 'System.IdentityModel.Tokens.Jwt

### ISSUE THREAD

**Issue by kylefernandadams** [box/box-windows-sdk-v2#328]
JWT authentication is failing with a type load exception. 
```
System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at BoxJwtConsoleSample.Program.Main(String[] args) in C:\Users\kadams\documents\visual studio 2017\Projects\BoxJwtExample\BoxJwtConsoleSample\Program.cs:line 19

Inner Exception 1:
TypeLoadException: Could not load type 'System.IdentityModel.Tokens.JwtPayload' from assembly 'System.IdentityModel.Tokens.Jwt, Version=5.1.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```

When setting a break point, I'm finding the that the UNIX_EPOCH time is set to 1/1/1970 12:00:00 AM, so I'm not sure that is an issue or not:
```
-		boxJWT	{Box.V2.JWTAuth.BoxJWTAuth}	Box.V2.JWTAuth.BoxJWTAuth
-		Static members		
-		Non-Public members		
		AUTH_URL	"https://api.box.com/oauth2/token"	string
		ENTERPRISE_SUB_TYPE	"enterprise"	string
		TOKEN_TYPE	"bearer"	string
		USER_SUB_TYPE	"user"	string
-		Non-Public members		
+		UNIX_EPOCH	{1/1/1970 12:00:00 AM}	System.DateTime
+		boxConfig	{Box.V2.Config.BoxConfig}	Box.V2.Config.IBoxConfig {Box.V2.Config.BoxConfig}
+		credentials	{System.IdentityModel.Tokens.SigningCredentials}	System.IdentityModel.Tokens.SigningCredentials

```

Lastly, here's a gist with my simple example:
https://gist.github.com/kylefernandadams/734828a968f9714cf74f02c6a70cee18

**Comment by coolboy** [comment]
Hi @kylefernandadams ,

What's the OS version and VS version you were using?
Are you using our source of the nuget package?

I could not repo your issue on my test machine, but while researching online below are some related links:

https://github.com/IdentityServer/IdentityServer3/issues/3017
https://github.com/Microsoft/PowerBI-CSharp/issues/38

Seems that downgrade to JWT 4.0 will fix the problem.

**Comment by STIHLFredGuanzon** [comment]
> Seems that downgrade to JWT 4.0 will fix the problem.

I'm going to try that on my code sample as well.

**Comment by coolboy** [comment]
@STIHLFredGuanzon sure, let me know the result

**Comment by STIHLFredGuanzon** [comment]
I got a different error this time after downgrading the libraries to these:

Box.V2 2.15.4
Box.V2.JWTAuth 1.3.1
System.IdentityModel.Tokens.Jwt  4.0.4.403061554


In my part of the code where we get the tokej from boxJWT i no longer get a cast error:

`var userToken = boxJWT.UserToken(userId);`

Instead I get this error:

{"{\"error\":\"invalid_request\",\"error_description\":\"Cannot obtain token based on the enterprise configuration for your app\"}"}

I assume something in my Box console for the calling app in not configured correctly.

I sent the message to my Box tech rep for further diagnosis.

**Comment by coolboy** [comment]
@STIHLFredGuanzon 

Looks like the SDK is working but your app needs to be authorized

Please check https://developer.box.com/v2.0/docs/configuring-box-platform of (4. Grant Access in Enterprise Admin Console)

**Comment by coolboy** [comment]
Closing this issue for now.

We will consider downgrading to JWT 4 if there are more requests for it
