### ISSUE TITLE
Why does GetEnterpriseUserAsync(user_type: "external" return any external users?

### ISSUE THREAD

**Issue by asd1** [box/box-windows-sdk-v2#329]
When I try to get a list of external users that use our Box Enterprise using the GetEnterpriseUserAsync it returns a list of 0 users. When I request "all" users it only returns Managed users. When I use the website to view the external users I can see 25 external users. How can I get the external users?

**Comment by coolboy** [comment]
hmm, seems the api is returning empty array to the SDK, will check with the team and get back to you

**Comment by coolboy** [comment]
ok @asd1 , so far for users/ endpoint right now, we don't support wild query on external user, you have to use the complete login as filter_term to make it return

Sample request/response 
![image](https://cloud.githubusercontent.com/assets/404691/25922862/af6ab834-358f-11e7-9dab-1fe48b692402.png)

**Comment by coolboy** [comment]
Our doc -> https://developer.box.com/reference#get-all-users-in-an-enterprise
