### ISSUE TITLE
.NET 4.5 support

### ISSUE THREAD

**Issue by nsouren** [box/box-windows-sdk-v2#337]
Hello, do you have plans to switch using .NET Framework 4.5 to get rid of Microsoft.Bcl  and Microsoft.Net.Http libraries?
Thanks.

**Comment by coolboy** [comment]
Hi @nsouren 

Yes, that's what I want to do and working with various team in order to put it on the read map

Will update this thread once I have any update for you and thank you for the feedback!

**Comment by coolboy** [comment]
BTW, @nsouren I also want to learn more about your use case, why do you need it?

It will help me to push this change forward

**Comment by coolboy** [comment]
Just update to 461 -> https://github.com/box/box-windows-sdk-v2/pull/357
