### ISSUE TITLE
Could BoxFileManager GetInformationAsync be changed to accept an IEnumerable<string> rather than List<string> for its fields parameter?

### ISSUE THREAD

**Issue by Dave-Lowndes** [box/box-windows-sdk-v2#340]
Currently, it's impossible to pass a readonly collection to this API - and in our usage, that's normally all we ever need to do.

**Comment by coolboy** [comment]
We are using List for fields in BoxFileManager every where, but I think your suggestion is valid.

I will mark it as our todo item, and welcome to submit a pull request for this fix.

Thank you for the feedback!

**Comment by Dave-Lowndes** [comment]
I've made changes to the sources and have attempted to commit/push them back, but I'm a newcomer when it comes to Git, so I don't know whether I've been successful or not!

**Comment by coolboy** [comment]
Hi @Dave-Lowndes 

Here is the link for how to make a PR into our repo -> https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by Dave-Lowndes** [comment]
Thanks for that, I see now the error I made was to clone directly from the master project rather than forking it for my account first. I hope my pull request is now visible to you.
