### ISSUE TITLE
A first chance exception of type 'System.MissingMethodException' occurred

### ISSUE THREAD

**Issue by seandixon** [box/box-windows-sdk-v2#343]
Huge sigh...I'm at my wits end. I have been working on an app for downloading files from box.com. Up until now everything has been going very well. I can get all kinds of information about folders and files. 

For example, this code perfectly returns a filename:
 ```
public static string getFileName(string fileId)
        {
            var client = getBoxClient();
            var result = client.FilesManager.GetInformationAsync(fileId).GetAwaiter().GetResult();
            return result.Name;
        }
```

For some reason, I'm getting the runtime error "System.MissingMethodException" whenever I call the DownloadStreamAsync method. Here is my code:
```
public static byte[] getBoxFile(string fileId)
        {
            var client = getBoxClient();
            using (Stream stream = client.FilesManager.DownloadStreamAsync(fileId).GetAwaiter().GetResult())
            using (MemoryStream ms = new MemoryStream())
            {
                int count = 0;
                do
                {
                    byte[] buf = new byte[8192];
                    count = stream.Read(buf, 0, 8192);
                    ms.Write(buf, 0, count);
                } while (stream.CanRead && count > 0);

                return ms.ToArray();
            }

        }


```
I've done everything I can think of and I can't get this method to work. All other functions are working fine.

**Comment by seandixon** [comment]
If I throw out everything and just run this code (which obviously doesn't do anything):

`       public static byte[] getBoxFile(string fileId)
        {
            var client = getBoxClient();           
            client.FilesManager.DownloadStreamAsync(fileId).GetAwaiter().GetResult();
            byte[] buf = new byte[8192];
        }`

 it still throws this error: 'System.Threading.Tasks.Task`1<System.IO.Stream> Box.V2.Managers.BoxFilesManager.DownloadStreamAsync(System.String, System.String, System.Nullable`1<System.TimeSpan>)'.

**Comment by coolboy** [comment]
try follow the example here and let me know if it works

https://github.com/box/box-windows-sdk-v2/blob/7e560863dbbdd9fb592083b70dac80d936615612/Box.V2.Test.Integration/BoxFilesManagerTestIntegration.cs#L50
