### ISSUE TITLE
Box SDK UploadAsync extremely slow

### ISSUE THREAD

**Issue by Band-Aid** [box/box-windows-sdk-v2#348]
Hi, UploadAsync is extremely slow to upload.
5MB file takes 60seconds to upload.

I tried uploading the same file using the Box Ruby SDK and this only takes 2 - 3 seconds
Test was conducted on the on the same machine; Windows 7 SP1 .net 4.5.2

What could be the cause?
Here's my c# code.

` 
using (FileStream fileStream = File.OpenRead(@localFilePath + fileName))
            {
				
				var fileRequest = new BoxFileRequest
				{
					Name = fileName,
					Parent = new BoxFolderRequest { Id = parentFolderId }
				};
					long length = fileStream.Length;
					// Write length to console
					Console.WriteLine("Length: {0}", length);
				
                var bFile = await client.FilesManager.UploadAsync(fileRequest, fileStream);
                Console.WriteLine("{0} uploaded to folder: {1} as file: {2}", localFilePath, parentFolderId, bFile.Id);
                Console.WriteLine("Time spend : {0} ms", timer.ElapsedMilliseconds);

			}`

**Comment by coolboy** [comment]
Which version of the .net sdk are you using?
Have you tried UploadUsingSessionAsync?

**Comment by Band-Aid** [comment]
Using 2.15.6 listed here
https://www.nuget.org/packages/Box.V2/

I thought UploadUsingSessionAsync only works for files that are 100MB.

I'm having trouble with files that are only 5MB in size.

**Comment by Band-Aid** [comment]
@coolboy 
So after testing this with several environments. Something is wrong when running the code on Windows 7.
Windows 7 takes roughly around 40 - 50 seconds to upload a 5MB file
Windows 10 takes 3 seconds.
I've upgraded Windows 7 to .net 4.6.1 but same results.

There seems to be a compatibility issue with Win 7.

**Comment by coolboy** [comment]
Hi @Band-Aid 

Thanks for the update, so both win7 and win10 machines are under the same network environment?

I suspect this is because Box.V2 is a Portable Class Library which may have these kinds of issues since PCL is very old.

We are planing to build Box.V3 shortly and completely drop the PCL support which should fix all these performance problems.

In the mean time I am curious to see if Box.V2.Core could fix this problem, do you have time to try? https://www.nuget.org/packages/Box.V2.Core

**Comment by Band-Aid** [comment]
@coolboy just tried with Box.V2.Core but am getting the folllowing method not found error.
I just have to replace the box sdk library with Box.v2.core right?

System.AggregateException: 。 ---> System.MissingM
ethodException: Method not found: 'System.String System.String.Format(Sy
stem.IFormatProvider, System.String, System.Object, System.Object)'
   場所 Box.V2.Managers.BoxResourceManager.AddAuthorization(IBoxRequest request,
 String accessToken)

**Comment by Band-Aid** [comment]
Oops. I pasted the wrong error message above.
Here's the actual message I was refereeing to.

>>System.Net.Http, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

The machine I'm building the code and executing is different and I think this may be related to this 
thread => . .net 4.6.1 is pointing to wrong system.net.http assembly.
https://github.com/dotnet/corefx/issues/9846

**Comment by coolboy** [comment]
Hi @Band-Aid 

Install Microsoft.Bcl.Async should resolve this problem

**Comment by Band-Aid** [comment]
@coolboy nope. not working even after installing Microsoft.Bcl.Async

**Comment by coolboy** [comment]
Per @Band-Aid report, it has been fixed per our .net45 upgrade
