### ISSUE TITLE
Could not load file or assembly Crypto

### ISSUE THREAD

**Issue by maxcap888** [box/box-windows-sdk-v2#365]
When I dropped the Box.V2 dll into my APTNET Core class and try to get a token, I get the following error:
System.IO.FileNotFoundException: Could not load file or assembly 'crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942'. The system cannot find the file specified.
File name: 'crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942'
   at Box.V2.JWTAuth.BoxJWTAuth..ctor(IBoxConfig boxConfig)

Upon further research it looks like the issue is in the RSUtilities class using an older version of the BouncyCastle package.

**Comment by coolboy** [comment]
Hi @maxcap888 

Which version of the Box.V2 dll were you dropping?
Do you have the crypto 1.8.1.0 on the environment?
What do you mean by dropping, VS2017 should pull all the dlls for you while building.

By checking our code -> https://github.com/box/box-windows-sdk-v2/blob/master/Box.V2/packages.config#L3 I can see we have crypto 1.8.1.0 as our dependency.
