### ISSUE TITLE
Debug symbols/symbol server available for releases?

### ISSUE THREAD

**Issue by Dave-Lowndes** [box/box-windows-sdk-v2#368]
If they are, how do we get them? If not, can we get them for the next release please?

Several times when investigating issues, I've wanted to be able to debug into the SDK code to see what's happening, but have been unable to do so.

While I can examine the source code here, it's not as productive as being able to debug and see what actually happens.

**Comment by coolboy** [comment]
Hi @Dave-Lowndes 

Sure, I will include those pdb files and put them here https://github.com/box/box-windows-sdk-v2/releases

**Comment by coolboy** [comment]
For our very own symbol server, it's a good idea and I will see if we can do that as well

**Comment by coolboy** [comment]
https://github.com/box/box-windows-sdk-v2/releases/tag/v3.0.0
