### ISSUE TITLE
Sporadic BadGateway (Http status 502) occurring when calling FilesManager.DownloadStreamAsync

### ISSUE THREAD

**Issue by Dave-Lowndes** [box/box-windows-sdk-v2#370]
In performance testing our service I'm encountering an occasional BoxException when we call DownloadStreamAsync.

The BoxException has no Error object, but the HttpStatusCode returns BadGateway (#502).

If I retry the operation (I've current just jumped the code back in the debugger) it succeeds.

Is this perhaps something that the API ought to hide from us by automatically retrying?

**Comment by coolboy** [comment]
Hi @Dave-Lowndes 

502 to me is a network environment issue but not a sdk issue

Not sure where did you jump back the code in the debugger to retry, but internally we don't have automatically retry for 502

**Comment by Dave-Lowndes** [comment]
Hi @coolboy,

I meant that I jumped my code back (in the debugger) to call DownloadStreamAsync again, and it always subsequently succeeded. I've since codified that exception to retry and it's worked consistently so far.

I presume it is an environmental issue (from the Box servers), but it's getting thrown as a BoxException from the API, and if the API handled it internally as a retry (as you do with other responses from the web interface), our code doesn't have to do it.

Information on http error 502 seems to imply that it is often a temporary problem - which does seem to be the case here from my testing results. Perhaps someone on the web end knows why the service gives rise to them sometimes?

**Comment by coolboy** [comment]
Hi @Dave-Lowndes 

You are handling it the right way but I don't think retry on 502 inside the SDK is a good idea.

We did see similar problems from other customers as well, but it's hard for us to diagnose since I could not reproduce it under our network env.

Is the server behind a proxy or a vpn, where is it?

**Comment by Dave-Lowndes** [comment]
@coolboy, can you elaborate on why you think handling 502 with a retry isn't a good idea? If it's not a good idea for handling in the SDK, it's presumably not a good idea for us to handle in our code - but doing so does appear to work fine.

With regards to reproducing the issue - we've been running continuous testing over several hours, downloading many smallish files rapidly, and the 502 only occurred about once an hour on average, and as I say, an immediate retry of the API call has always succeeded.

I've reproduced the issue from both my development VM on our company LAN (in the UK), talking to the Box service (wherever that is), and from a MS Azure hosted VM (located in the UK) to the ame Box service, so the common factor there is the Box end and whatever infrastructure is employed there, which I have no idea about.

**Comment by coolboy** [comment]
Hi @Dave-Lowndes 

SDK will handle the code from box server but should not handle 502 which is from the network layer, IMO.
I don't think we are returning 502 programmatically anywhere in the server.

e.g. for 429 (TooManyRequests) we will be confident that we are hitting the limit, but for 502, the reason will be different by the network environment.

Maybe this reveals some network infrastructure problem for box globally, but again, not something SDK should handle.

**Comment by Dave-Lowndes** [comment]
> I don't think we are returning 502 programmatically anywhere in the server.

Could you check to be sure?

I appreciate what you say about the 502 if your service isn't creating them, however, regardless of why they arise (they do), they cause a problem for users of your APIs.

I note that the Wikipedia page on http error codes says of 5xx codes: _"the server should include an entity containing an explanation of the error situation, and indicate whether it is a temporary or permanent condition"_, so if it is temporary, I think the operation should be retried.

Without your API code handling these real world implementation details, user application code such as our own is having to encounter these situations and subsequently code around them. For example, here's the mess of code I've got to handle retries for just 1 API call. It's not pretty when you have to have retry loops and more code in exception handling for situations that aren't that exceptional!:

	bool Retry;
	do
	{
		Retry = false;
		try
		{
			using ( Stream stream = await actorClient.FilesManager.DownloadStreamAsync( file.Id ) )
                        {
                            // Do our work with the stream
                            ...
                         }
		}
		catch ( BoxException ex )
		{
			if ( ex.Error != null )
			{
				if ( ex.Error.Code == "rate_limit_exceeded" )
				{
					await Task.Delay( 1000 );
					Retry = true;
				}
				else
				{
					// It's not a retry, give up.
					throw;
				}
			}
			else
			{
				// This seems to be retry-able
				if ( ex.StatusCode == System.Net.HttpStatusCode.BadGateway )
				{
					// In tests a delay hasn't been needed, but play safe
					await Task.Delay( 100 );
					Retry = true;
				}
				else
				{
					throw;
				}
			}
		}
	}
while ( Retry );

**Comment by coolboy** [comment]
Hi @Dave-Lowndes ,

I did a quick search in our codebase, 80% sure we are not returning 502 in the code.

It may come from our out-bound proxy, any router/switch between yours and our server.

One thing I would recommend is to set a break point in https://github.com/box/box-windows-sdk-v2/blob/0e14227cbbf5311069250a860b55d3fc8d3a8790/Box.V2/Request/HttpRequestHandler.cs#L73 and see the complete response from the server when 502 happened

**Comment by Dave-Lowndes** [comment]
Hi @coolboy,

Using the current release PDB (thanks very much for supplying that) and sources, trying to set a breakpoint on L73 gives:

_The following breakpoint cannot be set:
At HttpRequestHandler.cs, line 73 character 21 ('Box.V2.Request.HttpRequestHandler.ExecuteAsync(IBoxRequest request)') 
The breakpoint failed to bind._

However, setting it on L76 is OK :)

I'll set a test going and see if I can encounter the 502 error again. I'll let you know what that shows.

**Comment by Dave-Lowndes** [comment]
Hi @coolboy,

After a 24hr continuous test we've not seen the 502 error occur again - typical! :)

However, we have seen BoxException for 504's (GatewayTimeout), and had several occurrences of TaskCanceledException  (I think the latter can occur when the HttpClient operation has a timeout) - neither of which we'd observed before.

**Comment by coolboy** [comment]
Hi @Dave-Lowndes 

Glad to see the pdb file works for you! And do let us know if there is anything else we can help
