### ISSUE TITLE
Potential null reference exception in HttpRequestHandler.ExecuteAsync ?

### ISSUE THREAD

**Issue by Dave-Lowndes** [box/box-windows-sdk-v2#374]
In Box.V2/Request/HttpRequestHandler.cs, the retryAfterHeader variable is used on L88 after having been checked for non-null on L84, however the expression on L82 circumvents the null test.

So, if retryAfterHeader is null, and (response.StatusCode == TooManyRequests && !isMultiPartRequest) is true, it would give rise to a null reference exception.

Whether that could ever arise in practice, I don't know, but it may be better to never find out.

**Comment by coolboy** [comment]
Hi @Dave-Lowndes 

Thanks for running analysis and reporting issues here.

Per my investigation, looks like RetryAfter could not be null according to here -> https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/Headers/HttpResponseHeaders.cs

I will close this issue for now, but do reopen if you have other opinion

**Comment by Dave-Lowndes** [comment]
Hi @coolboy,

If it can't be null then the test for non-null on L84 in [HttpRequestHandler.cs](https://github.com/box/box-windows-sdk-v2/blob/master/Box.V2/Request/HttpRequestHandler.cs) is redundant and ought to be removed.

**Comment by coolboy** [comment]
you are correct, I will work on a fix

**Comment by Dave-Lowndes** [comment]
@coolboy, OK, thanks. If the value can't be null, then just a debug assert in the code would seem most appropriate.

While you're looking at that code, can you have a look at the numRetries usage that I flagged up a while ago too (issue #362)? It seems wrong to me to have your API impose a different retry scheme to whatever the underlying web service responds with. If you remove L23 and the use in L85, that would mean your API is behaving as the underlying web service says to do.

**Comment by carycheng** [comment]
Seems like this direct issue has been resolved, #362 has been closed as well, please reopen if there is something I've missed, thanks!
