### ISSUE TITLE
Will the tutorial video be updated?

### ISSUE THREAD

**Issue by ImranMoTown** [box/box-windows-sdk-v2#376]
The tutorial video referenced in the readme is out of date and refers to projects in the Legacy folder.  Will a new tutorial video be published?

Box Windows SDK Video Tutorial: https://youtu.be/hqko0hxbaXU

**Comment by coolboy** [comment]
Hi @ImranMoTown 

Totally, we should update the video by using our latest code and also demo the capability for .net core, e.g. development under mac

I will make it into our backlog

**Comment by Chiliyago** [comment]
this is much needed asap.  I am newbie and having real difficulty.  Need real demo's

**Comment by coolboy** [comment]
Totally, currently I am working on other high priority tasks, so I will mark it in the backlog

In the mean time, please put any question you have and I will see if I can answer

**Comment by carycheng77** [comment]
Hey @ImranMoTown and @Chiliyago apologies for the delay. We now have tutorial videos on how to get up and running with Box SDK's [here](https://www.boxdevelopertraining.com/courses/level-2-understanding-authentication-and-account-types) 

There is a .Net specific one coming soon as well. Thanks!
