### ISSUE TITLE
UploadAsync closes the stream

### ISSUE THREAD

**Issue by andrew-grichkevitch** [box/box-windows-sdk-v2#38]
Hi,

I create file, save it into MemoryStream and then pass it to SDK to Upload into box.com. This logic works for me except in one case.

When my access token get expired and I call UploadAsync, SDK automatically updates tokens and repeats the request. But first request failed due to expired tokens and stream get closed. As a result, repeated request failed too, due to closed stream.

How to deal with it?

Thanks

**Comment by SpiritBob** [comment]
@brianytang If you're disposing the HttpResponse, the only time it will actually dispose anything, is if you have a stream content, so perhaps the workaround is simply not disposing any http responses, because that would end up closing the interactive user's stream.
