### ISSUE TITLE
GetFolderItemsAsync not returning the FieldItemCollection

### ISSUE THREAD

**Issue by jkyadav** [box/box-windows-sdk-v2#380]
I'm using below code get the items of the parent folder, but this does not return the item collection can any one point to right direction.

Instead of _**BoxFolder**_ I tried to put **_BoxItem_**, but that also did not work, as this is not mentioned anywhere what list of fields **_GetFolderItemsAsync_** method will take.

Though getting the **_FieldSyncState_** value

```
         var task = Task.Run(async () =>
                {
                    var fields = new List<string>();
                    fields.Add(BoxFolder.FieldCreatedBy);
                    fields.Add(BoxFolder.FieldDescription);
                    fields.Add(BoxFolder.FieldModifiedBy);
                    fields.Add(BoxFolder.FieldName);
                    fields.Add(BoxFolder.FieldOwnedBy);
                    fields.Add(BoxFolder.FieldPathCollection);
                    fields.Add(BoxFolder.FieldSize);
                    fields.Add(BoxFolder.FieldSyncState);
                    fields.Add(BoxFolder.FieldItemCollection);

                    return await userClient.FoldersManager.GetFolderItemsAsync("0", 500, fields: fields);
                });
```

**Comment by coolboy** [comment]
Hi @jkyadav 

I am not getting your question, so what's response returned to you and what are you looking for?

Our reference doc -> https://developer.box.com/reference#get-a-folders-items

**Comment by jkyadav** [comment]
Actually what I'm trying to achieve is that according to document GetFolderItemsAsync method will return items and folder of the folder id , so I'm passing the field FieldItemCollection to get the sub folder and parent folder items as well, but this method not returning the items of sub folders.

I'm not sure if I'm calling correct method.

**Comment by carycheng77** [comment]
Hey @jkyadav, this api call will only return the folder items within the folder you specified with the ID. Unfortunately it will not recursively retrieve sub folder items down the folder tree. 

Let us know if you have any other issues or we are referring to the same thing, thanks!
