### ISSUE TITLE
The AdminToken() method throws a reference exception

### ISSUE THREAD

**Issue by aibars** [box/box-windows-sdk-v2#384]
While trying to create an AdminToken from BoxJWTAuth object, I get a Newtonsoft reference exception:

"Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by coolboy** [comment]
Hi @aibars 

Which version of the SDK are you using?

Here is the latest https://www.nuget.org/packages/Box.V2/3.1.0

**Comment by aibars** [comment]
Hi @coolboy ,
That's the version I'm currently using.
ConstructJWTAssertion() method is throwing such exception at 
 string assertion = tokenHandler.WriteToken(token);

**Comment by aibars** [comment]
@coolboy it seems that there is a missing reference on the System.IdentityModel.Tokens.Jwt namespace so I guess it is not a direct Box SDK issue

**Comment by coolboy** [comment]
@aibars 

Cool, will you be able to make Box.V2 work now? And what's ur resolution?

**Comment by aibars** [comment]
@coolboy No, not yet. I need to wait for a reply [here](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/701). I tried what he suggested with no success.
Thanks

**Comment by coolboy** [comment]
hmmm, the binding redirect should work, not sure why it doesn't for you

**Comment by aibars** [comment]
@coolboy well, the Nuget package adds this to the app.config after install:
```
<dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
      </dependentAssembly>
```

System.IdentityModel.Tokens.Jwt is looking for 9.0.1 so it falls under that range.

**Comment by coreygrubbFHL** [comment]
Was this solved? I am having the exact same issue with Box.V2.3.4.2 

I have the same assembly binding in my config and am also seeing "Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies."

thrown when I reach the following

//var session = new BoxConfig()
var serviceAccountClient = session.AdminClient(session.AdminToken());


Thanks

**Comment by coolboy** [comment]
Hi @coreygrubbFHL 

Try to add assembly binding redirect in your app.config to last version of Newtonsoft.Json:

<runtime>

    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">

      <dependentAssembly>

        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
       </dependentAssembly>

     </assemblyBinding>
  </runtime>

Then

right click on your project.
click on "Manage Nuget packages"
in the Update Tab, update all the package.
rebuild your project.
Done

**Comment by coreygrubbFHL** [comment]
Thank you for the response. I tried that and it did not help unfortunately. I updated the packages and this is what I have in the app.config

<assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-11.0.0.0" newVersion="11.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Tokens" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.1.0" newVersion="5.2.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.IdentityModel.Tokens.Jwt" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.1.0" newVersion="5.2.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.IdentityModel.Logging" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.1.0" newVersion="5.2.1.0" />
      </dependentAssembly>
      <dependentAssembly>


I am attempting the following:
`using (Stream fs = new FileStream("BoxConfig.json", FileMode.Open))
	   {
                var session = new BoxJWTAuth(BoxConfig.CreateFromJsonFile(fs));
		var serviceAccountClient = session.AdminClient(session.AdminToken());
	    }`


It seems that I am in an endless loop of package dependencies.

Whenever I hit the one of those methods, it throws an exception saying it is unable to locate the correct version of one of the packages that gets installed along with the Box SDK. 

It is always the previous version of one of those. For example, if I have Newtonsoft.Json 10.0.0.0 it looks for 9.0.0.0 or if I have Microsoft.IdentityModel.Tokens version 5.2.1 it looks for version 5.1.4.0

It does this until I have downgraded packages to the point that those methods are no longer included as part of the Box .NET SDK

Thanks in advance for any additional help. It seems like my project is ignoring the assembly bindings in the app.config
