### ISSUE TITLE
OAuth2 documentation points to legacy sample project

### ISSUE THREAD

**Issue by ohadschn** [box/box-windows-sdk-v2#386]
The main README says:

> Bundled with the SDK are sample applications for both Windows 8 and Windows Phone which include sample OAuth2 Workflows

Presumably it is referring to https://github.com/box/box-windows-sdk-v2/tree/master/Legacy/Box.V2.Samples.W8 and https://github.com/box/box-windows-sdk-v2/tree/master/Legacy/Box.V2.Samples.WP (as a search for `OAuth2Sample` suggests).

I'm assuming looking at legacy samples is not a good idea... could you provide up to date samples or at least some code snippets?

**Comment by coolboy** [comment]
we will update it
