### ISSUE TITLE
Multi-threading Use of Single BoxClient Instance

### ISSUE THREAD

**Issue by Richardsonke** [box/box-windows-sdk-v2#388]
I can't find any documentation for this, but sorry if I missed it somewhere.  Is a single BoxClient instance safe for use by multiple threads in the same process?  I would like to use a single BoxClient instance in a Parallel.ForEach instead of a new one each time.  I've tested it and it seems to work, I just wanted to make sure I was not missing some possible edge case that will break things.  Thanks for your help.

**Comment by coolboy** [comment]
Hi @Richardsonke,

BoxClient should be thread safe, but we are not fully committed to it officially.
So we don't have any test or use cases to verify that.

You should do your own test before you decide to make multi-threading into production 

But yes, if any problem, please report here.

**Comment by ohadschn** [comment]
@coolboy please forgive my forwardness but IMHO this is not good enough. It is absolutely essential for the `BoxClient` to be thread-safe, as it doesn't make sense to create a new one for each request in a mult-threaded environment...

**Comment by guilmori** [comment]
Any updates on this ?
Can a BoxClient be used as a singleton in a web app, which is responding to many parallel requests, where multiple requests may trigger the refresh of Access Token at the same time?
I'm using BoxJWTAuth.
