### ISSUE TITLE
Extract interfaces for testability

### ISSUE THREAD

**Issue by ohadschn** [box/box-windows-sdk-v2#389]
Most, if not all, public classes should implement interfaces. This will greatly help testability. 
For example if `BoxClient` implemented `IBoxClient`, I could replace it with an in-memory mock in unit tests.
The same is true for all classes deriving from `BoxResourceManager`, etc.

**Comment by coolboy** [comment]
Hi @ohadschn 

I think it's a good idea. But for clarification what kind of IBoxClient & IBoxResourceManager are you looking for?

A PR is also welcome

Thanks

**Comment by ohadschn** [comment]
I mean an interface that contains all public methods/properties.
So in my code I could have `IBoxClient _boxClient` and do things like `_boxClient.AddResourcePlugin(...)` and more importantly `_boxClient.EventsManager.EnterpriseEventsAsync()` (that will require the entire chain to be interface based, e.g. `_boxClient.EventsManager` would be an `IBoxEventsManager`.

I am aware of the PR option, we'll see who gets to it first :)

**Comment by Cpcrook** [comment]
I'll be tackling this soon-ish.  

Better late than never, because writing tests that involve mocking the SDK right now is killing my soul using Moq due to all the non-virtuals.

**Comment by mwwoda** [comment]
Closed under #735
