### ISSUE TITLE
Provide event type constants

### ISSUE THREAD

**Issue by ohadschn** [box/box-windows-sdk-v2#390]
It would be very convenient if [user event names](https://developer.box.com/reference#standard-user-events) (like `TASK_ASSIGNMENT_CREATE`) and [enterprise event names](https://developer.box.com/reference#enterprise-events) (like `CHANGE_FOLDER_PERMISSION`) would be exposed as constants somewhere (preferably as `static readonly` to avoid recompilation if they ever change).

**Comment by coolboy** [comment]
Good idea, this will be on our TODO list

**Comment by carycheng** [comment]
#428, thanks!
