### ISSUE TITLE
`BoxEventsManager.EnterpriseEventsAsync` triggers the `DateTimeInvalidLocalFormat` Managed Debugging Assistant

### ISSUE THREAD

**Issue by ohadschn** [box/box-windows-sdk-v2#393]
> Managed Debugging Assistant `DateTimeInvalidLocalFormat` : 'A UTC `DateTime` is being converted to text in a format that is only correct for local times. This can happen when calling `DateTime.ToString` using the 'z' format specifier, which will include a local time zone offset in the output. In that case, either use the 'Z' format specifier, which designates a UTC time, or use the 'o' format string, which is the recommended way to persist a DateTime in text.

The issue is the following line:
https://github.com/box/box-windows-sdk-v2/blob/0e14227cbbf5311069250a860b55d3fc8d3a8790/Box.V2/Managers/BoxEventsManager.cs#L42

Apparently because `RFC3339DateFormat` contains the `z` formatting specifier:
https://github.com/box/box-windows-sdk-v2/blob/cb5a10a4ab4b9274e788a7e782885ec3d1061655/Box.V2/Config/Constants.cs#L167

**Comment by coolboy** [comment]
Hi @ohadschn 

Thanks for reporting this, but what is `Managed Debugging Assistant` and what's the repo steps?

Are you recommending using `o` as below?
RFC3339DateFormat = "yyyy-MM-ddTHH:mm:ssooo";

**Comment by ohadschn** [comment]
Hi @coolboy,

> [Managed debugging assistants (MDAs)](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/diagnosing-errors-with-managed-debugging-assistants) are debugging aids that work in conjunction with the common language runtime (CLR) to provide information on runtime state. The assistants generate informational messages about runtime events that you cannot otherwise trap. You can use MDAs to isolate hard-to-find application bugs that occur when transitioning between managed and unmanaged code. 

The repro step would simply be to debug a program that does something like `BoxEventsManager.EnterpriseEventsAsync(DateTime.UtcNow)` in Visual Studio with MDA enabled (sepcifically [dateTimeInvalidLocalFormat](https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/datetimeinvalidlocalformat-mda))

As for the problem at hand, one line below in the constants file has this: https://github.com/box/box-windows-sdk-v2/blob/cb5a10a4ab4b9274e788a7e782885ec3d1061655/Box.V2/Config/Constants.cs#L168

So I'm guessing the author's intention was something like 
```cs
createdAfter.Value.ToString(createdAfter.Value.Kind == DateTimeKind.Utc 
    ? RFC3339DateFormat_UTC 
    : RFC3339DateFormat);
```

**Comment by carycheng77** [comment]
Hey @ohadschn 

Would love to get more context on the utc vs non-utc time format. We ran this snippet of code here

<img width="813" alt="screen shot 2017-09-21 at 6 30 11 pm" src="https://user-images.githubusercontent.com/6364733/30725650-1cf1005a-9efb-11e7-93a9-cde231f12435.png">

And got the following results:

<img width="384" alt="screen shot 2017-09-21 at 6 30 20 pm" src="https://user-images.githubusercontent.com/6364733/30725661-2e6e3fbe-9efb-11e7-984d-0f52aa6bf188.png">

Would love to get more understanding on the parts of the time format that might be causing issues. Thank you!

**Comment by ohadschn** [comment]
Hi @carycheng77,

The problem with the current code is that it assumes the given `DateTime` object is of `DateTimeKind.Local` and calls `Constants.RFC3339DateFormat` for it, which includes the [`z` custom format specifier](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#the-z-custom-format-specifier). Since that specifier represents the *signed offset of the local operating system's time zone from Coordinated Universal Time (UTC)*, if I pass in `DateTime.UtcNow` I'm going to get something like `2017-09-22T12:32:16+03:00` which doesn't make sense because UTC times obviously have **zero** offset from UTC (not +3 hours)...

Here's what I think you should do:
1. The first thing you do when you get a `DateTime` object is convert it to UTC using `DateTime.ToUniversalTime`. This is actually the [official Box API recommendation](https://developer.box.com/v2.0/reference#section-date-format). There could be [subtle issues here with things like daylight saving](https://stackoverflow.com/a/1201428/67824), which is why switching to `DateTimeOffset` (https://github.com/box/box-windows-sdk-v2/issues/394) is highly recommended. I suppose you could also throw an exception if the `DateTime` isn't of `DateTimeKind.UTC` but that might be a little extreme.
1. Get rid of `RFC3339DateFormat` and `RFC3339DateFormat_UTC` and use the ["o" custom format specifier](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#the-round-trip-o-o-format-specifier) instead (e.g. `createdAfter.Value.ToString("o")`), which represents ISO 8601. Since [RFC 3339 is a profile of ISO 8601](https://stackoverflow.com/questions/522251/whats-the-difference-between-iso-8601-and-rfc-3339-date-formats), you should be fine. It is actually equivalent to using the custom format specifier `yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK`, which is the same as `RFC3339DateFormat_UTC` except a bit more accrate in terms of second fractions.

**Comment by carycheng77** [comment]
#400
