### ISSUE TITLE
RestoreTrashedAsync should not mandate fileRequest.Name

### ISSUE THREAD

**Issue by ohadschn** [box/box-windows-sdk-v2#397]
According to the [docs](https://developer.box.com/reference#restore-a-trashed-item), the file name is only used if the item can't be restored with its previous name due to a conflict. However the code forces its use at all times:

https://github.com/box/box-windows-sdk-v2/blob/51a9935a9683971f9128bd193311f7dc4f542f4f/Box.V2/Managers/BoxFilesManager.cs#L886

**Comment by carycheng77** [comment]
Thanks for letting us know! 

#427
