### ISSUE TITLE
'ModifiedAt' property is not changed when item is deleted

### ISSUE THREAD

**Issue by Rod-Sychev** [box/box-windows-sdk-v2#40]
So when the item is moved to Trash folder it's 'ItemStatus' property is changed to "trashed" however 'ModifiedAt' property stays intact. I would expect it to be amended once item status is tweaked.
Is this a bug or "feature"?

**Comment by coolboy** [comment]
Closing old issues

Feel free to reopen it.

**Comment by Rod-Sychev** [comment]
I wonder why this issue hasn't been addressed?

**Comment by coolboy** [comment]
Hi @Rod-Sychev ,

This is not a SDK issue, but on the File-System side.

They told me this is by design.

**Comment by coolboy** [comment]
And their reason is `no change on the content`

**Comment by Rod-Sychev** [comment]
This is truly bizarre.

**Comment by mattwiller** [comment]
@Rod-Sychev I just tested and the `modified_at` timestamp of the file does not change when the item is deleted.  Instead, you should read the `TrashedAt` property to determine if/when the item was deleted.

**Comment by Rod-Sychev** [comment]
@mattwiller Thanks for the tip Matt!
