### ISSUE TITLE
Method to remove folder_upload_email

### ISSUE THREAD

**Issue by johnliss** [box/box-windows-sdk-v2#407]
I see methods to create/edit upload email addresses:
`BoxFolderRequest folderReq = new BoxFolderRequest()
{
   Id = "YOUR_FOLDER_ID",
   FolderUploadEmail = new BoxEmailRequest() {  Acesss = "open" }
};
BoxFolder f = await _foldersManager.UpdateInformationAsync(folderReq);`

is there a method or a way to **remove** the Upload Email Address / folder_upload_email?

I have tried using **UpdateInformationAsync** with null and it does not remove the email...
`BoxFolderRequest request = new BoxFolderRequest()
{
   Id = folder.Id, 
   FolderUploadEmail = null
};
var ret = boxclient.FoldersManager.UpdateInformationAsync(request).Result;
`

**Comment by carycheng77** [comment]
Hey @johnliss 

I just tried it and it seemed to work fine. I did something like this:
`            BoxFolderRequest openFolderEmailUploadReq = new BoxFolderRequest() { Id = folderId, FolderUploadEmail = new BoxEmailRequest() { Access = "open" } };
            BoxFolder folder = await _client.FoldersManager.UpdateInformationAsync(openFolderEmailUploadReq);

            folder.FolderUploadEmail = null;`

Let me know if this helps!
