### ISSUE TITLE
Folder Object - Missing Properties

### ISSUE THREAD

**Issue by AlexanderWebbe** [box/box-windows-sdk-v2#411]
The .NET SDK missing the below properties from the Folder Object

- trashed_at
- purged_at
- content_created_at
- content_modified_at
- can_non_owners_invite
- is_externally_owned
- allow_shared_link_access_levels

**Comment by carycheng77** [comment]
@AlexanderWebbe , thank you for the heads up! We'll take a look into this and see why the fields are missing if everything checks out the change should be implemented soon, thanks!

**Comment by carycheng77** [comment]
#414 Thanks!
