### ISSUE TITLE
FilesManager.PreflightCheck throwing unhandled exception

### ISSUE THREAD

**Issue by jkyadav** [box/box-windows-sdk-v2#412]
I'm trying to validate before uploading a file, if the file already exist in Box with the same name,  then will upload as a new version, otherwise as a new file, same need to do for size validation.

```
try
{
	var req = new BoxPreflightCheckRequest() { 
	    Name = "abcd.txt", 
	    Parent = new BoxRequestEntity() { Id = "0" }
	};
											 
	//exception will be thrown if name collision or storage limit would be exceeded by upload									 
	var p = userClient.FilesManager.PreflightCheck(req).Result;
}
catch (BoxPreflightCheckConflictException<BoxFile> bex)
{
	//Handle file name collision error	
}
catch (BoxException bex)
{
	//Handle storage limit error 
}
```
When I call the above code, if the file already exist it does not executes the "**BoxPreflightCheckConflictException**" block nor the "**BoxException**"  it just throw unhandled exception.

How to achieve this, can someone help me, let me know if need more details.

**Comment by jkyadav** [comment]
@coolboy and @carycheng77  Can you guys look at his? or any guidance to handle these requirement?

Thanks

**Comment by coolboy** [comment]
we will look into it

**Comment by carycheng77** [comment]
Hey @jkyadav 

Just tested this and it seems to be okay on our end. 
<img width="1510" alt="screen shot 2017-11-09 at 5 08 28 pm" src="https://user-images.githubusercontent.com/6364733/32638380-dac5581c-c573-11e7-933a-fac396a91059.png">



<img width="1506" alt="screen shot 2017-11-09 at 5 29 57 pm" src="https://user-images.githubusercontent.com/6364733/32638386-e135ff6c-c573-11e7-8e84-0a74ce9747c3.png">

Wondering what version of the .Net SDK are you using? 

Thanks!

**Comment by jkyadav** [comment]
@coolboy , @carycheng77 I'm using SDK version 3.1.0

 `<package id="Box.V2" version="3.1.0" targetFramework="net451" />`

**Comment by coolboy** [comment]
Hmm, but we could not repo it on our side, do you have a detailed repo step?

**Comment by jkyadav** [comment]
@coolboy I just created a sample application similar to attached screenshot by @carycheng77 and it worked, thanks.
But when try to execute the below code it throws unhandled exception, seems it works with async/await only. not sure whats wrong with below code.

Anyways thanks for the help @coolboy and @carycheng77 

```

public static void Test() {
           
            try
            {
                var req = new BoxPreflightCheckRequest()
                {
                    Name = "testP3.txt",
                    Parent = new BoxRequestEntity() { Id = "41142096941" }
                };
							 
              var p = userAccess.Data.FilesManager.PreflightCheck(req).Result;
            }
            catch (Box.V2.Exceptions.BoxPreflightCheckConflictException<BoxFile> bex)
            {
                //Handle file name collision error	
            }
            catch (Box.V2.Exceptions.BoxConflictException<BoxFile> bex)
            {
                //Handle file name collision error	
            }
            catch (Box.V2.Exceptions.BoxException bex)
            {
                //Handle storage limit error 
            }
        }

        static void Main(string[] args)
        {

            Test();

        }
```

**Comment by jkyadav** [comment]
Thanks
