### ISSUE TITLE
Box.V2.Models.BoxCollaborationRequest missing expires_at Json Property

### ISSUE THREAD

**Issue by kylefernandadams** [box/box-windows-sdk-v2#416]
Box.V2.Models.BoxCollaborationRequest is missing the expires_at Json Property. This forces developer to create a custom resource plugin when trying to edit a given collaboration's expires_at property value.

**Comment by carycheng77** [comment]
Hey @kylefernandadams ! 

I'll take a look at this now, thanks for letting us know!

**Comment by mattwiller** [comment]
@kylefernandadams In my testing with the API, it is not possible to set the `expires_at` field during Collaboration creation or update.  Can you help me understand how this field should be set?

**Comment by kylefernandadams** [comment]
I had to extend the CollaborationManager to get it to work correctly. Also you have to include the role in the call. Here's an example: https://gist.github.com/kylefernandadams/1cfcfed91f04371a725915646edc9528

**Comment by mattwiller** [comment]
@kylefernandadams When I make a call like that in Postman, it doesn't work correctly — the `expires_at` field is not actually set and is `null` in the returned object.  Does your account have some special configuration to be able to use that field?

**Comment by kylefernandadams** [comment]
@mattwiller It requires that the expires_at be not null. To test it, I essentially had to enable auto-expiration of collaborations in the Admin Console. Its something we should document either way. 

Here is a quick video: https://cloud.box.com/s/qj2y8hts7mmspqgelx7297rnwfzsmkhd
