### ISSUE TITLE
.NET SDK GetDownloadUriAsync not working

### ISSUE THREAD

**Issue by presnizky** [box/box-windows-sdk-v2#417]
Hi,
I'm a developer for Codelitt, and I'm creating an Enterprise Integration. I'm using the .NET SDK v3.2.0, and when I call the GetDownloadUriAsync method it takes forever to return the result, and the worst part is that it gives no error., so I can't figure out what is happening.

The code I'm using is this.
public async Task<Uri> GetDownloadUrl(string fileId) 
{ 
BoxClient client = this.GetClient(); 
Uri uri = await client.FilesManager.GetDownloadUriAsync(fileId); 
return uri; 
}

The client authenticates correctly, as I'm able to upload files, but getting the download uri is not working.

Let me know if you need further information.
Thanks.

Pablo Resnizky 
pablo@codelitt.com

**Comment by aibars** [comment]
I've been facing the same issue trying to use that method. Is there a way to solve it?
Thank you

**Comment by coolboy** [comment]
ok we will look at it

**Comment by carycheng77** [comment]
Hey @presnizky and @aibars,

Wondering what kind of error you guys are throwing if any? We just tested this function on our end it was able to return fine. 

<img width="1026" alt="screen shot 2017-11-17 at 10 36 21 am" src="https://user-images.githubusercontent.com/6364733/32963101-bf168080-cb83-11e7-87b5-2bead34a9c58.png">

I would also double check to make sure the client you are making this call from has access to that specific file you are trying to grab the download uri for, thanks!

**Comment by presnizky** [comment]
@carycheng77 Sorry for the delay on my response.  We're only using the service account to upload/download the files, and the files upload without any issues.  This method worked at some point, but it started failing a couple of weeks ago.

**Comment by carycheng** [comment]
@presnizky, apologies for the late reply. Wanted to know if you are still experiencing issues with this call. If you are, would love to dig into this for you. If you could email me your API Key at ccheng@box.com along with timestamp of failure(most recent) that would be a great starting point for us. Thank you!

**Comment by maparedev** [comment]
I am also getting issue while using  Stream downloadStream = client.FilesManager.DownloadAsync(fileId).Result; code, with the same client I can able to upload the file without any issue.

Below are two error messages from client.

•	The remote certificate is invalid according to the validation procedure.
•	The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel
