### ISSUE TITLE
Collaboration events source object isn't parsed

### ISSUE THREAD

**Issue by Enzzer** [box/box-windows-sdk-v2#418]
Hi,
When retrieving enterprise events, collaboration events aren't parsed correctly.
This happens because there is inconsistency in the source object format which for these type of events doesn't contain "type" or "item_type" field. This results in the Json parser returning a default BoxEntity object with null id and null type.

Thanks.

**Comment by carycheng77** [comment]
Hey @Enzzer, we'll take a look at this, thanks for letting us know

**Comment by Enzzer** [comment]
Hi @carycheng77 thanks for you reply,
The same issue happens for GROUP_CREATION, GROUP_EDITED and GROUP_DELETION: source object in raw json isn't parsed by the SDK.
