### ISSUE TITLE
When will you release new version to nuget?

### ISSUE THREAD

**Issue by rassy** [box/box-windows-sdk-v2#419]
Hi.
When will you release new version to nuget ?
I must delivery a Windows application using sdk for customer at Nov.30.

We hope to release new version.

Best regards.

**Comment by carycheng77** [comment]
Hey @rassy, thank you for reaching out, we plan on releasing a new version tomorrow. Thanks!

**Comment by carycheng77** [comment]
Hey @rassy, new version 3.3.0 is available on Nuget, let us know if you run into any issues, thanks!
