### ISSUE TITLE
Using the box windows sdk in powershell

### ISSUE THREAD

**Issue by whiggs** [box/box-windows-sdk-v2#426]
The first portion of this two part issue was oversight on my part, so I have removed that portion from the post.  However, the other portion is still an issue.  I have gotten in touch with box support, and this is the response that I received:

> my name is Johannes, your case has been escalated to me. I made a small test calling

> $adminClient.UsersManager.GetCurrentUserInformationAsync() |Format-List

> and ran into an exception.
>
> 
>` Exception              : System.AggregateException: One or more errors occurred. ---> > System.TypeInitializationException: The type 
>                         initializer for 'System.IdentityModel.Tokens.Jwt.JsonExtensions' threw an exception. ---> 
>                        System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, 
> Version=9.0.0.0, 
>                        Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The  
> system cannot find the file 
>                        specified.
>                            at System.IdentityModel.Tokens.Jwt.JsonExtensions..cctor()
>                            --- End of inner exception stack trace ---
>                            at System.IdentityModel.Tokens.Jwt.JsonExtensions.SerializeToJson(Object value)
>                            at System.IdentityModel.Tokens.Jwt.JwtPayload.Base64UrlEncode()
>                            at  
> System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.WriteToken(SecurityToken token)
>                            at Box.V2.JWTAuth.BoxJWTAuth.ConstructJWTAssertion(String sub, String 
> boxSubType)
>                            at Box.V2.JWTAuth.BoxJWTAuth.AdminToken()
>                            at Box.V2.JWTAuth.JWTAuthRepository.<RefreshAccessTokenAsync>d__21.MoveNext()
>                        --- End of stack trace from previous location where exception was thrown ---
>                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>                            at 
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>                            at Box.V2.Managers.BoxResourceManager.
> <RetryExpiredTokenRequest>d__11`1.MoveNext()
>                        --- End of stack trace from previous location where exception was thrown ---
>                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>                            at 
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>                            at Box.V2.Managers.BoxResourceManager.<ExecuteRequest>d__10`1.MoveNext()
>                        --- End of stack trace from previous location where exception was thrown ---
>                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>                            at 
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>                            at Box.V2.Managers.BoxResourceManager.<ToResponseAsync>d__9`1.MoveNext()
>                        --- End of stack trace from previous location where exception was thrown ---
>                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>                            at 
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>                            at Box.V2.Managers.BoxUsersManager.
> <GetCurrentUserInformationAsync>d__1.MoveNext()
>                            --- End of inner exception stack trace ---
>                        ---> (Inner Exception #0) System.TypeInitializationException: The type initializer for 
>                        'System.IdentityModel.Tokens.Jwt.JsonExtensions' threw an exception. ---> 
> System.IO.FileNotFoundException: Could 
>                        not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, 
> PublicKeyToken=30ad4fe6b2a6aeed' or 
>                        one of its dependencies. The system cannot find the file specified.
>                            at System.IdentityModel.Tokens.Jwt.JsonExtensions..cctor()
>                            --- End of inner exception stack trace ---
>                            at System.IdentityModel.Tokens.Jwt.JsonExtensions.SerializeToJson(Object value)
>                            at System.IdentityModel.Tokens.Jwt.JwtPayload.Base64UrlEncode()
>                            at 
> System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.WriteToken(SecurityToken token)
>                            at Box.V2.JWTAuth.BoxJWTAuth.ConstructJWTAssertion(String sub, String 
> boxSubType)
>                            at Box.V2.JWTAuth.BoxJWTAuth.AdminToken()
>                            at Box.V2.JWTAuth.JWTAuthRepository.<RefreshAccessTokenAsync>d__21.MoveNext()
>                        --- End of stack trace from previous location where exception was thrown ---
>                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>                            at 
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>                            at Box.V2.Managers.BoxResourceManager.
> <RetryExpiredTokenRequest>d__11`1.MoveNext()
>                        --- End of stack trace from previous location where exception was thrown ---
>                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>                            at 
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>                            at Box.V2.Managers.BoxResourceManager.<ExecuteRequest>d__10`1.MoveNext()
>                        --- End of stack trace from previous location where exception was thrown ---
>                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>                            at 
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>                            at Box.V2.Managers.BoxResourceManager.<ToResponseAsync>d__9`1.MoveNext()
>                        --- End of stack trace from previous location where exception was thrown ---
>                            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>                            at 
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>                            at Box.V2.Managers.BoxUsersManager.
> <GetCurrentUserInformationAsync>d__1.MoveNext()<---`
 

> It looks like an older version of NewtonSoft.Json is expected. This is most likely a bug, but we might be > able to work around by downgrading to version 9.0.0.0.

However, downgrading does not work either.  **Picture of attempt without version 9.0.0:**
![image](https://user-images.githubusercontent.com/11139575/34420124-c48e2578-ebd5-11e7-868f-dcf1eceb58b6.png)

**Picture of attempt without version 10:**
![image](https://user-images.githubusercontent.com/11139575/34420138-db3e05cc-ebd5-11e7-8567-b50f94b5ed9a.png)

However, I was able to get it to work by **importing both version 9.0.0 and version 10.0.0 of the Newtonsoft.Json assembly into the powershell session:**
![snipaste_2017-12-28_13-53-22](https://user-images.githubusercontent.com/11139575/34420248-89a83740-ebd6-11e7-9583-6b1d026e6dbf.png)

 The dotnet core sdk (which the windows sdk for box says is needed if running under dotnet core) has the required version of the assembly located in "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\newtonsoft.json\9.0.1\lib\net45\Newtonsoft.Json.dll". So I just copied that assembly into the folder with all of the other assemblies needed to use the sdk (put it in its own folder Newtonsoft.Json.9.0.0), and then run the following line in powershell to import all of the assemblies: 
Get-childitem "Path\to\folder\\*.dll" -recurse | % {[reflection.assembly]::LoadFrom($_.FullName)} 
However, the fact that 2 different versions of Newtonsoft.Json need to be imported into the same powershell session to make this semi-work (again, the role information is missing) is, in of itself, another major problem that needs to be fixed, as not only is this considered to be very bad practice and can lead to future problems, this also limits the IDE/ISE that I can use and limits the features which can be utilized within the IDE/ISE, as many products will not allow the importation of the same assembly a second time, even if it is a different version. Below is a link to a zip file in which I have included all of the assemblies that are needed in order to make the box windows sdk work in powershell. Please let me know if you need anything else from me, as I would like to see this resolved asap. Thank you. 
[assemblies](https://acuitybrandsinc-my.sharepoint.com/personal/wmh02_acuitysso_com/_layouts/15/guestaccess.aspx?docid=0cb11bbe19a8a46218052fc4893e5acb8&authkey=AVXl7AB3htiNe9hPdIXShxw&e=f8990967a7fb4b51affb7586606cf635)

**Comment by carycheng77** [comment]
Hey @whiggs, will take a look at this now, thanks!

**Comment by whiggs** [comment]
Thank you sir.  I appreciate it.  Also, in addition to the missing property values for objects returned by the windows sdk, could you please look into why the Newtonsoft.Json assembly (v. 9.0.0 and v. 10.0.0) needs to be imported more than once?  The fact an assembly with the same name needs to be imported into the same powershell session multiple times is very limiting.  I posted about this very issue on the powershell studio forums as well, and got the below response:
> I am not sure if that even can be done. In general, when you try to use two different versions of the 
> same assembly at the same time you are creating a huge problem for yourself. In any language.
> This is not an easy task even in C#, and practically not possible if both versions use the same 
> namespace (very likely) and/or use a different .NET runtime (also quite likely). I suspect that this is not 
> a PowerShell Studio limitation but simply something that the underlying .NET framework will not allow > you to do. I will inquire with the development team, but you should provide some information if these > two assembly versions use the same namespace and/or if there are different .NET runtime 
> requirements.
> Last but not least, I would also be curious why you even want to do that. The newer version of that 
> assembly *should* work for everything that the older version does or the vendor screwed something 
> up.
> So if you could provide some more information on this as well, it would be appreciated. Maybe we can > help you in some other fashion if we know more.
So if you could look into that as well, I would really appreciate it.

**Comment by whiggs** [comment]
So the first portion of the issue concerning missing property values for objects returned via the sdk was oversight on my part, so I have removed it from the original post.  Still, however, waiting to hear word about the remaining portion of the issue............

**Comment by whiggs** [comment]
The issue seems to be due to the System.Identitymodel.Tokens.JWT assembly (I think).  Interestingly, when I use the nuget commandline tool to install System.Identitymodel.Tokens.JWT into the project directory, it also installs Newtonsoft.Json 9.0.0 along with it, even though version 10 is already present....

**Comment by carycheng** [comment]
Hey @whiggs, 

We looked through that issue for a bit and seems like for both V2 and V2.core we are only requiring Newtonsoft.json 10.0. 
<img width="597" alt="screen shot 2018-01-08 at 3 04 54 pm" src="https://user-images.githubusercontent.com/6364733/34697684-0c3556b0-f489-11e7-816f-1b3955b3d883.png">
<img width="598" alt="screen shot 2018-01-08 at 3 05 16 pm" src="https://user-images.githubusercontent.com/6364733/34697687-0fb3a9ea-f489-11e7-98c2-f34fbe841672.png">


The issue does seem to be stemming from System.Identitymodel.Token.JWT where there is a dependency of Newtonsoft.json 9.01 or greater. 
<img width="541" alt="screen shot 2018-01-08 at 3 32 35 pm" src="https://user-images.githubusercontent.com/6364733/34697714-2e57338a-f489-11e7-9b1c-653f199a9179.png">

However, it should be keeping v10.0 because that dependency lists anything greater or equal to 9.0.1 is okay. It is a big difficult to debug but if you could use the Visual Studio built in Dependency Graph to see which package is exactly calling on Newtonsoft.json v9.0 what would be a great help. 

[Visual Studio Dependency Graph](https://msdn.microsoft.com/en-us/librAry/dd409453%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396)

Thank you and let us know if you run into more issues

**Comment by whiggs** [comment]
Ah.  I think I found the issue.  If you look in the first post, there is a picture labeled "Picture of attempt without version 9.0.0:" which shows that System.Identitymodels.tokens.jwt.jsonextensions is what threw the exception.  Upon analyzing the System.Identitymodels.tokens.jwt assembly, I took a closer look at the JsonExtensions type.  I then looked for any reference to the Newtonsoft.Json assembly in the code for the JsonExtensions type and found the below code:
` static JsonExtensions()
        {
            JsonExtensions._serializer = new Serializer(JsonConvert.SerializeObject);
            JsonExtensions._deserializer = new Deserializer(JsonConvert.DeserializeObject);
        }`
I then did a comparison of the Newtonsoft.Json 9.0.0 and Newtonsoft.Json10.0.0 assemblies to see if I could find why the JsonExtensions type was throwing an exception when Newtonsoft.json version 9.0.0 was not imported into the powershell session.  I found that the Deserializeobject and serializeobject methods seem to differ between the two assemblies in such a way that the later version of Newtonsoft.Json is not able to process the information which is being fed to it by System.Identitymodel.Tokens.JWT.  I have attached the decompiled code for the "JSONconvert" type from both the 9.0.0 and 10.0.0 versions of Newtonsoft.json, and using winmerge to compare the text from the two files, there seems to be a substantial difference between the two.  I hope this helps, and please let me know if you need me to do anything else.
[9.txt](https://github.com/box/box-windows-sdk-v2/files/1615762/9.txt)
[10.txt](https://github.com/box/box-windows-sdk-v2/files/1615763/10.txt)

**Comment by mattwiller** [comment]
@whiggs Thank you for investigating!  Let me check that I understand this issue correctly:

- The Box Java SDK package directly requires `Newtonsoft.Json` 10.x
- One of our other dependencies, `System.IdentityModel.Tokens.Jwt`, transitively depends on `Newtonsoft.Json` 9.x
- Despite specifying that it works with `Newtonsoft.Json` >= 9.0.1, `System.IdentityModel.Tokens.Jwt` actually breaks when `Newtonsoft.Json` 10.x is used.

Does that line up with your understanding?  If so, I'm unsure of how we should proceed here.  I'm not an expert on .NET dependency specification and resolution, but this seems like a difficult issue to me.  I'm open to any suggestions you might have.

**Comment by whiggs** [comment]
@mattwiller You are almost spot on.  Everything up to the last point is correct, and the last point itself is somewhat correct.  The box windows sdk does have a dependency on newtonsoft.json 10.x and the sdk will not work without it.  Also, as you have stated, despite the nuget package for System.IdentityModel.Tokens.Jwt specifying that it is dependent on a version of newtonsoft.json which is greater than or equal to version 9.x, System.IdentityModel.Tokens.Jwt itself seems to have inconveniently forgotten the "greater than or" portion of that dependency.  So, in order to get the the box sdk to properly work, I need to import **both versions** of the newtonsoft.json assembly into the active powershell session, which significantly limits how my script functions, as many IDEs and ISEs do not allow for the importation of the same assembly (regardless of version) more than once.  Attached to this post is the powershell code that I have which will automate the setup of the box sdk on a machine if it is not detected.  Then, if you have a json file containing the information of a registered app, you can plug that into the "$cli" variable, and the powershell script will generate an admin token and admin client for the powershell session.
[start-boxsdk.ps1.txt](https://github.com/box/box-windows-sdk-v2/files/1618998/start-boxsdk.ps1.txt)

**Comment by mattwiller** [comment]
Hmm, okay — in that case, it sounds like there isn't a lot for our team to do here.  You could follow up with `System.IdentityModel.Tokens.Jwt` about their broken dependency specification (or get them to fix their code so it works with the latest version of `Newtonsoft.Json`).  In the meantime, it sounds like you have a workaround available — I totally understand that it's ugly, but it's at least possible.  Is there anything you're looking for us to do on this at this time?

**Comment by whiggs** [comment]
Well, its funny you say that, because I just tested the newest release of the box windows sdk without Newtonsoft.Json.9.0.0 and it was able to generate the admin clients successfully (which it was not able to do in the previous version).  You can consider this issue resolved.  Thanks.

**Comment by whiggs** [comment]
@carycheng @mattwiller So the official decision is that it is a broken dependency issue on Microsoft's end?  The I would like to present the following scenario and see if that still holds true.  Below you will see a screenshot of the dependencies for the box.v2 assembly as displayed on nuget.org (which you are probably already very familiar with):
![image](https://user-images.githubusercontent.com/11139575/36944347-1f549526-1f68-11e8-8fc3-3cd54e058f12.png)
Notice how the System.IdentityModel.Tokens.Jwt dependency can be greater than or equal to 5.1.4.  If what you have previously claimed as a broken dependency specification and that assemblies, in general, should be able to use an assembly version greater than the version listed when the dependency specifies greater than or equal to said version, then, by that logic, I **should** be able to use the latest version of the System.IdentityModel.Tokens.Jwt assembly (in which the Newtonsoft.Json assembly dependency version has been updated to version 10, thus eliminating the need for the Newtonsoft.Json version 9.0.0 assembly altogether, which **was** the idea) instead of the version which nuget downloads when running the "nuget install box.v2" command.  However, this is not what happens when System.IdentityModel.Tokens.Jwt (and its dependencies) are replaced by with the most up to date version of the assembly (5.2.1):
![image](https://user-images.githubusercontent.com/11139575/36944478-3200f13a-1f6b-11e8-9b9f-0a777f5260db.png)

Care to comment and explain how exactly this is Microsoft's problem again?  The issue is currently being discussed on their end too, but the information you previously provided about assembly dependencies does not hold up, and it is starting to seem much more like Box's problem again, not Microsofts.....

**Comment by whiggs** [comment]
@carycheng @mattwiller So the official decision is that it is a broken dependency issue on Microsoft's end? The I would like to present the following scenario and see if that still holds true. Below you will see a screenshot of the dependencies for the box.v2 assembly as displayed on nuget.org (which you are probably already very familiar with):
https://user-images.githubusercontent.com/11139575/36944347-1f549526-1f68-11e8-8fc3-3cd54e058f12.png
Notice how the System.IdentityModel.Tokens.Jwt dependency can be greater than or equal to 5.1.4. If what you have previously claimed as a broken dependency specification and that assemblies, in general, should be able to use an assembly version greater than the version listed when the dependency specifies greater than or equal to said version, then, by that logic, I should be able to use the latest version of the System.IdentityModel.Tokens.Jwt assembly (in which the Newtonsoft.Json assembly dependency version has been updated to version 10, thus eliminating the need for the Newtonsoft.Json version 9.0.0 assembly altogether, which was the idea) instead of the version which nuget downloads when running the "nuget install box.v2" command. However, this is not what happens when System.IdentityModel.Tokens.Jwt (and its dependencies) are replaced by with the most up to date version of the assembly and its dependencies (5.2.1):

https://user-images.githubusercontent.com/11139575/36944478-3200f13a-1f6b-11e8-9b9f-0a777f5260db.png
Care to comment and explain how exactly this is Microsoft's problem again? The issue is currently being discussed on their end too, but the information you previously provided about assembly dependencies does not hold up, and it is starting to seem much more like Box's problem again, not Microsofts.....

**Comment by whiggs** [comment]
@carycheng @mattwiller So the official decision is that it is a broken dependency issue on Microsoft's end? The I would like to present the following scenario and see if that still holds true. Below you will see a screenshot of the dependencies for the box.v2 assembly as displayed on nuget.org (which you are probably already very familiar with):
![image](https://user-images.githubusercontent.com/11139575/37123740-4ce56902-2233-11e8-9a02-78f3bf37d083.png)

Notice how the System.IdentityModel.Tokens.Jwt dependency can be greater than or equal to 5.1.4. If what you have previously claimed as a broken dependency specification and that assemblies, in general, should be able to use an assembly version greater than the version listed when the dependency specifies greater than or equal to said version, then, by that logic, I should be able to use the latest version of the System.IdentityModel.Tokens.Jwt assembly (in which the Newtonsoft.Json assembly dependency version has been updated to version 10, thus eliminating the need for the Newtonsoft.Json version 9.0.0 assembly altogether, which was the idea) instead of the version which nuget downloads when running the "nuget install box.v2" command. However, this is not what happens when System.IdentityModel.Tokens.Jwt (and its dependencies) are replaced by with the most up to date version of the assembly and its dependencies (5.2.1):
![image](https://user-images.githubusercontent.com/11139575/37123753-53be8f24-2233-11e8-82ab-57c7eb49005d.png)


Care to comment and explain how exactly this is Microsoft's problem again? The issue is currently being discussed on their end too, but the information you previously provided about assembly dependencies does not hold up, and it is starting to seem much more like Box's problem again, not Microsofts.....

**Comment by mattwiller** [comment]
@whiggs I'm sorry we didn't get back to you you earlier — our team was busy researching possible solutions and working with our internal Windows SRE team to diagnose the issue.  Since you mentioned previously that you had a workaround, we didn't prioritize responding without concrete suggestions and instead focused on getting you the best possible answer.

It looks like this works in full .NET applications but not in PowerShell because the SDK's [app.config file](https://github.com/box/box-windows-sdk-v2/blob/master/Box.V2/app.config) that binds any version of Newtonsoft.Json to the 10.x version that the SDK installs is not being loaded by PowerShell.  Fundamentally, since you're going outside of the SDK's normal operation and loading the assemblies manually, you're going to have to ensure that the correct versions are installed and referenced.  In the course of our investigation we found some [information about how to make PowerShell load the app.config](https://stackoverflow.com/questions/17960/powershell-app-config), but weren't able to make it work in our environment.  You're more proficient in PowerShell than we are, so maybe you'll be able to get better results.

Since the error you're seeing is not in SDK code (the Microsoft library could not resolve the correct version of its dependency), and your assembly loading code is outside of what we support in the SDK, I'm going to close this ticket.  Best of luck in getting your script working, and feel free to let us know how you resolved this issue in the future.
