### ISSUE TITLE
As-User

### ISSUE THREAD

**Issue by jhoerr** [box/box-windows-sdk-v2#43]
I'd like to start working on support for `As-User`. However, it's not clear to me where the best entry point for this is. Here are some ideas I've had:

**1.**
IAuthRepository could be involved, but that would likely result in breaking changes. We could:
- Add `IAuthRepository.AsUserId`, which would be consumed by `BoxResourceManager.AddAuthorization` and added as a header to the request; **or**
- Move `BoxResourceManager.AddAuthorization` to `IAuthRepository.AddAuthorization`. `AuthRepository` would provide the same implementation as `BoxResourceManager` does now. A new subclass of `AuthRepository`, `AsUserAuthRepository`, could add the additional `As-User` header.

**2.**
Another option is to add an optional `asUser` string to every Box*Manager method signature. `BoxResourceManager.AddAuthorization` would be responsible for adding the appropriate header. This feels pretty clunky to me:

```
public async Task<bool> DeleteAsync(string id, string etag=null, string asUser=null)
```

**3.**
Finally, we might add the same optional `asUser` parameter on the `BoxClient` and `Box*Manager` constructors instead of the methods. This feels a little less clunky than option (2) and wouldn't result in the breaking change of (1).

Thoughts?

**Comment by sukku007** [comment]
any outcome on this thread/question?

**Comment by coolboy** [comment]
Hi @jhoerr @saguiitay @sukku007 

I know I am late for the reply, but here is the sample code which may fit your purpose https://github.com/box/box-windows-sdk-v2/blob/master/Box.V2.Samples.TransactionalAuth/Program.cs#L84

Closing this issue now, and feel free to reopen if you have any question
