### ISSUE TITLE
Uploaded file conversion status for .csv and .txt types.

### ISSUE THREAD

**Issue by PraveenKariyapperuma** [box/box-windows-sdk-v2#436]
I'm having issues with getting the conversion status of the .csv and .txt types through representations endpoint and it always returns the status 'none' when the file conversion/upload has completed already. However if you call the info URL of the same representation, returns the status as 'pending' and repeating info URL call again turns the status to 'success'. Simply i have to call the info URL twice to force the 
'success ' status.  Hope someone would look into this.

**Comment by mattwiller** [comment]
Hey @PraveenKariyapperuma — representations are generated on demand, so they may not be ready the first time you make the request.  You mentioned that the upload and Conversion were already completed; how do you know that the representation was completed?  I’m wondering if this is an issue with the status field being incorrect, or an issue with the representation not being generated yet.

**Comment by PraveenKariyapperuma** [comment]
Well @mattwiller, it's because i download thumbnails through the representations endpoint and it works all nice and fine for all other supported file types on the first call except for .csv and .txt types where i have to make two requests. If you can spend five minutes, here are the steps to reproduce what i'm talking about.

* Upload a small pdf, then call one of it's representations with fiddler/postman for instance jpg32x32. Hopefully you'll get the state as 'success' on the first call in the response if it's ready.

* Upload a small .txt or .csv file, call one of it's representations such as png1024x1024 (since .txt and .csv supported only png1024 and png2048) and you should see the status is 'none'. Status won't change how many times you try, not even after an hour. Now get the URL from the info property of the same representation and make a request (Authorization required), you'll get the status as 'pending'. Make the request again and the status becomes 'success'.

**Comment by carycheng** [comment]
Hey @PraveenKariyapperuma, that's not documented well on our part and we apologize! 

The reason behind this is that a lot of representations gets generated, in order to handle the influx of representation generation certain representation types for certain file types gets prioritized. Others however require two calls to kick off the process. 

Unfortunately txt files do not have specific representations prioritized for it, thus the first call is meant to return the representations available to generate on this txt file(even when you specify the x-rep-hint) but you still need to make a subsequent call in order to actually go start this creation process. This is similar anytime you see a status "none" when making a GET for an allowable representation.

One solution is to poll this download url for when a representation is available after you make a subsequent call to kick off the process to generate a representation.

We understand that this is not ideal and we are working internally to correct it, thank you!

**Comment by PraveenKariyapperuma** [comment]
Thanks for the elaboration @carycheng, hope you guys work on this.

**Comment by mattwiller** [comment]
@PraveenKariyapperuma We'll be implementing a higher level method to get a single representation in the next release.

**Comment by PraveenKariyapperuma** [comment]
Thank you @mattwiller

**Comment by PraveenKariyapperuma** [comment]
@mattwiller , i see the issue has been closed and fixed. could you please elaborate how it is done?  i mean is there a new end point to this?

**Comment by mattwiller** [comment]
@PraveenKariyapperuma There's a new method that was added in the linked pull request, which will go out in the next release of the SDK (should be tomorrow, March 26th).  You'll be able to do something like the following:

```c#
var repRequest = new BoxRepresentationRequest
{
    FileId = fileId,
    XRepHints = "[png?dimensions=1024x1024]"
};
Stream assetStream = await _client.FilesManager.GetRepresentationContentAsync(repRequest);
```

This method should do all the necessary polling to generate the representation, and will return a Stream over the contents of the representation.

**Comment by PraveenKariyapperuma** [comment]
i'll check this out. thanx.

**Comment by mattwiller** [comment]
@PraveenKariyapperuma We released v3.6.0 of the SDK, which includes the new method.  Give it a try and let us know how it works for you!

**Comment by PraveenKariyapperuma** [comment]
@mattwiller  This new endpoint serves all supported file types except for .txt and .csv. I get this message "Files of type 'txt' do not support this representation." plus is there a straight forward way to know the status of an uploaded file?

**Comment by mattwiller** [comment]
@PraveenKariyapperuma That would be an API limitation then — if the representation is not supported there's nothing we can do in the SDK to make it generate.

What do you mean when you say the "status" of an uploaded file?

**Comment by PraveenKariyapperuma** [comment]
Well thank you for reminding me of the assetPath and it works. In Crocodoc there was an option to get the status of a document. According box documentation a document could go through or end up in one of the following stages (states).

* none
* pending
* viewable
* error
* success

What i want to know is whether there's a way to get the status of a document just by passing the file id.

**Comment by mattwiller** [comment]
@PraveenKariyapperuma Those values are the statuses of individual representations — they're the same ones you can get via the `client.FilesManager.GetRepresentationsAsync()` method:

```c#
var representations = await _client.FilesManager.GetRepresentationsAsync(new BoxRepresentationRequest()
{
    FileId = fileId,
    XRepHints = "[png?dimensions=1024x1024]",
});
var status = representationsAllHeaders.Entries[0].Status.State;
```

**Comment by PraveenKariyapperuma** [comment]
@mattwiller How do i determine if a document is ready to be viewed once it has been uploaded? or is it ready right after the upload? or should depend on a representation status prior to viewing the document?

**Comment by mattwiller** [comment]
@PraveenKariyapperuma The representation status should tell you if that specific representation is ready to view.  If you use `GetRepresentationContentAsync()`, the SDK will handle polling until the representation is ready and then fetch it for you.

**Comment by PraveenKariyapperuma** [comment]
Thank you for the clarification @mattwiller .
