### ISSUE TITLE
UploadFileVersionUsingSessionAsync returns type BoxFileVersion

### ISSUE THREAD

**Issue by allenmichael** [box/box-windows-sdk-v2#437]
The helper method for using chunked upload returns type `Task<BoxFileVersion>` while all other upload methods (UploadAsync, UploadNewVersionAsync, and UploadUsingSessionAsync) return type `Task<BoxFile>`. I propose returning type `BoxFile` to remain consistent with the other upload methods in the SDK. The type `BoxFileVersion` is a nested object in the type `BoxFile` so you could still work with the `BoxFileVersion` object after returning a `BoxFile` from UploadFileVersionUsingSessionAsync method.

**Comment by mattwiller** [comment]
Hey @allenmichael — changing the return type would be a breaking change, so we would need to add a new method that resolves to the full BoxFile instead of a BoxFileVersion.  Any suggestions on how you would want the new method named to avoid confusion?

**Comment by allenmichael** [comment]
That's a good point @mattwiller. Maybe `UploadNewVersionUsingSessionAsync` to match the method for non-chunked upload `UploadNewVersionAsync`. You may want to mark the `UploadFileVersionUsingSessionAsync` method as deprecated as well and phase it out of the SDK eventually. Definitely not a critical fix, was just a little confusing when I was working with the method.

**Comment by carycheng** [comment]
#438, thank you!
