### ISSUE TITLE
Provide a change log or release notes when releasing a NuGet package

### ISSUE THREAD

**Issue by ckress** [box/box-windows-sdk-v2#439]
There is no document available describing the changes between NuGet package versions. What was fixed?
 Which features have been introduced? Updating blindly from, e.g., v3.2.0 to v3.4.1 is simply not an option, how should I justify the effort?

**Comment by mattwiller** [comment]
Hi @ckress — are you looking for something like a CHANGELOG.md in the GitHub repo?  The [NuGet page][nuget] for the SDK contains Release Notes that describe the major changes  is there something else you think would be valuable to add?

[nuget]: https://www.nuget.org/packages/Box.V2/3.4.1

**Comment by ckress** [comment]
Oh, I'm sorry, I missed the release notes section on the NuGet page. A more detailed CHANGELOG.md would be helpful, though.

**Comment by carycheng** [comment]
#441
