### ISSUE TITLE
Dependency on System.IdentityModel.Tokens.Jwt 5.1.4 breaks ASP.NET 4.x compatibility

### ISSUE THREAD

**Issue by Cpcrook** [box/box-windows-sdk-v2#443]
Box.V2 dependency in packages.config:

`<package id="Newtonsoft.Json" version="10.0.3" targetFramework="net45" />
  <package id="System.IdentityModel.Tokens.Jwt" version="5.1.4" targetFramework="net45" />`

Means that Box.V2 is not fully .NET 4.5 compatible.  This is likely due to Newtonsoft.Json's dependency on the updated identity model referenced above.

Per Usage section https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet

> IdentityModel Extensions for .NET 5 has now been released. If you are using IdentityModel Extensions with ASP.NET, the following combinations are supported:
>
>IdentityModel Extensions for .NET 4.x and ASP.NET 4
>IdentityModel Extensions for .NET 5.x and ASP.NET Core 1.x
>All other combinations aren't supported.

**Comment by carycheng** [comment]
Hey @Cpcrook, thank you for letting us know, we'll look into that now!

**Comment by carycheng** [comment]
Hey @Cpcrook, to get a little bit more context behind this issue - 

What version of ASP .NET are you currently working with and what are the conflicts or issues you are experiencing with when using the Windows SDK with ASP .Net?

If there are any error messages that would be very helpful, thanks!

**Comment by Cpcrook** [comment]
Sorry it took me a little to get back to you on this -- got back burnered for a while.

I've resolved this by upgrading all of my projects to compile against .NET 4.7 as the target framework, and updating all packages to latest.

I was compiling against .NET 4.5 previously.  My issue stemmed from the fact that Box .NET SDK relies on a Newtonsoft JSON 10.x, but the OWIN (3.1) & Identity (Microsoft.IdentityModel.Tokens / System.IdentityModel.Tokens.Jwt) earlier versions are dependent on Newtonsoft 6.x -- and to upgrade them 
 to their 4.0 (OWIN) and 5.x (Identity) requires upgrading my build target to 4.7 as NuGet packages for those don't exist for 4.5 build targets.  Hence my solution.

Perhaps it can be achieved with a bunch of dependentAssembly binding redirects, but it quickly becomes package/reference hell.
