### ISSUE TITLE
.Net SDK Doesn't Work with .Net Core 1.0, 1.1, or 2.0 Installed With Nuget in VS 2017

### ISSUE THREAD

**Issue by adamdaum** [box/box-windows-sdk-v2#446]
This may be several issues, but ...

I can't get the sdk to work with a .Net Core 2.0, 1.1, or 1.0 Web Application template, if it's installed using the Nuget package manager.

Using VS2017 Community, latest with all updates.  Don't have issues with any other projects.

1. Create new Web application project, .Net Core, MVC, ASP.NET Core 1.0 (or 1.1, or 2.0 have same result) 

2. Install Box.V2.Core using Nuget package manager (it appears to install properly).

3. Add using statement in Startup.cs, or any other class, "using Box.V2.Core;" 

Error, "Type or namespace 'Box' could not be found ..."

I was able to clone the solution from github, update the target framework to .NET Standard 1.6, recompile, (commented out a few items related to reflection), create a new nuget package, publish it to local nuget, install in .Net Core 1.1 Web app, and get it to work, when debugging from localhost, but I don't think I should have to do that.  And I still get exceptions when I use BoxJWTAuth or Oauth when running the app from IIS on one of our company intranet servers, and they're not super helpful messages.

**System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The connection with the server was terminated abnormally

AggregateException: One or more errors occurred. (An error occurred while sending the request.)
System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
System.Threading.Tasks.Task.GetResultCore(bool waitCompletionNotification)
Box.V2.JWTAuth.BoxJWTAuth.JWTAuthPost(string assertion)
Box.V2.JWTAuth.BoxJWTAuth.AdminToken()**

I was also able to clone the github repo, and run all the tests successfully, and sample projects, with no issues.

I was able to perform the auth handshake with oauth and jwt, both... using jQuery/ajax, and retrieve data, so I don't think it's firewall or network related.

**Comment by carycheng** [comment]
Thanks @adamdaum! We are looking into this now

**Comment by carycheng** [comment]
Hey @adamdaum, that was a huge mistake on my part. I unfortunately did not update the versions correctly so Nuget was unable to find its depedency. It has now been updated and seems to be working fine when I test it on my machine. Please give it a go and let me know if you run into any other issues! 

https://www.nuget.org/packages/Box.V2.Core/3.4.2

**Comment by carycheng** [comment]
Please reopen if the dependency is still causing an issue @adamdaum, thank you!

**Comment by adamdaum** [comment]
Thanks @carycheng , I installed the new nuget package in my .net core 1.1 web app, and the reference issue was fixed.  Same with .net core 2.0  I can connect using oath with jwt from localhost, and retrieve data, etc using the apis in the library.  So, that's fixed.  Thank you.

However, I'm still getting exceptions when running this from iis on our company Intranet, and I don't know it's related to the library or something else.  I have no issues performing these steps using jquery/ajax from the client side on iis...

--
WinHttpException: The connection with the server was terminated abnormally
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

HttpRequestException: An error occurred while sending the request.
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

AggregateException: One or more errors occurred. (An error occurred while sending the request.)
System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)

**Comment by carycheng** [comment]
Hey @adamdaum, would be great to get the calls you are making that you think may be causing these issues also if you could try running this in an environment outside of your company intranet that would be awesome! 

Trying to narrow down where the issue is coming from, thank you!

**Comment by adamdaum** [comment]
Hi @carycheng I will continue trying to think of other ways to test this outside out Intranet. The issue is happening at the same place as before though, when trying to obtain an admin token via Box.V2.JWTAuth.BoxJWTAuth.AdminToken() ... this works from my local, no issue.  I don't know if that's helpful.  Didn't find anything on the forum, but I might post there as well to see if anyone else has had any issues.

AggregateException: One or more errors occurred. (An error occurred while sending the request.)
System.Threading.Tasks.Task.ThrowIfExceptional(bool includeTaskCanceledExceptions)
System.Threading.Tasks.Task.GetResultCore(bool waitCompletionNotification)
Box.V2.JWTAuth.BoxJWTAuth.JWTAuthPost(string assertion)
Box.V2.JWTAuth.BoxJWTAuth.AdminToken()**

**Comment by mattwiller** [comment]
@adamdaum It sounds like this might be a problem with your firewall or some other network issue, if it works on your local machine but not on your intranet.  Is that correct?

**Comment by adamdaum** [comment]
@mattwiller  sorry, matt, i've been busy with other stuff.  

I don't think it's a firewall issue, because I'm able to perform the oauth2 handshake, etc with jquery/ajax and your REST api's directly.  

I mean, I'm kind of wondering if other people are even using this .Net Core sdk, or if it's been tested for typical use cases, because it sit out there on Nuget, and I was the first person to bring up that the Nuget package wasn't even usable.  

I haven't really had time to do additional testing.  I'm not exactly sure how else to test the sdk.  I'm thinking I could try and just create a console app and run it from that same server, which would eliminate one possible issue, and determine it has something to do with running it from IIS, which is what I suspect.  I'll keep you posted. 

But it would be nice to know that other people have had some success with this already.  And what use cases / libraries / frameworks they're using.

**Comment by mattwiller** [comment]
@adamdaum Have you had a chance to do any additional testing on this?  I'm still not entirely sure how best to narrow down the problem here, but any additional information would be helpful!

**Comment by mattwiller** [comment]
@adamdaum We just released v3.5.2 of the SDK, which fixes an issue that we identified with our build process — `dotnet pack` wasn't correctly packaging the library.  Could you try installing that version and let us know if you're still running into issues?
