### ISSUE TITLE
Allow for a custom IWebProxy to be set for new HttpClientHandler instances

### ISSUE THREAD

**Issue by nyxel** [box/box-windows-sdk-v2#448]
I would like to request support for a custom `IWebProxy` without having to reimplement `IRequestHandler`.

My suggestion is to add a `HttpRequestHandler.Proxy` property, initialize it to `new WebProxy()`, and use its value to set the `HttpClientHandler.Proxy` property in the `ClientFactory.CreateClient` method.

**Comment by carycheng** [comment]
Hey @nyxel, we can definitely look into this but would love to get some context behind this change to IWebProxy and the blockers you might be experiencing currently with IRequestHandler. Thanks!

**Comment by nyxel** [comment]
Hey @carycheng, a `HttpClient` is the heart of the `HttpRequestHandler` which in turn is that of the `BoxClient`. Applications may have local proxy settings, and there is currently no way to configure a `BoxClient` to use them. The only way is to replace `HttpRequestHandler` with a custom one, and this means the `HttpClient` caching feature is gone, too.

Admittedly, the `HttpClient` caching feature does make it difficult to add a HttpRequestHandler.Proxy property, one whose value can change over time, so it may not be the best place to go.
