### ISSUE TITLE
Trying to refresh access token .NET SDK

### ISSUE THREAD

**Issue by fredwilliams1981** [box/box-windows-sdk-v2#449]
I created a developer token through the dashboard which works fine with regular http calls. I'm trying to use the .ET SDK instead of making a bunch of http calls now, but when i try touse the BoxFoldersManager to retrieve folder tiems, I get an "oject is not set to an instance of an object error. NotE: I do't hve a refresh token at this point. I'm trying to using the developer token I created in the dashboard.

 

        public static BoxCollection<BoxItem> GetFolderItems(IConfiguration config,string id)
        {
            BoxService _boxService = new BoxService(new HttpRequestHandler());
            BoxJsonConverter converter = new BoxJsonConverter();
            AuthRepository repository = new AuthRepository(GetBoxConfig(config), _boxService, converter);
            //var session = repository.RefreshAccessTokenAsync(config["access_token"]).Result;
            BoxFoldersManager manager = new BoxFoldersManager(GetBoxConfig(config), _boxService, converter, repository);
            return manager.GetFolderItemsAsync(id, 100).Result;
        }
I do see that the session inside the authrepository is nul so maybe that's the issue? Again I'm able to do this through regular htprequests using the endpoints in the documentation but I'd lke to use the .NET SDK.

Thanks.

**Comment by carycheng** [comment]
Hey @fredwilliams1981, 

We have an example here of [getting started with an adminClient](https://github.com/box/box-windows-sdk-v2/blob/master/README.md#example-2). 

You can see from the first four lines how to instantiate a client. After you are done instantiating your client you can then make a callout to the 

```C#
FoldersManager.GetFolderItemsAsync("FOLDER_ID", "LIMIT OF ITEMS TO RETRIEVE");
```

seen [here](https://github.com/box/box-windows-sdk-v2/blob/master/README.md#get-folder-items) to retrieve your folder items. 

Let us know if you have any questions, thank you!

**Comment by fredwilliams1981** [comment]
Hello and thank for the swift reply,

I'm not using JWT to access the API. I just generate a developer token and use that as my access token. The idea is to have the users login and have their authentication code created and then passed to this application to crate access and refresh tokens to access to their box accounts. The problem is that while I'm testing I only have the developer token I create from within the app I created  at developer.box.com. 

Unless I'm missing something, it looks like I need a refresh token to create an OAuthSession to use the SDK.

This works fine when I use the REST API to make JavaScript calls and pass the developer token in the authorization header, but the .NET SDK is requiring me to have a refresh token. I don't have any refresh token, only the developer token.

**Comment by carycheng** [comment]
Hey @fredwilliams1981, 

You can also instantiate an OAuthSession without the refresh token by doing the [following](https://github.com/box/box-windows-sdk-v2/blob/master/README.md#authentication) 

Let me know if this helps, thanks!
