### ISSUE TITLE
BoxRepresentationStatus class deserialization issue still persists.

### ISSUE THREAD

**Issue by PraveenKariyapperuma** [box/box-windows-sdk-v2#451]
@carycheng , BoxRepresentationStatus class deserialization issue doesn't seem to be reflected to both 3.4.1 and 3.4.2 nuget packages. However it's working fine in the cloned SDK. Hope you guys will look into this.

**Comment by carycheng** [comment]
@PraveenKariyapperuma, thanks for letting us know! We'll take a look at this

**Comment by mattwiller** [comment]
@PraveenKariyapperuma We released v3.5.1 of the SDK today, which should include your fix for this issue.  Can you let us know if that works for you?

**Comment by PraveenKariyapperuma** [comment]
Working as expected, thanks for the heads up @mattwiller .
