### ISSUE TITLE
.Net SDK Doesn't Work (again) Installed With Nuget in VS 2017

### ISSUE THREAD

**Issue by PartyArk** [box/box-windows-sdk-v2#461]
Hi, 3.5.1 seems to have a reversion to the bug noted in #446 , which was I believe related to incorrect packages.

**Comment by mattwiller** [comment]
@PartyArk Thanks for letting us know, we're actively investigating this now

**Comment by mattwiller** [comment]
@PartyArk We just released v3.5.2 of the SDK, which should fix the issue.  We identified a problem with our build configuration that was causing the `dotnet pack` command to incorrectly package the library.  Could you try installing the new version and let us know if you see any issues?

**Comment by PartyArk** [comment]
Yes all good here, many thanks.

**Comment by mattwiller** [comment]
Great to hear — thanks for reporting the issue!
