### ISSUE TITLE
BoxApiUri is read only

### ISSUE THREAD

**Issue by cloughin** [box/box-windows-sdk-v2#471]
I posted this to Box support and Richie of Box User Services told me to post it here.

I'm attempting to follow instructions in the guide referenced in the "Upgrade to TLS 1.1 or Higher before June 15" email.

When I add the suggested C# code below, the second line give an error indicating BoxApiUri is read
only :

BoxConfig config = new BoxConfig(/* config parameters */);
config.BoxApiUri = "https://api-test.box.com/2.0/";

Specifically, "The property Box.V2.Config.BoxConfig.BoxApiUri has no setter."
I'm unable to proceed with the TLS testing.

I'm using Box.V2 version 3.6.0.

**Comment by carycheng** [comment]
Thanks for writing in @cloughin! 

We have a pr out for this now - #472

**Comment by cloughin** [comment]
Hi,

 

Haven’t seen anything further on this. Is this being actively pursued? We need to be able to validate that our site will work after the Box TLS upgrade.

 

Curt Loughin

**Comment by carycheng** [comment]
Hey @cloughin, 

Apologies for this! We just finished testing this and everything is good to go, we should be rolling this into our release Wednesday, thank you!

**Comment by carycheng** [comment]
Hey @cloughin, 

We just released v3.8.0 of the .Net SDK with the changes from #472. Let us know if everything is working for you and if you run into any issues, thank you!

**Comment by mattwiller** [comment]
@cloughin I'm glad everything is working for you now!  Thanks for letting us know about the documentation — it should be corrected now.

**Comment by cloughin** [comment]
Wow! You guys are quick. Thanks again.

**Comment by AGrant59** [comment]
Sorry to bump up an old thread, but is there a solution if you are not able to upgrade Box.com?  I'm using version 2.14 at the moment.

**Comment by mattwiller** [comment]
@AGrant59 Looking at the v2.x code from a couple years ago, the `BoxApiUri` property of `BoxConfig` is marked `virtual`, so you should theoretically be able to subclass `BoxConfig` yourself and override the property so it returns whatever you want.
