### ISSUE TITLE
Client initialization fails in Xamarin iOS and Android.

### ISSUE THREAD

**Issue by xal1983** [box/box-windows-sdk-v2#476]
Hi!
I've been using the client for a while and after upgrading to the latest version it crashes.
HttpClientHandler.SslProtocols property throws in those platforms with a NotImplementedException. The exception is actually raised by the property getter because of the |= assignment.

Here's the offending line:

https://github.com/box/box-windows-sdk-v2/blob/816c66770f9438a1faf1dcd71de0e4fcd04890e2/Box.V2/Request/HttpRequestHandler.cs#L189

Cheers,
Andrés

**Comment by mattwiller** [comment]
@xal1983 Thanks for the detailed bug report!  We introduced that line to ensure that clients work with the Box API once we deprecate TLSv1.0 in June — we'll add some additional safety checks to ensure it doesn't throw on platforms where it isn't implemented.
