### ISSUE TITLE
Undisposed responses make the client crash on mobile.

### ISSUE THREAD

**Issue by xal1983** [box/box-windows-sdk-v2#477]
### Description of the Issue
I have a mobile app (iOS & Android) and it needs to download the entire contents of a folder (and subfolders). In order to do so, it uses recursion to list out all of the subfolders' content using FoldersManager.GetFolderItemsAsync.
After a few folders are listed, the process hangs for a while and crashes.
On iOS, you can see this line in the debug output:
WARNING: An HttpWebRequest was added to the ConnectionGroup queue because the connection limit was reached.

Upon further investigation I could confirm that calling Dispose() on the response object fixes the issue.

I understand by reading the code that the reasoning for not disposing responses is so that streams can be read. I think a quick fix would be to manually call dispose if the request isn't for a stream.
A better solution would be to always return a disposable result object that includes the content/stream and disposes the response internally.

### Versions Used
.NET SDK: 3.7.0.  
.NET Framework/Core: netstandard 1.6. with xamarin ios and xamarin android.

### Steps to Reproduce
This example will reproduce the error:

`private async Task ListContents(string folderId)
        {
            var excludes = new List<string>();
            var fields = new List<string>() { "id", "name", "size", "modified_at", "sha1" };
            var client = GetClient();

            var items = await client.FoldersManager.GetFolderItemsAsync(folderId, 100, 0, fields);

            foreach (var o in items.Entries)
            {
                Debug.WriteLine($"\"{o.Name}\" ({o.Type}) id: {o.Id}");
                if (o.Type == EntryType.folder)
                {
                    await ListContents(o.Id);
                }
            }
        }`

Cheers,
Andrés

**Comment by mattwiller** [comment]
@xal1983 Thanks for the detailed issue!  We'll take a look internally and see what we'd like to do to dispose of the response.

**Comment by carycheng** [comment]
Hey @xal1983 , 

We just released a new version of the .NET SDK (v3.9.1) which we think might address your issue. Please try it out and let us know. 

Thank you! 

https://www.nuget.org/packages/Box.V2.Core/3.9.1
