### ISSUE TITLE
Session invalidated and I can never find the new access token

### ISSUE THREAD

**Issue by kninsa** [box/box-windows-sdk-v2#484]
- [X] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I am getting a session invalidated error and I don’t know how to fix it.  Here is the code:

var sessionInfo = new OAuthSession(_accessToken, _refreshToken, 3600, "bearer");
var boxConfig = new BoxConfig(clientId, clientSecret, new Uri(@"http://localhost:5000/BoxRedirectMethod"));
_client = new BoxClient(boxConfig);
_client.Auth.SessionAuthenticated += new EventHandler<SessionAuthenticatedEventArgs>(Auth_SessionAuthenticated); 
_client.Auth.SessionInvalidated += new EventHandler(Auth_SessionInvalidated);
_client = new BoxClient(boxConfig, sessionInfo);

Here is my behavior:
1.	I redirect the user to the box auth page so they can login and allow access
2.	I use the code from step 1 to authenticate and I save the access token and refresh token in the variables _accessToken and _refreshToken
3.	For the next 60 minutes the API works wonderfully, with no issues!
4.	AFTER 60 minutes, I call the above code with the _accessToken and _refreshToken variables I’ve been using the whole time
5.	This first 60+ call also works.  I assume the access token was refreshed, but in the _client.Auth.Session.AccessToken it is still the same (nothing has changed)
6.	Then, on the SECOND 60+ call that I make, I get an error that the session is invalidated
7.	I never get in either event handler (Auth_SessionAuthenticated or Auth_SessionInvalidated).  Neither one is ever called.

Can you please tell me what I’m doing wrong?  I really believe the code is working as designed and the access token is somehow automatically being refreshed, but I can never see what the new one is.  How can I GET the new access token?  What am I missing?

### Versions Used
.NET SDK: Box.V2.Core v3.8.0
.NET Framework/Core: .NET Core 

### Steps to Reproduce
See above

### Error Message, Including Stack Trace
Exception of type 'Box.V2.Exceptions.BoxSessionInvalidatedException' was thrown.
   at Box.V2.Auth.AuthRepository.<ExchangeRefreshToken>d__21.MoveNext()
   at Box.V2.Auth.AuthRepository.<RefreshAccessTokenAsync>d__18.MoveNext()
   at Box.V2.Managers.BoxResourceManager.<RetryExpiredTokenRequest>d__13`1.MoveNext()
   at Box.V2.Managers.BoxResourceManager.<ExecuteRequest>d__12`1.MoveNext()
   at Box.V2.Managers.BoxResourceManager.<ToResponseAsync>d__11`1.MoveNext()
   at Box.V2.Managers.BoxFilesManager.<UploadAsync>d__6.MoveNext()
   at Avii.DocumentManagement.DocumentProviders.BoxDocumentProvider.<CreateBoxFile>d__20.MoveNext() in C:\src\Avii\src\Avii.Application\DocumentManagement\DocumentProviders\BoxDocumentProvider.cs:line 146

**Comment by mattwiller** [comment]
@kninsa The client should be able to refresh the tokens automatically — you shouldn't need to do anything yourself with the access token and refresh token.  One thing to note is that once a refresh token is used to create a new active token pair (with a new access token and new refresh token), the original refresh token becomes invalid and you need to use the newly-generated refresh token the next time around.  If you just let the client handle refreshing on its own, does that solve the issue?

**Comment by kninsa** [comment]
Thanks for the quick response; I'll try that tomorrow and let you know.  As I stated in my original post, I was never able to see the SessionAuthenticated post fire, but maybe it was a permission or scope issue on my part.  I'll try it with an inline delegate -- as you suggested here -- and hopefully be able to catch the changed tokens.

**Comment by kninsa** [comment]
@mattwiller Using your inline delegate code, I still don't seem to be getting into that event.  Is it called on every successful authentication, or only when the tokens are refreshed?  And if I call 
`_client = new BoxClient(boxConfig, sessionInfo);`
right after assigning the delegate, does it renew the _client object and remove it?  Not sure why I'm not catching that event.

**Comment by kninsa** [comment]
Okay, that was the issue.  I was re-initializing the _client object after assigning event handlers.  Once I stopped doing that, your code snippet worked great.  Closing this issue and thank you so much for your help @mattwiller !
