### ISSUE TITLE
Unable to read tags for file and Folders it always comes as null

### ISSUE THREAD

**Issue by KiranSeersath** [box/box-windows-sdk-v2#488]
BoxFile file = await realClient.FilesManager.GetInformationAsync("XXXXXXXXXX");

file.Tags is always null. 

How to fetch tags for files and folders?

Thanks,
Kiran

**Comment by mattwiller** [comment]
@KiranSeersath The `tags` field of the file object is not returned by the API by default, and must be specifically requested with the `fields` parameter in [`GetInformationAsync()`](https://github.com/box/box-windows-sdk-v2/blob/master/docs/files.md#get-a-files-information):

```c#
string fileId = "xxxxxxx";
List<string> fields = new List<string> { "tags", "name", "size" };
BoxFile file = await realClient.FilesManager.GetInformationAsync(fileId, fields);
```
