### ISSUE TITLE
SessionAuthenticated not firing and Token expiring

### ISSUE THREAD

**Issue by hugohilario** [box/box-windows-sdk-v2#495]
### Description of the Issue
I have a access token and a refresh token that work during an hour approximately. After that I get a `BoxSessionInvalidatedException`. 

The ``Auth_SessionInvalidated``is fired immediatly before that happens, although ``Auth_SessionAuthenticated``is never fired.

### Versions Used
BOX .NET V2

### Steps to Reproduce

```
private void DoThings(string appKey, string appSecret, string  accessToken,string refreshToken)
{
	var config = new BoxConfig(appKey, appSecret, new Uri("http://localhost"));
	var session = new OAuthSession(accessToken, refreshToken, 3600, "bearer");

	var boxClient = new BoxClient(config, session);

	boxClient.Auth.SessionAuthenticated += Auth_SessionAuthenticated;
	boxClient.Auth.SessionInvalidated += Auth_SessionInvalidated;

	var root = client.FoldersManager.GetInformationAsync("0").Result;

	//Do things here
}

void Auth_SessionInvalidated(object sender, EventArgs e)
{
	//do nothing
}

void Auth_SessionAuthenticated(object sender, SessionAuthenticatedEventArgs e)
{
	// Updates the DB Store with the new token values e.Session.AccessToken, e.Session.RefreshToken
}
```

**Comment by carycheng** [comment]
Hey @hugohilario, 

Thanks for writing in! We'll investigate and let you know

**Comment by hugohilario** [comment]
@carycheng still no information after 26 days ? Thanks

**Comment by mattwiller** [comment]
@hugohilario Unfortunately, we've been unable to reproduce the error you're seeing so far -- in our testing using the code you pasted above, we observed that we could continue to make calls for at least 90 minutes, well past the token expiration time.  One thing to note is that in the code you pasted above, you have both `client` and `boxClient`; is that just an artifact of how you copied the code, or do you perhaps have two different clients in use?

In any case, we'll need some more information to continue debugging this issue.  If you don't mind, could you send me an email at the address in my GitHub profile with your client ID/API key (__NOT__ your client secret!) and a date/time when you saw this error occur (or just reproduce the error yourself now and use that time)?  That way we can take a look in our server logs to see if we can figure out what might be going wrong here.

**Comment by hugohilario** [comment]
Hi Matt. Yes please ignore that, it was a typo.

I just sent you the email with my clientId. Meanwhile I also replicated the error a few minutes ago.

Thanks

**Comment by hugohilario** [comment]
Hi Matt. I tried again and the refresh token I'm sending is the refresh token I got when I also got the Access Token. I got both tokens today at 8h50 UTC. And I got the error a few minutes ago.

I will send you the token and access token by email if that helps.
