### ISSUE TITLE
Uploading version does not rename file

### ISSUE THREAD

**Issue by LinneyS** [box/box-windows-sdk-v2#496]
- [x] I have checked that the [SDK documentation](https://github.com/box/box-windows-sdk-v2/blob/master/README.md) and [API documentation](https://developer.box.com/docs) doesn't solve my issue

### Description of the Issue
Uploading a new file version that has a different file type does not rename the file.

### Versions Used
SDK: 3.9.2 (https://www.nuget.org/packages/Box.V2/3.9.2)

### Steps to Reproduce
Run a request to upload a **DOC** file with a **DOCX** stream
[Upload File Version](https://developer.box.com/reference#upload-a-new-version-of-a-file-1)
`BoxFile file = client.FilesManager.UploadNewVersionAsync("new.docx", oldDocID, docxStream, fields: new List<string> { "name" }, setStreamPositionToZero: false).Result;`
File uploaded successfully as new version.
But the name and extension did not change

**Comment by mattwiller** [comment]
@LinneyS Thanks for reporting — this looks like a bug in the way the SDK sends the file name as part of the API request.  It includes the new name as the name of the file part in the multipart upload, but does not create an `attributes` part with the name, which is what the API uses to determine if the name should be updated.  We'll try to get a fix for this into the next SDK release later this week!
