### ISSUE TITLE
boxJWT.AdminToken - The API returned an error [BadRequest]

### ISSUE THREAD

**Issue by NeilMeredith** [box/box-windows-sdk-v2#499]
I am attempting to authenticate a JWT application by following the steps here (https://developer.box.com/docs/authenticate-with-jwt#section-step-2-generate-configuration), but am getting a "The API returned an error [BadRequest]" error message

### Versions Used 
.NET Framework/Core: 3.9.2

### Steps to Reproduce
I created a new JWT app with enterprise application access and generated a public/private keypair.  I then loaded that json file using the code from your documentation:

                IBoxConfig config = null;
                using (FileStream fs = new FileStream(@"C:\dev\key.json", FileMode.Open)) {
                    config = BoxConfig.CreateFromJsonFile(fs);
                }
                var boxJWT = new BoxJWTAuth(config);
                var adminToken = boxJWT.AdminToken();

I confirmed that the config object is populated (it has my enterprise id, public/private key, etc).  When the call to boxJWT.AdminToken() is made, I get the error message below:

### Error Message, Including Stack Trace
The API returned an error [BadRequest]

With the stack trace:

   at Box.V2.Extensions.BoxResponseExtensions.ParseResults[T](IBoxResponse`1 response, IBoxConverter converter)
   at Box.V2.JWTAuth.BoxJWTAuth.JWTAuthPost(String assertion)
   at Box.V2.JWTAuth.BoxJWTAuth.GetToken(String subType, String subId)

[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@NeilMeredith One thing you might want to do to get more information about the error is to catch and inspect the exception you're getting.  You should be able to check `ex.Error` and `ex.ResponseHeaders` for more information about the error response the API sent.  If those don't provide any useful context, one really common issue that people run into is that your application needs to be authorized by your enterprise administrator before you can authenticate.  If you haven't done that, you can contact your enterprise admin and send them the API key of your app to request that they authorize it.

**Comment by NeilMeredith** [comment]
The app was not authorized by the enterprise admin, it was right there in the `ex.Error` error message I just missed it.  Thank you for the help.
