### ISSUE TITLE
How to hide Printer and Download images in Preview Mode

### ISSUE THREAD

**Issue by mremigio** [box/box-windows-sdk-v2#500]
- [ ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
We are using Explorer via: https://cdn01.boxcdn.net/platform/elements/4.3.2/en-US/explorer.css.  In Preview, is there a way to hide Printer and the Download image since they don't work.

### Versions Used
.NET Framework 4.6

### Steps to Reproduce
Using Explorer, preview a document

### Error Message, Including Stack Trace
N/A

**Comment by mattwiller** [comment]
Hi @mremigio — it looks like your question might be more related to the Content Explorer UI Element than the .NET SDK; I would recommend asking over at https://github.com/box/box-ui-elements
