### ISSUE TITLE
A strongly-named assembly is required.

### ISSUE THREAD

**Issue by chessar** [box/box-windows-sdk-v2#501]
Could not load file or assembly 'Box.V2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

Box.V2 version 3.9.2

**Comment by mattwiller** [comment]
@chessar It looks like our build and release process somehow stopped signing the assembly.  We just released v3.9.3 of the SDK, which should be correctly strong-named.  Please give it a try and let us know if that fixes your issue!

**Comment by chessar** [comment]
Version 3.9.3 is working! Thanks.

**Comment by mattwiller** [comment]
Glad to hear it!
