### ISSUE TITLE
JTW authentication and file upload

### ISSUE THREAD

**Issue by vance222** [box/box-windows-sdk-v2#502]
- [ x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Hi,
I am attempting to make a program using the .NET SDK that will automatically login and upload a file when run.  I am having trouble understanding how to get JWT with OAuth working.  I've used the dev token successfully to test my code, but can't seem to figure out the proper way to use the client created with AdminClient and the JSON Config file.  Should I be making an As-User to be able to call Filesmanager.uploadasync()? Below is my code. I get the same error when using a service account client and an App User.
 

 
Any help is appreciated, thanks!

### Versions Used
.NET SDK: 3.9.3

### Steps to Reproduce

            IBoxConfig configJWT = null;
            using (FileStream fs = new FileStream(@"MyPath", FileMode.Open))
            {
                configJWT = BoxConfig.CreateFromJsonFile(fs);
          
              }
            var boxJWT = new BoxJWTAuth(configJWT);
            Console.WriteLine("created boxJWT");
            var adminToken = boxJWT.AdminToken();
            BoxClient clientJWT = boxJWT.AdminClient(adminToken);
        
            
            var userRequest = new BoxUserRequest() { Name = "test appuser", IsPlatformAccessOnly = true };
            var appUser = await clientJWT.UsersManager.CreateEnterpriseUserAsync(userRequest);

            var userToken = boxJWT.UserToken(appUser.Id); //valid for 60 minutes so should be cached and re-used
            var userClient = boxJWT.UserClient(userToken, appUser.Id);
            BoxFile newFile;

             string path = <mypath>";
     
           
              using (FileStream stream = new FileStream(path, FileMode.Open))
                    {
                                   BoxFileRequest req = new BoxFileRequest()
                    {

                        Name = "test.pdf",
                        Parent = new BoxRequestEntity() { Id = "myID" }
                    };
                Console.ReadKey();
                try
                {
                newFile = await userClient.FilesManager.UploadAsync(req, stream);

                }
                catch(BoxException bex)
                {
                    Console.WriteLine("exception when uploading: " + bex.ToString());
         
                    Console.ReadKey();
                }

### Error Message, Including Stack Trace
Here is the error I am receiving: 
exception when uploading: Box.V2.Exceptions.BoxException: The API returned an error [NotFound | 1xzugdfv55z9c2d5] not_found - Not Found

   at Box.V2.Extensions.BoxResponseExtensions.ParseResults[T](IBoxResponse`1 response, IBoxConverter converter)

   at Box.V2.Managers.BoxResourceManager.ToResponseAsync[T](IBoxRequest request, Boolean queueRequest)

   at Box.V2.Managers.BoxFilesManager.UploadAsync(BoxFileRequest fileRequest, Stream stream, IEnumerable`1 fields, Nullable`1 timeout, Byte[] contentMD5, Boolean setStreamPositionToZero, Uri uploadUri)

[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by vance222** [comment]
@mattwiller Ok. The folder was created with the box developer account we are using. My goal is to upload files to that same account.  If the app user does not have any folders in it, is there a way to upload to a different account, or should I be going about this differently?
Thanks

**Comment by mattwiller** [comment]
@vance222 The documentation on Service Accounts has some good detailed information about this issue: https://developer.box.com/v2.0/docs/service-account

I would recommend reading that over first, and then please let us know if you have any specific questions.

**Comment by nguyenHGP** [comment]
Vance222. I know this is article is from 2 years ago but I'm running into the same issue. Did you ever resolve this? Any information would be appericated.

thanks
