### ISSUE TITLE
Cannot reinitialize BoxClient object after reconnecting to the internet

### ISSUE THREAD

**Issue by khuongdo** [box/box-windows-sdk-v2#509]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I'm developing a Box client application for my corporation. Own corporation has our own SSO service which integrated with Box service. Therefore, I used JWT authentication method to create session with User client. I got stuck on a problem as described below.
Test 1: After internet connection is lost, I tried to make an API call for example get user information. Of course, the sdk returned HttpRequestException/SocketException, I handled that exception by displaying a error message to user. Then, I reconnected the internet, used the same session to make another API call -> It didn't work at all. 
Test 2: Well then, I reproduced the issue, but this time after reconnecting to the internet, I tried to re-initialize BoxClient object (init BoxConfig from Json config file -> init BoxJWTAuth object -> init BoxClient object - exactly the same way when the application starts) but it still thrown HttpRequestException means somehow the BoxClient object wasn't initialized at all.
Test 3: I start the app (with BoxClient session was successfully initialized), disconnect and reconnect to the internet -> Make an API call -> It's worked -> try to repeat the same actions (disconnect -> reconnect) on the same BoxClient session -> It's still work.
My question is how can I refresh the Jwt login session after losing connection to the Internet? Do I misunderstand anything? 

Thanks,
### Versions Used
.NET SDK: 3.9.2
.NET Framework: 4.7

### Steps to Reproduce
1. Initialize BoxJWTAuth using json config file
2. Initialize BoxClient by BoxJWTAuth.UserClient() method
3. Disconnect from the internet.
4. try to make an API call (the exception will be thrown)
5. Reconnect.
6. Repeat step 1 and 2.
6. try to make an API call again.

### Error Message, Including Stack Trace
HttpRequestException
WebException
SocketException
with message "remote name could not be resolved api.box.com"

[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@khuongdo This doesn't seem to be an SDK issue, given that the exception in question originates during DNS resolution, in the .NET networking internals.  I don't think there's much we can do within the SDK to make this work if the network disconnect has affected DNS resolution.

**Comment by khuongdo** [comment]
Hello @mattwiller ,
Thanks for your response.
I will take a look at DNS.
