### ISSUE TITLE
Can't access enterprise events with enterprise JWT token

### ISSUE THREAD

**Issue by danchoi** [box/box-windows-sdk-v2#511]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Using the `boxr` Ruby SDK, I can get an enterprise auth token and make client request to get users, get files, download files etc. But requests for enterprise events fails with an `insufficient_scope` error.

### Versions Used
`boxr` Ruby SDK, version 1.4.0

### Steps to Reproduce

```
# call Boxr::get_enterprise_token( ) with JWT credentials and successfully get access token
$client = Boxr::Client.new(ACCESS_TOKEN, as_user: BOX_USER_ID)
$client.enterprise_events(stream_position: next_stream_position, event_type: 'UPLOAD')
# error happens
```

### Error Message, Including Stack Trace
```
Traceback (most recent call last):
        6: from /app/bin/get_events.rb:31:in `<main>'
        5: from /var/lib/gems/2.5.0/gems/boxr-1.4.0/lib/boxr/events.rb:13:in `enterprise_events'
        4: from /var/lib/gems/2.5.0/gems/boxr-1.4.0/lib/boxr/events.rb:13:in `loop'
        3: from /var/lib/gems/2.5.0/gems/boxr-1.4.0/lib/boxr/events.rb:14:in `block in enterprise_events'
        2: from /var/lib/gems/2.5.0/gems/boxr-1.4.0/lib/boxr/events.rb:44:in `get_enterprise_events'
        1: from /var/lib/gems/2.5.0/gems/boxr-1.4.0/lib/boxr/client.rb:104:in `get'
/var/lib/gems/2.5.0/gems/boxr-1.4.0/lib/boxr/client.rb:239:in `check_response_status': 403: Bearer realm="Service", error="insufficient_scope", error_description="The request requires higher privileges than provided by the access token." (Boxr::BoxrError)
```
[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by briankwilliams** [comment]
It is worth noting that our account is a Co-Admin and has every single permission.

In other words, every one of these permissions is granted for the account:

![image](https://user-images.githubusercontent.com/14282589/48215272-e513c600-e34f-11e8-9e89-73424281b665.png)

**Comment by mattwiller** [comment]
In this case, `insufficient_scope` refers not to the permissions of the user, but to the actions the app is allowed to take on behalf of the user, which are defined via scopes in the Developer Console for the application.

**Comment by briankwilliams** [comment]
Thanks a ton for the feedback @mattwiller .

Would having the Box Administrator re-authorize the account help?  If not, is there a different approach we should take?  Apologies for all of the questions - we are a vendor completing an integration on behalf of an Enterprise Box customer.  Our access to the Developer and Administrator console is restricted.

**Comment by mattwiller** [comment]
If you've changed the scopes the app has enabled, you will need the Box Administrator to reauthorize the app before those changes take effect.
