### ISSUE TITLE
XML documentation missing in nuget packages

### ISSUE THREAD

**Issue by khenzar** [box/box-windows-sdk-v2#514]
### Description of the Issue
The nice XML documentation which is written via `<summary>` tag in code comments is not visible in Visual Studio after installing Box.V2 nuget packages.
The problem exists in both the .NET Core and the full .NET Framework nuget packages.

### Versions Used
.NET SDK: Box.V2.Core 3.10.0, Box.V2 3.10.0
.NET Core: 2.1, .NET Framework: 4.6.1
Visual Studio: 2017 (15.9.4), 2019 (16.0.0 Preview 1.1)

### Steps to Reproduce
1. In Visual Studio create new .NET Command Line App or .Net Standard library or any other project.
2. Install Box.V2.Core nuget package for the project.
3. Start referencing any of the Box.V2 namespaces in your code.
4. Hover your mouse over any Box SDK method and observe the description.
5. A documentation text should be shown in the Intelli-sense, but it's not.

EXAMPLE:
Source code with documentation: [BoxCollaborationsManager.cs:30](https://github.com/box/box-windows-sdk-v2/blob/a7ed424c9b00e6da07e7aa30b1a28e33420aead3/Box.V2/Managers/BoxCollaborationsManager.cs#L30)
Result (documentation missing):
![MethodDscScreenshot](https://user-images.githubusercontent.com/2130285/50143732-ac033580-02ad-11e9-92b6-42477d3f0ffd.png)

### SOLUTION
`GenerateDocumentationFile `property needs to be enabled in the CSProj files.
```
<PropertyGroup>
  <GenerateDocumentationFile>true</GenerateDocumentationFile>
</PropertyGroup>
````

**Comment by mattwiller** [comment]
@khenzar Thanks for letting us know!  We have a PR open to address this issue over at #515 — we'll make sure that gets into the next release of the SDK.
