### ISSUE TITLE
"GetCollaborationsAsync" method of the "BoxFilesManager" class does not return number of collaborations

### ISSUE THREAD

**Issue by whiggs** [box/box-windows-sdk-v2#524]
### Description of the Issue
So I have found that using the "GetCollaborationsAsync" method of the "BoxFilesManager" class does not return the correct number of collaborations for a file, even though it does list the collaboration entries.  I am creating a powershell module for box which utilizes the box windows sdk and found this while testing my module's functions. Consider the below code:

```powershell
function get-boxfolderitems
{
<#
This function returns the "result" property of the variable which stores the result of using "GetFolderItemsAsync" method in "BoxFoldersManager" class
#>
	[CmdletBinding(DefaultParameterSetName = "auto")]
	param (
		[string]$folderid = "0",
		[Parameter(ParameterSetName = 'noauto')]
		[int]$offset = 0,
		[Parameter(ParameterSetName = 'noauto')]
		[int]$limit = 1000,
		[Parameter(ParameterSetName = 'auto')]
		[Switch]$autopage,
		[System.String[]]$fields
	)
	If ($PSCmdlet.ParameterSetName -like "auto")
	{
		$foldlist = $adminclient.FoldersManager.GetFolderItemsAsync($folderid, 1000, 0, $PSBoundParameters.fields, $true)
	}
	Else
	{
		$foldlist = $adminclient.FoldersManager.GetFolderItemsAsync($folderid, $limit, $offset, $PSBoundParameters.fields, $false)
	}
	$foldlist.Wait()
	If ($foldlist.IsFaulted -eq $true)
	{
		Write-error $foldlist.Exception.InnerException
		return
	}
	Else
	{
		return $foldlist.Result
	}
}

$tt = get-boxfolderitems -autopage
# Takes the box folder items, filters out everything but the files, and passes that to the "GetCollaborationsAsync" method of the "BoxFilesManager" class

$tt.Entries | Where-object {$_.Type -like "file"} | % {($adminclient.FilesManager.GetCollaborationsAsync($_.id)).Result}

```

You should also assume that there is a file in "$tt.entries" that has a collaboration.  In any event here is the result that we see when running the above code:

![image](https://user-images.githubusercontent.com/11139575/51429657-96e83200-1bde-11e9-82bc-795a454d4164.png)

As you can see, even though a collaboration is detected and listed in the "entries" property, total count remains 0 for some reason, when it should be 1.

### Versions Used
.NET SDK: 3.11.0

### Steps to Reproduce
Please see above.  I was pretty clear about how to reproduce the issue at the very beginning and would rather not repeat myself.

### Error Message, Including Stack Trace
No error message, just incorrect return value.

[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by whiggs** [comment]
Also, I didn't feel this warranted the creation of a new issue, but the source code for the "GetRepresentationContentAsync" of the "boxfilesmanager" class does not have any explanation for the parameter "assetPath."  Might want to add some info about it.

**Comment by mattwiller** [comment]
@whiggs It looks like there's a couple things going on here:
* The data returned by the API does not include the `total_count` field at all — it uses [marker-based paging][marker] and returns a `next_marker` instead.
* The type returned by the SDK for this method (a `BoxCollection` is incorrect — it should be one of the types that expose `.NextMarker`), but changing it in place is a breaking change.

We'll need to discuss how we want to move forward with fixing this in the SDK, but for the moment the best answer to your question is that the total count is not available directly via the API.  The "correct" way to get it would just be to page through the collection and count them as you go, but we'll need to fix the return type first so that the paging marker is available to your code.

[marker]: https://developer.box.com/v2.0/reference/#section-marker-based-paging

**Comment by whiggs** [comment]
@mattwiller Oh think I understand what you are saying.  So let me ask, why is it that the wrong paging method is used?  Does it relate to second part of the explanation, about how the method returns an object that is not necessarily the best choice for returning the data generated by the method?  If that is the case, isn't it only one problem really: the method just returns an object that is not really suited for the the method?

**Comment by mattwiller** [comment]
@whiggs The core problem in the SDK is that the method returns the wrong type, but the other point that's probably relevant for your use case is that even when the type is fixed, you will not have access to a total count on it.  That data is simply not sent back by the API.  Fixing the return type will only remove the `.TotalCount` property so it's not confusing, and provide access to the `.NextMarker` property so it's possible to page through the collection.

**Comment by whiggs** [comment]
Ah I see what you are saying.  That second problem will not be an issue in my case.  It is all good.
