### ISSUE TITLE
Any plan to support the new Get User Avatar endpoint?

### ISSUE THREAD

**Issue by rchan85** [box/box-windows-sdk-v2#525]
According to https://developer.box.com/docs/api-changelog-2017 avatar_url only returns a static image now.

Is there any plan to support the new Get User Avatar on .NET's SDK?

Thanks.

Kind regards,
Raymond

**Comment by mattwiller** [comment]
@rchan85 This is definitely something the SDK should support — I opened a PR to add this functionality (#527)
