### ISSUE TITLE
Any plan to support weblink copy and shared link?

### ISSUE THREAD

**Issue by rchan85** [box/box-windows-sdk-v2#526]
As title mentioned, 

The Web-links.md page mentioned that Weblink also support shared links, copy just like file object but I wasn't able to find the corresponding methods from BoxWebLinksManager.cs
https://github.com/box/box-windows-sdk-v2/blob/5800ee9aa621493d6d23d8628b2bf5b20057309a/docs/web-links.md

Is there other way to do the following? Or it would be something for the future?
- Copy a Weblink
- Shared a Weblink 

Thanks.

Kind regards,
Raymond

**Comment by mattwiller** [comment]
@rchan85 These should definitely be a part of the SDK — I have a PR open to add these methods (#528)
