### ISSUE TITLE
BoxGroupEventSource Issue?

### ISSUE THREAD

**Issue by whiskeyjimg** [box/box-windows-sdk-v2#535]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue

I believe I found a bug in BoxGroupEventSource. The Id field is not declared with override to override the Id field in BoxEntity. This is inconsistent with how BoxFolderEventSource and BoxFileEventSource declarations which which both override the Id field. This is showing up when we process events and causing null exceptions at times. Some events have the BoxEntity Id field set while other events have the Id field from BoxGroupEventSource set. You can access both fields based on how the object is cast. Can you verify if this is a bug or "feature". I'm thinking bug.

### Versions Used
.NET SDK: 2.3.12 

### Steps to Reproduce
Since this is a design question the only steps are to look at the above mentioned source code.

### Error Message, Including Stack Trace
Id is sometimes blank if you don't cast the object to the appropriate type.

[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@whiskeyjimg That looks like a bug to me too — I have a PR (#536) that should fix this issue.  We'll hopefully push it out with the next release of the SDK later this week!
