### ISSUE TITLE
Really, really confused.

### ISSUE THREAD

**Issue by whiggs** [box/box-windows-sdk-v2#540]
### Description of the Issue
I honestly don't know what is going on with this latest release of the box windows sdk.  I figured I would download it, incorporate it into the Poshbox powershell I had created to act as a wrapper around it, but instead I run into some odd behavior.  Lets start with actually downloading the nuget package using the nuget command line tool.  From what I can see when analyzing the assembly, the dependencies have remained mostly unchanged (list on the left), yet look at the list of assemblies that downloads when I install the package from the command line (on the right):
![image](https://user-images.githubusercontent.com/11139575/53830323-2dcf3a80-3f50-11e9-85b9-8f5e35eda05b.png)

At one point, trying to get this mess to work, I had 4 different versions of the newtonsoft.json assembly imported into a single powershell session simultaneously:
![image](https://user-images.githubusercontent.com/11139575/53830565-bd74e900-3f50-11e9-8f56-c200538fb7bc.png)

This strange behavior seems to only affect the latest release, as downloading version 3.13.1 results in the packages I would expect to see:
![image](https://user-images.githubusercontent.com/11139575/53830746-2197ad00-3f51-11e9-8649-af1a2cc1830b.png)

And I ran into all of these issues just trying to download and use the sdk.  I could write a trilogy on the problems I ran into actually trying to use it, but I think the issue has been adequately reported.

### Versions Used
.NET SDK: // 3.14.0
.NET Framework/Core: // Replace with the version of .NET or .NET Core your application is running on.

### Steps to Reproduce
1. Download nuget command line tool
2. run "nuget install box.v2"

### Error Message, Including Stack Trace
Here is one issue I ran into when actually trying to use the sdk.  In this one command, I am pulling the authentication info from the json containing the info, storing it in the registry, then pulling that info from the registry and using it to create a client config object.  Take a look at what happens:
![image](https://user-images.githubusercontent.com/11139575/53831157-21e47800-3f52-11e9-92c9-641fa8d2f21b.png)

But, as you can see in a previous picture, nj version 11 is indeed one of the 4 different versions of the assembly that is imported into the wrapper module when it is imported.

Maybe I just don't understand something...  Is there something I am not understanding, or is the box windows sdk as screwed up as I think it is at the moment?

**Comment by carycheng** [comment]
Hey @whiggs,

This issue falls on me, I am really sorry for all the inconvenience this has caused. I have removed the offending configs that is confusing the Windows SDK and will be pushing out a release later today/tomorrow.

Thank you for biding with me and in the meantime I would use one previous version as I work on releasing the updated/fixed package.

Thank you!

**Comment by whiggs** [comment]
@carycheng All good.  Everyone makes mistakes.  I get that.  Thank you for resolving it so quickly.

**Comment by carycheng** [comment]
Hey @whiggs, we just pushed out a new version of the windows sdk today(v3.14.1). Please try it out and let us know if there are any issues.
