### ISSUE TITLE
BoxUserFolderCollaborationEventSource

### ISSUE THREAD

**Issue by whiskeyjimg** [box/box-windows-sdk-v2#542]
### Description of the Issue

BoxUserFolderCollaborationEventSource issue?

When I get a list of collaborations there is unique ID associated with the collaboration.   There is no similar ID with BoxUserFolderCollaborationEventSource, just file ID.   What is the purpose of the BoxUserFolderCollaborationEventSource event.   It has no collaboration ID so I cant tie it back to an existing collaboration.   I can update information on the Folder that the collaboration is for but that is about it.    Is that collaboration ID field missing or am I misunderstanding the purpose of this event?

### Versions Used
.NET SDK: 2.3.14.

### Steps to Reproduce
take a look at BoxUserFolderCollaborationEventSource

**Comment by mattwiller** [comment]
@whiskeyjimg This information is not available as a top-level property of the event object, but for this event type the ID of the collaboration can be found in the `.AdditionalDetails` dictionary, under the `collab_id` key.

**Comment by whiskeyjimg** [comment]
Can you point me at documentation on what can be found in AdditionalDetails for all event types?

**Comment by mattwiller** [comment]
@whiskeyjimg Unfortunately, I don't know of any such documentation — it is highly specific to each event type.

**Comment by whiskeyjimg** [comment]
Thank you
