### ISSUE TITLE
User search with special character in the email

### ISSUE THREAD

**Issue by jtrujillo3** [box/box-windows-sdk-v2#543]
- [X] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
We are using GetEnterpriseUsersAsync(..) (.net SDK) to search for a given user to see if the user exists in our instance. This call takes many arguments but we only pass the “filterTerm” and “fields”.

Some of the email addresses have special characters in them.  With the “filterTerm” parameter, we are seeing that if we pass an email address with a “+” in it , it is not matching anything and does not return  a result.  If you replace + with %2B it returns the correct result match.  I have tested this in the Java SDK and CLI v2 and the search call performs differently than .NET.  The "+" does not need to be translated in those cases and it searches as expected.  

### Versions Used
.NET SDK: 3.4.2 

### Steps to Reproduce
client.UsersManager.GetEnterpriseUsersAsync(filterTerm: “jtrujillo+test@box.com”, fields:null)

**Comment by mattwiller** [comment]
@jtrujillo3 Thanks for letting us know!  It looks like the SDK isn't escaping things correctly for query parameters.  I think we can fix this relatively easily, but just note that if you're manually escaping things today then when the fix lands it will double-escape and potentially cause an error.

**Comment by mattwiller** [comment]
@jtrujillo3 This fix was just released in v3.16.0 of the SDK; please give it a try and let us know if you run into any more issues!
