### ISSUE TITLE
Get Thumbnail - jpg endpoint

### ISSUE THREAD

**Issue by guilmori** [box/box-windows-sdk-v2#547]
How can I use the .jpg endpoint using the GetThumbnailAsync() method ?

Ref: https://box-content.readme.io/reference#get-a-thumbnail-for-a-file

**Comment by guilmori** [comment]
The issue I have with .png endpoint is it squares and crop the image.
I've been told by support to use the .jpg endpoint, as it will keep the aspect ratio of the image.

**Comment by mattwiller** [comment]
@guilmori That is not currently possible — the method will need to be updated to allow selecting either `png` or `jpg`.  We'll add a task to update this method to our backlog and update this issue when the change is complete!  If you're so inclined, you're also more than welcome to submit a pull request in the meantime.

**Comment by guilmori** [comment]
@mattwiller I just submitted a pull request. Please give me an idea when this can be merged, i need it ASAP :-) 
Thanks!

**Comment by mattwiller** [comment]
@guilmori Thanks for the PR!  I merged the new code in, and we'll push out a release with your changes next week.

**Comment by mattwiller** [comment]
@guilmori Sorry for the delay!  This change was just released in v3.16.0 of the SDK.  Please try out the new version and let us know if you run into any more issues.
