### ISSUE TITLE
JWT authentication model - Safe to use BoxClient as a singleton ?

### ISSUE THREAD

**Issue by guilmori** [box/box-windows-sdk-v2#548]
Can a BoxClient be used as a singleton in a web app, where multiple requests may trigger the refresh of Access Token at the same time?

**Comment by mattwiller** [comment]
@guilmori Yes, this should be fine, especially using JWT authentication.  Generating a new access token with JWT authentication does not invalidate previously-generated tokens, so it should not cause any errors if you use a single client this way.  However, if you do run into any issues, please let us know!

**Comment by guilmori** [comment]
Did some multi-threaded tests and all works good!

**Comment by mattwiller** [comment]
Great — glad to hear that!
