### ISSUE TITLE
How can I download User Activities using Box API with c#

### ISSUE THREAD

**Issue by dhawkKD** [box/box-windows-sdk-v2#549]
I am looking for a way to get User activities using Box API similar to user activities report/alert generated in box.
Do we have any way for this?

**Comment by mattwiller** [comment]
@dhawkKD Have you tried using `client.EventsManager. EnterpriseEventsAsync()`?  That method should allow you to access the events for your enterprise.  Unfortunately, this API does not offer filtering by user, but you should be able to read through the set of available events and find only the ones you care about by inspecting each event.
