### ISSUE TITLE
Token is not automatically refreshing 

### ISSUE THREAD

**Issue by whiskeyjimg** [box/box-windows-sdk-v2#558]
We have a C# application that is using the BOX SDK 3.14 to do a number of calls to box.   Our program is getting a list of all files and looping through them making the following call for each file.    

var collaborations = AwaitReturn(() => _client.FoldersManager.GetCollaborationsAsync(id, 
fields))

The following  logon works and is good until the authorization token expires.   The event for refreshing the auth token is not firing, so further calls to the API get an authorization failure.   

For authorization we do the following.  

1.   We use an user name/ password and authcode to retrieve valid auth and refresh tokens.   
2.   The tokens are written to a file.
3.   We connect to box with the following code (using the saved tokens)

OAuthSession session = OAuthSession(accessToken, refreshToken,  36000, "bearer");
IBoxConverter boxConverter = new BoxJsonConverter();
IRequestHandler boxRequestHandler = new HttpRequestHandler();
IBoxService boxService = new BoxService(boxRequestHandler);
config =new BoxConfig(Client_Id, Client_Secret, Redirect_Uri);
IAuthRepository boxAuthRepository = new AuthRepository(config,  boxService, boxConverter, session);

// create box client
BoxClient client = new BoxClient(config, boxConverter, boxRequestHandler, boxService, boxAuthRepository, null, false);

client.Auth.SessionAuthenticated += HandleOnSessionAuthenticated;
_userId = userId;

 protected void HandleOnSessionAuthenticated(object sender, 
SessionAuthenticatedEventArgs args)
{
            // the session was authenticated or re-authenticated - so update the session field
            _session = args.Session;
            // and trigger our OnSessionAuthenticated event
            if (OnSessionAuthenticated != null)
            {
                OnSessionAuthenticated(sender, args);
            }
        }
}

This is critical to our application as it often runs for many hours scanning box.    Any ideas wht this is not working?

**Comment by carycheng** [comment]
Hey @whiskeyjimg,

Thank you for writing in, we will take a look at this and get back to you as soon as we can.

**Comment by mattwiller** [comment]
@whiskeyjimg Using the code you provided, we were unable to reproduce the issue you're seeing.  After an hour, the tokens are correctly refreshed and the `SessionAuthenticated` event is triggered.

I suspect the issue might lie in exactly what your code is doing in `OnSessionAuthenticated()`. 
 We see a few common sources of error around this topic;could you please verify that:
- You are either not creating a new `BoxClient` instance anywhere, or correctly re-attaching event handlers to any new `BoxClient` instance after creating it
- You are storing the new access and refresh tokens in the file

If both of those are true, then your application __should__ run without issue.
