### ISSUE TITLE
DownloadStreamAsync int offset values

### ISSUE THREAD

**Issue by mtnbiker987** [box/box-windows-sdk-v2#560]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
In my application I am using the SDK to download files and if they are above a specified size, I am splitting the requests and downloading in chunks and building the file locally rather than downloading the whole file at once. 
To accomplish this I am setting the `startOffsetInBytes` and `endOffsetInBytes` arguments in the `BoxFilesManager.DownloadStreamAsync` method. 

Unfortunately, those arguments are `int?` types which will not work for any values/file sizes over `int.MaxValue` of  2,147,483,647 bytes or almost 2GB. 

Would it be possible to update that method, or just overload it, using the `long?` type for the `startOffsetInBytes` and `endOffsetInBytes` arguments?

### Versions Used
.NET SDK: 3.16.0
.NET Framework/Core: 4.6.1

**Comment by mattwiller** [comment]
@mtnbiker987 Thanks for letting us know — you're right, this should use `long?` to account for offsets within the largest files supported by Box.  Based on https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md it seems like just changing the argument type from `int?` to `long?` might be considered a breaking change, so I'll plan on adding an overload and deprecating the old version of the method.

**Comment by mtnbiker987** [comment]
Matt, thanks for the quick response and implementation!!

**Comment by mattwiller** [comment]
@mtnbiker987 No problem!  The fix should be released now in v3.17.0 of the SDK; please give it a try and let us know if you run into any other issues!
