### ISSUE TITLE
Using a cached refresh token to get an access token

### ISSUE THREAD

**Issue by grillod** [box/box-windows-sdk-v2#565]
I've been through the sample apps but I'm not sure if my desired use case is supported.

I want a user to authorize my app once and then I want to cache the refresh token received from that auth.

From then on I want to be able to use that refresh token to get access tokens and do work on the users behalf in dropbox. This is a server application so the user won't always be around to authorize every time. And it may be several days between when the server app will need to do some work in the users dropbox account. 

I'm looking for sample code that illustrates that given a valid refresh token, how one might use the .net SDK to get an access code from that. I assume a new refresh token would be given when using a previously cached one to get an access token? And then I'd use that the next time I need an access token?

**Comment by mattwiller** [comment]
@grillod You should be able to do this by manually creating the client with the access token, and ensuring that every time the client automatically refreshes you save the new refresh token somewhere:

```c#
var tokenInfo = YourApp.getSavedTokenInfo();

var config = new BoxConfig("YOUR_CLIENT_ID", "YOUR_CLIENT_SECRET", new Uri("http://your.redirect.url.net/"));
var session = new OAuthSession(tokenInfo.AccessToken, tokenInfo.RefreshToken, 3600, "bearer");
var client = new BoxClient(config, session);

client.Auth.SessionAuthenticated += delegate(object o, SessionAuthenticatedEventArgs e)
{
    string newAccessToken = e.Session.AccessToken;
    string newRefreshToken = e.Session.RefreshToken;

    YourApp.storeNewTokenInfo(newAccessToken, newRefreshToken);
};
```

The SDK will automatically refresh its tokens if the access token provided this way is not valid, so you shouldn't need to worry too much about that part of the process; just getting the stored tokens into the client and letting it do the rest should be fine.  You'll just need to implement whatever logic you need for saving the tokens somewhere secure.

**Comment by grillod** [comment]
But lets say I dont have an access token. Because that expired days ago. I have Only a refresh token I have saved previously. How do I use that to get a new access and refresh token. 

Like I said , I only want a user to authenticate once and then the server to be able to start up and do some work days later. My server app wont be running continually so it wont get token updates. 

I want to use a refresh token alone to get an access and new refresh token. Is that possible?

**Comment by grillod** [comment]
Or are you saying its fine to give it a garbage access token because so long as the refresh token is good, Ill get an event with new tokens?

**Comment by mattwiller** [comment]
@grillod It's fine to provide the SDK an expired access token; it will automatically refresh for you (as long as the refresh token you provide is valid).

**Comment by grillod** [comment]
Great. Thankyou!
