### ISSUE TITLE
BoxSearchManager.SearchAsync sizeRangeXXXBoundBytes parameter types should be long

### ISSUE THREAD

**Issue by mtnbiker987** [box/box-windows-sdk-v2#566]
### Description of the Issue
Not a breaking issue, more of an enhancement request. 
This issue is similar to #560, where the `sizeRangeLowerBoundBytes` and `sizeRangeUpperBoundBytes` parameters are currently typed as `int?` but ideally should be `long?` to account for file sizes greater than 2GB.

### Versions Used
.NET SDK: 3.17.0
.NET Framework/Core: Framework 4.6.1

**Comment by mattwiller** [comment]
@mtnbiker987 Thanks for the report!  I just opened a PR to deprecate the existing search method and replace it with one that has the correct types; we should be able to get this into the next release of the SDK.

**Comment by mattwiller** [comment]
@mtnbiker987 We just released v3.18.0, which includes the fix for this issue.  Please let us know if you run into any more issues!
