### ISSUE TITLE
Sort and Direction - Search vs. Get Folder Items

### ISSUE THREAD

**Issue by dcrnojevac** [box/box-windows-sdk-v2#569]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Sort and Direction params were added to SearchAsync but per the Box API documentation there are no such parameters for that endpoint. However, there are such parameters on the endpoint for 'Get Folder Items'. Was this accidentally switched?

### Versions Used
Box.V2.Core(3.17.0)

**Comment by mattwiller** [comment]
@dcrnojevac It appears the documentation hasn't yet been updated, but the Search API does in fact have sort parameters now!

**Comment by dcrnojevac** [comment]
Ah, I see. It works when I tried something like 'modified_at' like it states in the method summary, but when I tried 'name' I get a bad request. Is there a way to sort by name? Also can you tell me when will the sort parameter be added for the 'Get Folder Items' endpoint?

**Comment by mattwiller** [comment]
@dcrnojevac I believe that right now, `modified_at` is the only field that search results can be sorted on.  I just put together PR #570 to add the sort parameters to `GetFolderItemsAsync()`, so that should be coming in the next SDK release, probably next week.

**Comment by dcrnojevac** [comment]
I see. Thank you for the info.

**Comment by mattwiller** [comment]
@dcrnojevac We just released v3.18.0, which includes the fix for this issue.  Please let us know if you run into any more issues!
