### ISSUE TITLE
BoxSearchManager is missing some search params

### ISSUE THREAD

**Issue by andrew-grichkevitch** [box/box-windows-sdk-v2#57]
Box Content API has 12 params for search request: http://developers.box.com/docs/#search
But BoxSearchManager operates only with three of them: https://github.com/box/box-windows-sdk-v2/blob/master/Box.V2/Managers/BoxSearchManager.cs

Are you planning to add all parameters in SDK?
Maybe there is any possibility to make request through SDK using all search params?

Thanks

**Comment by coolboy** [comment]
Closing old issues

Feel free to reopen it.
