### ISSUE TITLE
Is_external_collab_restricted missing from BoxUserRequest.cs

### ISSUE THREAD

**Issue by jtrujillo3** [box/box-windows-sdk-v2#573]
- [ X] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Attempting to use CreateEnterpriseUserAsync function; however, the BoxUserRequest it references does not contain the PropertyName "is_external_collab_restricted"

Looks like it would just need the below added to BoxUserRequest.cs
/// <summary>
/// Whether this user cis restricted from external collaboration
/// </summary>
[JsonProperty(PropertyName = "is_external_collab_restricted")]
public bool? IsExternalCollabRestricted { get; set; }

[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@jtrujillo3 Thanks for letting us know about the missing field.  We just released v3.18.0 of the SDK, which includes the fix for this issue.  Please let us know if you run into any more issues!
