### ISSUE TITLE
Constants does not contain the FILE_RESTORE_VERSION event

### ISSUE THREAD

**Issue by pmatte1** [box/box-windows-sdk-v2#575]
- [ X] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
When trying to capture the event of restoring a prior version of a file, I included the event **ItemMakeCurrentVersion** from Constants.cs.  The reason is because the event_type on the event is **FILE_VERSION_RESTORE**.  

### Versions Used
.NET SDK: 3.18.0
.NET Framework/Core: 4.5

### Steps to Reproduce
Go to a file with multiple versions.  Select ... --> Properties --> Versions.  Then click on the Make Current Version link.  This will generate an event with the event_type of FILE_VERSION_RESTORED.

        {
            "source": {
                "item_type": "file",
                "item_id": "491807******",
                "item_name": "_footer.txt",
                "parent": {
                    "type": "folder",
                    "name": "Folder Name",
                    "id": "82049******"
                },
                "owned_by": {
                    "type": "user",
                    "id": "217******",
                    "name": "owner-user",
                    "login": "owner-user@mydomain.com"
                }
            },
            "created_by": {
                "type": "user",
                "id": "8186******",
                 "name": "owner-user",
                 "login": "owner-user@mydomain.com"
            },
            "action_by": null,
            "created_at": "2019-07-17T04:24:19-07:00",
            "event_id": "b1c5e***-0000-001b-9f1b-29ad53******",
            "event_type": "FILE_VERSION_RESTORE",
            "ip_address": "xxx.xxx.xxx.xx",
            "type": "event",
            "session_id": null,
            "additional_details": {
                "size": 664,
                "version_id": "521283******"
            }
        }

### Error Message, Including Stack Trace
N/A - Functional Issue, not an actual error.

[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @pmatte1,

We have a pr for this here #577, thank you!

**Comment by PreciselyAlyss** [comment]
@pmatte1 Please reopen this if you see the issue reoccur with the latest version!
