### ISSUE TITLE
Downloading files causing problems

### ISSUE THREAD

**Issue by AdilKamal44** [box/box-windows-sdk-v2#580]
I have been using the sample code for downloading the files, but I am having several issues.
1. It never downloads the full size of file, suppose if the file is 1MB sometimes it will download 100 kb sometimes 200Kb or sometimes full size.
2. After downloading the file when I am trying to use the copy function to copy the file to another folder,  its gives an error message that file is in use.
Here is the sample code I copied from Box site.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Box.V2.Config;
using Box.V2.JWTAuth;

namespace BoxDownloadAllFiles
{
    class Program
    {
        static void Main(string[] args)
        {
            ExecuteMainAsync().Wait();
        }
      
        private static async Task ExecuteMainAsync()
        {
            using (FileStream fs = new FileStream($"./config.json", FileMode.Open))
            {
                var session = new BoxJWTAuth(BoxConfig.CreateFromJsonFile(fs));
                var client = session.AdminClient(session.AdminToken());
                var folderId = "987654321";
                var folder = await client.FoldersManager.GetInformationAsync(folderId);
                var folderName = folder.Name;
                var localFolderPath = Path.Combine(Directory.GetCurrentDirectory(), folderName);
                ResetLocalFolder(localFolderPath);

                var items = await client.FoldersManager.GetFolderItemsAsync(folderId, 1000, autoPaginate: true);
                var fileDownloadTasks = new List<Task>();
                var files = items.Entries.Where(i => i.Type == "file");
                foreach (var file in files)
                {
                    fileDownloadTasks.Add(client.FilesManager.DownloadStreamAsync(file.Id).ContinueWith((t) =>
                    {
                        var localFile = File.Create(Path.Combine(localFolderPath, file.Name));
                        return t.Result.CopyToAsync(localFile);
                    }));
                }
                await Task.WhenAll(fileDownloadTasks);
//  I am calling my function here to move files to another folder.
            }
        }

        private static void ResetLocalFolder(string localFolderPath)
        {
            if (!Directory.Exists(localFolderPath))
            {
                Directory.CreateDirectory(localFolderPath);
            }
            else
            {
                foreach (var file in Directory.EnumerateFiles(localFolderPath))
                {
                    File.Delete(Path.Combine(localFolderPath, file));
                }
                Directory.Delete(localFolderPath);
                Directory.CreateDirectory(localFolderPath);
            }
        }
    }
}

**Comment by mattwiller** [comment]
@AdilKamal44 Based on your description of the issue and the code you posted, it seems like you might not be correctly disposing the file download stream provvded by the SDK.  That stream is backed by a network connection to the download server, and must be disposed in order to complete that connection.  Failing to dispose the stream may cause the connection to the download server be held open indefinitely, and can cause exhaustion of available connection resources and/or other issues.  Could you try something like the following in your code and see if that helps?
```c#
fileDownloadTasks.Add(client.FilesManager.DownloadStreamAsync(file.Id).ContinueWith((t) =>
{
    using (var downloadStream = t.Result)
    {
        var localFile = File.Create(Path.Combine(localFolderPath, file.Name));
        return downloadStream.CopyToAsync(localFile);
    }
}));
```

**Comment by AdilKamal44** [comment]
> @AdilKamal44 Based on your description of the issue and the code you posted, it seems like you might not be correctly disposing the file download stream provvded by the SDK. That stream is backed by a network connection to the download server, and must be disposed in order to complete that connection. Failing to dispose the stream may cause the connection to the download server be held open indefinitely, and can cause exhaustion of available connection resources and/or other issues. Could you try something like the following in your code and see if that helps?
> 
> ```cs
> fileDownloadTasks.Add(client.FilesManager.DownloadStreamAsync(file.Id).ContinueWith((t) =>
> {
>     using (var downloadStream = t.Result)
>     {
>         var localFile = File.Create(Path.Combine(localFolderPath, file.Name));
>         return downloadStream.CopyToAsync(localFile);
>     }
> }));
> ```

Hi Matt,
With this code it downloads the file with 0 KB. Just for a test when I tried the code below, it works. So I am confused what is causing this problem.

var t= await client.FilesManager.DownloadStreamAsync(file.Id);
using( var localFile = File.Create(Path.Combine(localFolderPath, file.Name)))
{
 t.Copyto(localFile );
}

**Comment by mattwiller** [comment]
Ah, must be an issue with the asynchronous/parallel control flow you were using then.  If you want to keep the asynchronous behavior, you'll probably want to look carefully at when/how the code inside the `ContinueWith()` closure executes, to ensure that all the objects it uses are in the right state until the file is fully downloaded.

**Comment by AdilKamal44** [comment]
Hi Matt,
how can I make sure? Do you have any suggestions in your mind?
