### ISSUE TITLE
Missing fields in BoxFile & BoxFolder

### ISSUE THREAD

**Issue by i3arnon** [box/box-windows-sdk-v2#581]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
The `BoxFile` class doesn't expose fields that exist on the File object.

For example, `is_externally_owned`. which exists in the general API reference: https://developer.box.com/reference#file-object
And also in other client SDKs: https://github.com/box/box-java-sdk/blob/master/src/main/java/com/box/sdk/BoxFile.java#L1723

Missing fields for `BoxFile`:
- expires_at
- allowed_invitee_roles
- has_collaborations
- is_externally_owned

Missing fields for `BoxFolder`:
- expires_at
- is_collaboration_restricted_to_enterprise

### Versions Used
.NET SDK: 3.18.0
.NET Framework/Core: .NET Core 3 preview 7

**Comment by mattwiller** [comment]
@i3arnon Thank you for letting us know!  I put together a PR over at #582 to address this issue; we should be able to get the fix into the next SDK release later this week.

**Comment by i3arnon** [comment]
Sounds great :)
Thanks for the quick turnaround..
