### ISSUE TITLE
Issue while using Box sdk in VSTO Addin

### ISSUE THREAD

**Issue by LawrenceAntony** [box/box-windows-sdk-v2#587]
- [ ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Error "The type initializer for <Module> threw an exception. " occurring while using Box V2 assemblies

### Versions Used
.NET SDK: 4.7.2 
.NET Framework/Core: Framework

### Error Message, Including Stack Trace

[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by PJSimon** [comment]
Hi @LawrenceAntony, thanks for report.  Unfortunately, I'll need some more information about the issue you're experiencing before I can offer any assistance.  Can you tell me more how I might be able to reproduce your issue on my end so I can investigate?

More detailed error messages and a stack trace would be the most helpful.

Thanks so much!  I look forward to hearing back from you!

**Comment by LawrenceAntony** [comment]
@PJSimon  I am developing a VSTO powerpoint addin to download box enterprise files. 
My project's target platform is .net framework 4.7
I installed box sdk from nuget and its working good with visual studio and when i deploy it under Programfiles folder its not working. it works good in other folders.

**Comment by LawrenceAntony** [comment]
@PJSimon Here is the Inner exception and stack trace
Inner Exception: 
System.IO.FileLoadException: Could not load file or assembly 'BouncyCastle.Crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'BouncyCastle.Crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942'

=== Pre-bind state information ===
LOG: DisplayName = BouncyCastle.Crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942
 (Fully-specified)
LOG: Appbase = file:///C:/Users/Maria Lawrence Anton/source/repos/BoxConnectTest/BoxConnectTest/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : Box.V2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=ddda8fe64dde1ac3.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\Maria Lawrence Anton\source\repos\BoxConnectTest\BoxConnectTest\bin\Debug\BoxConnectTest.dll.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Redirect found in application configuration file: 1.8.1.0 redirected to 1.8.5.0.
LOG: Post-policy reference: BouncyCastle.Crypto, Version=1.8.5.0, Culture=neutral, PublicKeyToken=0e99375e54769942
LOG: Attempting download of new URL file:///C:/Users/Maria Lawrence Anton/source/repos/BoxConnectTest/BoxConnectTest/bin/Debug/BouncyCastle.Crypto.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

 Stack Trace 
   at Box.V2.JWTAuth.BoxJWTAuth..ctor(IBoxConfig boxConfig, IBoxService boxService)
   at BoxConnectTest.Ribbon1.<MainAsync>d__4.MoveNext() in C:\Users\Maria Lawrence Anton\source\repos\BoxConnectTest\BoxConnectTest\Ribbon1.cs:line 111

**Comment by LawrenceAntony** [comment]
I copied the code to console application and executed in Programfiles folder it works well.  Can anyone help me to solve this issue!

**Comment by LawrenceAntony** [comment]
Adding file:// prefix in vsto manifest registry entry resolved this issue.

**Comment by mattwiller** [comment]
@LawrenceAntony Glad you were able to find a solution — thank you for posting back here so anyone else running into the same problem later can see!
