### ISSUE TITLE
tracking_codes are not possible to set via the C# SDK

### ISSUE THREAD

**Issue by Cpcrook** [box/box-windows-sdk-v2#593]
- [ X] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I want to update or create a user and set the TrackingCodes property (underlying json field is "tracking_codes").
The setters for the BoxTrackingCode object are private, making this impossible, even though it is possible via the REST API directly (once tracking_codes are enabled for your enterprise)

### Versions Used
.NET SDK: 3.20.0

### Steps to Reproduce
Instantiate a BoxTrackingCode.  Try to set any of the properties on it and perform an create/update using it within a BoxUserRequest.

You won't get past compilation to the private setters.

### Error Message, Including Stack Trace
Property or indexer BoxTrackingCode.Name cannot be assigned to it is read-only.

------

I see no good reason this should be read-only when the REST API supports this functionality.  I'll be submitting a PR myself to fix this so I don't have to do reflection to set properties with private setters as a hack.

**Comment by sujaygarlanka** [comment]
Thank you for the pull request. Will take a look at this soon.
