### ISSUE TITLE
Improvement: optional fields param on UserManager.GetUserInformationAsync

### ISSUE THREAD

**Issue by Cpcrook** [box/box-windows-sdk-v2#601]
This would be consistent with the underlying REST API (including the collection of Postman examples).

Currently not supported by the Windows .NET SDK V2, despite the docs [here](https://developer.box.com/docs/sdks) saying the .NET SDK is in parity (presumably) with the underlying REST API.

**Comment by nidoran** [comment]
https://github.com/box/box-windows-sdk-v2/pull/605
