### ISSUE TITLE
Conflict Newtonsoft.Json version Box.V2 and Microsoft.IdentityModel.Tokens

### ISSUE THREAD

**Issue by SmartDuck72** [box/box-windows-sdk-v2#610]
**Problem**
When calling the method...
 adminToken = BoxJWT.AdminToken();

Message: 
The type initializer for 'System.IdentityModel.Tokens.Jwt.JsonExtensions' threw an exception. 

Inner exception message: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

**Possible cause** 
Dependency of Box.V2:  Newtonsoft.Json version 10.0.3
Dependency of Microsoft.IdentityModel.Tokens: Newtonsoft.Json version 9.0.1

**Software versions**
.NET framework: 4.5.1
BouncyCastle: 1.8.1
Box.V2: 3.20.0
Microsoft.IdentityModel.Logging: 1.1.4
Microsoft.IdentityModel.Tokens: 5.1.4
Newtonsoft.Json: 10.0.3
System.IdentityModel.Tokens.Jwt: 5.1.4

**Comment by SmartDuck72** [comment]
Solved by adding a version check in the app.config.

      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <codeBase version="1.0.0.0" href="Newtonsoft.Json.dll"/>
        <codeBase version="9.0.0.0" href="Newtonsoft9/Newtonsoft.Json.dll"/>
      </dependentAssembly>

Could this be a problem in the Box sdk?

**Comment by nidoran** [comment]
Microsoft.IdentityModel.Tokens 5.1.4  specifies a depedency requirement for Newtonsoft.Json (>= 9.0.1) https://www.nuget.org/packages/Microsoft.IdentityModel.Tokens/5.1.4
that the SDK satisifies (Newtonsoft.Json 10.0.3), so I'm not sure that the problem would lie within the SDK's configuration entirely.

Please let us know if you're having further issues with this.
