### ISSUE TITLE
Confusing discrepancy between BoxFolder.Parent & BoxFolder.PathCollection in some cases

### ISSUE THREAD

**Issue by Cpcrook** [box/box-windows-sdk-v2#612]
Perhaps this is just not clear from the API documentation, but there is a scenario that seems to manifest a surprising outcome regarding folder structure when looking at Parent vs. PathCollection.

### Expected Behavior
Given I have created a folder in the root of the enterprise with the app service account
And I have shared that folder with an App User
When I call FolderManager.GetFolderInformationAsync(folderId) as that App User
Then I expect the returned BoxFolder to have a Parent.ID of 0
And I expect the returned BoxFolder to have a PathCollection entry for folder 0

### Actual Behavior
The returned BoxFolder has a null Parent object, but the PathCollection _does_ have the virtual root (folder zero) present.

Looking at the documentation regarding this functionality, there doesn't seem to be a distinction as to why this would necessarily occur, since PathCollections are (per the API Docs):

> "The tree of folders that this folder is contained in, starting at the root." 

while the Parent is:

> The optional folder that this folder is located within.
> This value may be null for some folders such as the root folder or the trash folder.

-----

The cause seems to be that the App User must have access to the Parent folder in order to get back a non-null Parent value, but the PathCollection disregards the _physical_ structure of the location, and is relative to the current user's virtual root.

Not sure if I'm using the correct terminology here, but there's some goofiness going on where the app user sees the shared folder as being under their Folder Zero (virtual root) but when trying to get the parent folder info as that user, the parent is null, despite the PathCollection indicates there is in fact a parent folder.

If we're keeping in mind [the principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) these should probably behave the same way, or the documentation should be a lot more clear as to why they don't (i.e. giving another example of where parent folders may be null, but the path collection isn't empty)

**Comment by sujaygarlanka** [comment]
Hello Cpcrook,

The expected behavior you outlined seems reasonable. The discrepancy is on API side, and we will try to document this discrepancy in the near future. Sorry for any inconvenience and thanks for bringing it to our attention.
