### ISSUE TITLE
Error with new app and developer token authentication

### ISSUE THREAD

**Issue by psharkauburn** [box/box-windows-sdk-v2#613]
- [ X] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Just created a new custom app(s) trying both standard OAuth2 and OAuth2 + JWT. In both cases, I'm just generating a developer token and attempting a simple API call 'client.FoldersManager.GetFolderItemsAsync(0, 100)' or 'client.UsersManager.GetCurrentUserInformationAsync' and am getting a consistent failure of `Exception of type 'Box.V2.Exceptions.BoxSessionInvalidatedException' was thrown.`

I've been following the sdk instructions of:
`Dim config As New Box.V2.Config.BoxConfig(clientID, clientSecret, New Uri("http://localhost/"))
        Dim session As New Box.V2.Auth.OAuthSession(developerToken, "N/A", 3600, "bearer")
        Dim client As New Box.V2.BoxClient(config, session)`

after providing appropriate ClientID / ClientSecret / DeveloperToken strings based on the developer console page for my app. **Any ideas what I'm missing?** 

### Versions Used
.NET SDK: 3.20.0 from nuget
.NET Framework/Core: .Net Framework 4.7.2

### Error Message, Including Stack Trace
`Inner Exception 1:
BoxSessionInvalidatedException: Exception of type 'Box.V2.Exceptions.BoxSessionInvalidatedException' was thrown.`

**Comment by psharkauburn** [comment]
After trying a manual OAuth2 flow via https://account.box.com/api/oauth2/authorize? ... i was getting a 'this type of app is disabled by your administrator' type of message leading me to believe our accounts aren't allowed to connect with a custom app. Swapping from my organizations enterprise account to just an individual account and all is well it seems.

**Comment by carycheng** [comment]
Hey @psharkauburn,

I'm glad this issue was resolved! If you did want to use your new application you created the process for having your app authorized for your enterprise is for your admin to go to the: `enterprise settings page` -> `Apps` from the top navigation bar -> `Authorize New App` -> `Paste in your API key which is your client id`.

I hope this helps, thank you!

**Comment by PJSimon** [comment]
Hi @psharkauburn,

Here's some additional info / screenshots for you, regarding @carycheng's message: https://developer.box.com/en/guides/applications/custom-apps/app-approval/#as-admin

HTH,
Patrick
