### ISSUE TITLE
'ModifiedAt' property is set by preview time.

### ISSUE THREAD

**Issue by tokkn** [box/box-windows-sdk-v2#614]
-  I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
When get BoxItem by [Client.FoldersManager.GetInformationAsync] or [Client.FilesManager.GetInformationAsync].
The BoxItem.ModifiedAt is set by the last preview time(if it is the last access time).

### Versions Used
.NET SDK: Box.V2 3.20.0

### Error Message, Including Stack Trace

[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by PJSimon** [comment]
Hi @tokkn,

Sorry for the delay. My team is still catching up following the holidays! We'll respond back to you soon!

Thanks!

**Comment by sujaygarlanka** [comment]
@tokkn The SDK will present information returned from the API. When I test against the API by making manual requests, the returned `modified_at` time does not change every time I preview it, so the SDK should not be returning changing `modified_at` times. I would recommend making manual calls against the API and see if the `modified_at` times are changing. If they are not, and the SDK is reporting changing times then there is an SDK issue. I would recommend testing using Postman. The Box Postman collection can be found here: https://developer.box.com/en/guides/tooling/postman/. Hope this helps!

**Comment by tokkn** [comment]
@sujaygarlanka 
Thank you very much.
In my box, there are only a few files have the problem.
Not all files get the wrong modified_at date time.

I try to test get file info of the file with this problem by Postman use [BoxPlatform API>Files>Get file information],
The result of modified_at is right.
But when I get the same file info by [Client.FilesManager.GetInformationAsync].(C#@VS2003 Debug)
It returned the wrong date time (it always return a preview accessed time, not the last one).

Is there any different between [BoxPlatform API>Files>Get file information] and [Client.FilesManager.GetInformationAsync]?

**Comment by sujaygarlanka** [comment]
@tokkn There is no difference between `[BoxPlatform API>Files>Get file information]`  and `[Client.FilesManager.GetInformationAsync]?`. The SDK makes the  API request, gets the data, and puts the data into a model for easy access to that information. So I don't believe it is an SDK issue. Since this issue occurs for certain files, it could be that previewing these files affects the `modified_at` time. Are all the files that have this issue of a certain type?

Another option is look at the `content_modified_at` field. This field is more specific than `modified_at`, so it only changes when the content of the file or folder is modified. More details on this field can be found here: https://developer.box.com/en/reference/resources/file/#param-content_modified_at

**Comment by tokkn** [comment]
@sujaygarlanka
Thank you very much.
I made a mistake last time, the result from Postman or VS2013Debug is the same.

  | Postman | DebugVS2013
-- | -- | --
CreateAt | 2019-11-05T21:51:54-08:00 | {2019/11/06 14:51:54}
ModifiedAt | 2019-11-06T16:22:26-08:00 | {2019/11/07 9:22:26}
  |   |  
ContentCreateAt | 2019-11-05T21:49:24-08:00 | {2019/11/06 14:49:24}
ContentModfiedAt | 2019-11-05T21:49:41-08:00 | {2019/11/06 14:49:41}

Postman timezone is -8:00
My timezone is +9:00
I am sorry for that.

And return to my question,
The difference is between Updated(Display in Web) and API's ModifiedAt.
I try to test again, and find that when a file is moved to another folder,
In web , the [Updated] is also display the file's last upload time.
But the API's ModifiedAt is returned the Moved time. (Sorry, it is not  the last preview time)

  | Uploaded | File is Moved
-- | -- | --
Display Web Updated | Upload Time | Upload Time
API ModifiedAt | Upload Time | Moved Time

I am sorry, maybe this is not a issues,
But when a file is moved, 
How can I get the file's upload time By API (Like it display in web). 
I need to display the same thing in app like web.

Thank you very much!

**Comment by sujaygarlanka** [comment]
@tokkn If you are looking for when the file is uploaded to Box, I would look at the `create_at` field. This field shows when the file was created on Box, which should match the time file was upload to Box. For any other data you may be interested in getting on a file, I would look at this [documentation](https://developer.box.com/en/reference/resources/file/).

**Comment by tokkn** [comment]
Dear @sujaygarlanka
Good Day!
Thank you very much.
I want to know who modified the box file last time.
And from API, I can not get this information correctly.

The create_at field is the first time when the file was uploaded to box.
When the file was uploaded a new version by a user, 
At web, I can see the updated (time) is the uploaded time of new version and the user's name.
I also can get those info correctly by API.
It is right.

But When I moved the file, 
At web, the updated(time) is also the new version's uploaded time and the user's name.
From API, the modified_at is the time I moved the file.
And modified_by is also the user who uploaded the new version.

So from API, 
I got the file info is  modified at the time I moved it, modified by other user who uploaded it.
 
![image](https://user-images.githubusercontent.com/47196984/73702761-23558c00-4731-11ea-88ee-c41451270d66.png)

Kindly move a file (upload by other users) in box to a other folder, 
And then get the file info by API, Can you also get the same result at your box?

Thank you for your assistance.
Best Regards,
Tokkn

**Comment by sujaygarlanka** [comment]
@tokkn Have you tried looking at the `content_modified_at` field? This field should only update when the content is changed, so this should solve your issue.

**Comment by tokkn** [comment]
Dear @sujaygarlanka
Good Day!
Thank you very much.

I had confirmed the field content_modified_at,
The field content_modified_at is no problem,
It is real modified time of the file.

But my question is the box modified( uploaded, moved. ...) time is wrong.
When a file is moved to another folder,
the field modified_at is reset by the moved time.
If this is right, then why the field modified_by is not be reset to the user who moved it?

And at web, when a file is moved,
It also display the time when the file uploaded last time and who uploaded it.(Not the user who moved it)

Have you tried to test this at your box?
I want to know if it only gives the wrong information at my box.

Best Regards,
Tokkn

**Comment by sujaygarlanka** [comment]
@tokkn My Box works as yours. When I move a file, the display time is when the file was last uploaded and who uploaded it.

**Comment by tokkn** [comment]
Dear @sujaygarlanka
Good Day!
Thank you very much.

Because I need to display the same thing in app like the web.
So kindly keep this open.

Thank you for your assistance.
Best Regards,
Tokkn

**Comment by sujaygarlanka** [comment]
@tokkn On looking more deeply into this, I was able to replicate the issue you were having with the `modified_at` updating when a file is moved, but not the `modified_by`. This is not an SDK issue, but a backend issue. I filed a ticket with the team that manages this service. I will keep you updated with what they have to say.
