### ISSUE TITLE
Box SDK throwing issue when implemented in MIM

### ISSUE THREAD

**Issue by Leafry** [box/box-windows-sdk-v2#616]
- [✓] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I'm currently working on adding Box account provisioning and de-provisioning accounts and folders in a MIM library extension. When originally building and testing the code (utilizing the Box V2 version 3.20) I built a console application. The code I used was *almost* exactly the same. I ported it over to my MIM extension DLL and changed a few of the variables to pull from different objects but the NuGet package crashed.

Specifically, the crash comes from one of the dependencies, System.IdentityModel.Tokens.Jwt.JsonExtensions. This will throw an error every time a session is attempted in the cs file utilizing the SDK.

### Versions Used
.NET SDK: 3.20.0
.NET Framework: 4.5, also tried 4.7.2 (The console application was also built in 4.7.2)

### Steps to Reproduce
This might be very hard to reproduce since it is looking at MIM libraries and extensions but I am open to working together to demonstrate the issue. The full set up requires to call the MIM MVExtension file from the sync engine. The account that it is working with is newly provisioned accounts, they will go through the Box provision method which will call the Box SDK code.

### Error Message, Including Stack Trace
[Error message]:
Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

[Fusion log]:
Pre-bind state information
LOG: DisplayName = Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files/Microsoft Forefront Identity Manager/2010/Synchronization Service/
LOG: Initial PrivatePath = NULL
Calling assembly : System.IdentityModel.Tokens.Jwt, Version=5.1.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Program Files\Microsoft Forefront Identity Manager\2010\Synchronization Service\Bin\miiserver.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Forefront Identity Manager/2010/Synchronization Service/Newtonsoft.Json.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Forefront Identity Manager/2010/Synchronization Service/Newtonsoft.Json/Newtonsoft.Json.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Forefront Identity Manager/2010/Synchronization Service/bin/Newtonsoft.Json.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Forefront Identity Manager/2010/Synchronization Service/bin/Newtonsoft.Json/Newtonsoft.Json.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Forefront Identity Manager/2010/Synchronization Service/bin/assemblies/Newtonsoft.Json.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Forefront Identity Manager/2010/Synchronization Service/bin/assemblies/Newtonsoft.Json/Newtonsoft.Json.DLL.
LOG: Attempting download of new URL file:///C:/Program Files/Microsoft Forefront Identity Manager/2010/Synchronization Service/Extensions/Newtonsoft.Json.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Major Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

[Stack Trace]:
   at System.IdentityModel.Tokens.Jwt.JsonExtensions.SerializeToJson(Object value)
   at System.IdentityModel.Tokens.Jwt.JwtPayload.Base64UrlEncode()
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.WriteToken(SecurityToken token)
   at Box.V2.JWTAuth.BoxJWTAuth.ConstructJWTAssertion(String sub, String boxSubType, Nullable`1 nowOverride)
   at Box.V2.JWTAuth.BoxJWTAuth.GetToken(String subType, String subId)
   at Mms_Metaverse.WorkerFunctions.<CreateBoxAccount>d__3.MoveNext() in C:\Users\forsytedev1\source\repos\Saint Catherine - MIM\MVExtension\WorkerFunctions.cs:line 373

[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by PJSimon** [comment]
Hi @Leafry, 
I'm not sure how much help I can be without seeing more of your code.  From what you shared, it looks like:
>at Mms_Metaverse.WorkerFunctions.d__3.MoveNext() in C:\Users\forsytedev1\source\repos\Saint Catherine - MIM\MVExtension\WorkerFunctions.cs:line 373
makes a call that instantiates a BoxClient with JWT via 
`public BoxClient(IBoxConfig boxConfig, IAuthRepository authRepository, string asUser = null, bool? suppressNotifications = null)`
where the `authRepository` is set to an invalid token that BoxJWTAuth can't decode.  It looks like the exception details coming back from `ConstructJWTAssertion` are not being shown in the log.

I guess I would take a look at the token that's being passed into BoxClient via the authRepository object and try using it in Postman or via a `curl` command to see if the token is valid.  If you dig deeper and it looks like the issue is with the Box SDK itself, please let me know!

**Comment by PJSimon** [comment]
Hi @Leafry, I'm going to close out this issue, assuming you've found a way around it.  If that's not the case, then by all means, please re-open this issue and let us know how we can help further!  Thanks!
