### ISSUE TITLE
BoxItem or BoxFile returns field value blank

### ISSUE THREAD

**Issue by prakashnawalecloudywave** [box/box-windows-sdk-v2#617]
I used client.FoldersManager.GetFolderItemsAsync method to pull files under folder and this method returns  BoxCollection<BoxItem>, in BoxItem I can see below fields empty
tags
description
size
created_at
modified_at
created_by
modified_by
parent

even I tried client.FilesManager.GetInformationAsync this method again returns tags field blank.

### Description of the Issue
 call method client.FoldersManager.GetFolderItemsAsync  passing folder id and see all fields blank except id and name.

### Versions Used
.NET SDK: V2

[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by PJSimon** [comment]
Hi @prakashnawalecloudywave, 

Thanks for your question.  `client.FoldersManager.GetFolderItemsAsync` returns BoxItem objects in the [mini variant](https://developer.box.com/en/guides/api-calls/request-extra-fields/#mini), by default.  This is to decrease the size of the response when returning a collection of objects.  If you would like these objects to be populated with a particular field or list of fields, just pass in the field(s) you want in the `fields` parameter of `client.FoldersManager.GetFolderItemsAsync`.

As mentioned in the documentation for [Folders](https://github.com/box/box-windows-sdk-v2/blob/master/docs/folders.md#get-a-folders-items):
> Requesting information for only the fields you need can improve performance and reduce the size of the network response.

Let me know if that solves this issue for you, or if you have any other questions!

Thanks!

**Comment by PJSimon** [comment]
Hi @prakashnawalecloudywave, 

Thanks for your question.  `client.FoldersManager.GetFolderItemsAsync` returns BoxItem objects in the [mini variant](https://developer.box.com/en/guides/api-calls/request-extra-fields/#mini), by default.  This is to decrease the size of the response when returning a collection of objects.  If you would like these objects to be populated with a particular field or list of fields, just pass in the field(s) you want in the `fields` parameter of `client.FoldersManager.GetFolderItemsAsync`.

See [Folders](https://github.com/box/box-windows-sdk-v2/blob/master/docs/folders.md#get-a-folders-items) for more info.  Also note that:
> Requesting information for only the fields you need can improve performance and reduce the size of the network response.

I'm going to close this issue, but if that doesn't solves this issue for you, or if you have any other questions, please just re-open the issue!

Thanks!
