### ISSUE TITLE
Issues uploading large files to Box

### ISSUE THREAD

**Issue by rohanpathak** [box/box-windows-sdk-v2#62]
I am facing 2 issues regarding Box file upload feature. I have a requirement of uploading movie files to box through my .NET application.

Issue 1:
I am able to upload files of size 250-300 MBs but it takes long time. It takes around 1.5-3 mins to upload. When I upload the file from Box (using their web interface), it takes less than a minute to upload files.
Why is there so much of difference when you upload file from API and from Box Web interface?

Issue 2:
I am not able to upload files of size 500 MBs or more. The requests timeouts. I have set the timeout as 10 mins but still the error is thrown. I believe 10 mins should be enough time to upload file of size 500 MBs. Again when I upload same file from Box (using their web interface), it takes around a minute to upload files.

I am using Box V2 SDK for windows. Visual studio 2010/2012. Any help in this regards is appreciated. Please let me know if any more info is needed.

**Comment by coolboy** [comment]
Closing old issues

@rohanpathak please try https://www.nuget.org/packages/Box.V2/2.15.4 which has the UploadUsingSessionAsync()
