### ISSUE TITLE
Unable to create BoxTrackingCode object

### ISSUE THREAD

**Issue by trevonmckay** [box/box-windows-sdk-v2#620]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I am unable to create a tracking code using the .NET SDK it looks like the pull request for BoxTrackingCode constructors never made it to production. 

My goal is to create and assign tracking codes via the API however the following code sample fails

```
var trackingCode = new BoxTrackingCode("trackingCodeName", "trackingCodeValue");
```

### Versions Used
.NET SDK: 3.20.0
.NET Framework/Core: .NET Core 2.1

### Steps to Reproduce
1. Create .NET Core 2.1 project
2. Install Box.V2.Core (3.20.0) Nuget package
3. Somewhere in your project add the following line
```
var trackingCode = new BoxTrackingCode("trackingCodeName", "trackingCodeValue");
```

### Error Message, Including Stack Trace
'BoxTrackingCode' does not contain a constructor that takes 2 arguments

![image](https://user-images.githubusercontent.com/18320804/70254108-88e9c400-1752-11ea-8204-6aaef833ac5e.png)

[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by sujaygarlanka** [comment]
@trevonmckay Just released a new version of the SDK (v3.21.0). You are able to create and assign tracking codes in this new version.
