### ISSUE TITLE
Problem creating ENCRYPTED private Key

### ISSUE THREAD

**Issue by arnoldperozoGL** [box/box-windows-sdk-v2#621]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
App fails reading Private Key from the file.
JSON file downloaded from BOX with Application Data (Client Id, Token and Private/Public Keys) fails with the encrypted private key. Error Description: padblock corrupted
![unnamed](https://user-images.githubusercontent.com/46229581/71689967-f9dbc600-2d68-11ea-9df5-8560d9eff86b.png)

This might be a duplicate of [this](https://github.com/box/box-windows-sdk-v2/issues/396) but I already tried the specified workaround with no results.

### Versions Used
.NET SDK: BOX SDK 2.6
.NET Framework/Core: Net Core 2.2

**Comment by PJSimon** [comment]
Hi @arnoldperozoGL ,

Can you walk me through what you have tried, in regard to the workaround you linked to?  The portion discussing a hard-coded value as a sanity check seemed like a good thing to try, just to get something working for a starting point, namely:
`string privateKey = "-----BEGIN ENCRYPTED PRIVATE KEY-----\r\n#######\r\n-----END ENCRYPTED PRIVATE KEY-----\n";`

After trying that, I would be interested in what the output of config.ToString() would display (before instantiating the BoxJWTAuth object).  That would be another sanity check to make sure there's no corruption going on and everything is properly formatted.

Also you're more than welcome to share the config file that you downloaded and are using here, but please SANITIZE sensitive information first, by removing any values.

**Comment by arnoldperozoGL** [comment]
Hi @PJSimon ...

Thanks for your time and response ... This is my current CONFIG, before instantiating BoxJWTAuth Object. And config.ToString() returns: "Box.V2.Config.BoxConfig". This is with the hard-coded value.

![image](https://user-images.githubusercontent.com/46229581/72080932-30fb2b80-32c3-11ea-9b87-5fb4691e62bf.png)


To give you a little more context, I created a Box App and generated Public and Private Keys and Token from Box page. That is the current config file read by our App.

The issue is specifically with the private key, which apparently is incomplete or corrupted:

![image](https://user-images.githubusercontent.com/46229581/72080829-0ad58b80-32c3-11ea-821b-73f900fb8821.png)

**Comment by sujaygarlanka** [comment]
Hello @arnoldperozoGL,

Here is some sample code that imports the JSON file provided by Box for your application and makes a request (https://gist.github.com/sujaygarlanka/2a1a8495e2e55996c9e2454ed21dc6ab). This is working in my environment with with the most recent SDK. If you run into the pad block issue with this code, then I would recommend using a more recent version of our SDK.

**Comment by PJSimon** [comment]
Hello @arnoldperozoGL, I hope you had a nice weekend.  I just wanted to touch base to see how this is going.  Have you tried the sample code that @sujaygarlanka shared?  If that didn't work, then we can drill down on what the issue is.  If it did work, then we can start looking at what your application is doing that is causing it not to work.  I'll check back with you later today!  Please keep us posted!

**Comment by arnoldperozoGL** [comment]
There is an issue apparently with my user and application configuration and the keys generated, this is something I'm working with my team. We tried with other user keys and everything works

**Comment by PJSimon** [comment]
Thanks for the update, @arnoldperozoGL.  Please don't hesitate to re-open / open a new issue if you have any other issues.  Thanks!
