### ISSUE TITLE
Best practice to use clientkey/secret/public key json file in securely in Windows App

### ISSUE THREAD

**Issue by LawrenceAntony** [box/box-windows-sdk-v2#623]
I am creating a .net windows application for uploading a file to the box folder. I am using JWT authentication and storing the .json public key config file as a resource in my project. Now my concern is the .json file is very easy to tamper by anyone. Can anyone suggest how to secure the .json private key in windows application?

**Comment by PJSimon** [comment]
Hi @LawrenceAntony,

Great question and it's an important one!  I found some best practices from [Google](https://cloud.google.com/docs/authentication/api-keys#securing_an_api_key) on the web.  It's certainly not an exhaustive list.  You might try searching the web for a more .Net-specific set of best practices, which may include features in the .Net Framework and/or extensions.  For example, I found information about [Microsoft.Extensions.Configuration.UserSecrets](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.UserSecrets) on [MSDN](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.2&tabs=windows#access-a-secret).

Good luck!
