### ISSUE TITLE
The BoxItem class does not contain a definition for "TrashedAt"

### ISSUE THREAD

**Issue by manon2wheels** [box/box-windows-sdk-v2#628]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
The BoxItem class does not contain a definition for "TrashedAt" to access the "trashed_at" attribute.  Calling the GetTrashItemsAsync() method with fields defined, will return the trashed_at value but a BoxItem from a List does not have a definition for TrashedAt.

### Versions Used
.NET SDK: Box.V2.Core
.NET Framework/Core: .NET Core 2.2

### Steps to Reproduce
//Running this code will return the error below
int folderLimit = 100;       
int folderOffset = 0;      
IEnumerable<string> itemFields = new List<string>() { "id", "type", "name", "trashed_at", "modified_at", "modified_by", "parent" };    
BoxCollection<BoxItem> trashedItems = await boxClient.FoldersManager.GetTrashItemsAsync(folderLimit, folderOffset, itemFields, false);
List<BoxItem> trashedItemsList = trashedItems.Entries;

foreach (BoxItem item in trashedItemsList)
{
    var itemId = item.Id;
    var itemModifiedAt = item.ModifiedAt;
    var itemTrashedAt = item.TrashedAt;
}

### Error Message, Including Stack Trace
error caused by trying to access item.TrashedAt;
CS1061 C# does not contain a definition for and no accessible extension method accepting a first argument of type could be found (are you missing a using directive or an assembly reference?)

### Proposed Resolution
It looks that adding the properties to this class should create the definition, much like ModifiedAt: public class BoxItem : BoxEntity
//add code below
public const string FieldTrashedAt = "trashed_at";

[JsonProperty(PropertyName = FieldTrashedAt)]
        public DateTime? TrashedAt { get; private set; }

[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by PJSimon** [comment]
Hi @manon2wheels,

Thanks for reporting this!  We'll take a look at it soon.

Patrick

**Comment by manon2wheels** [comment]
Wonderful, just updated to 3.22.  Thank you
