### ISSUE TITLE
BoxUserManager.MoverUserFolderAsync configurable timeout

### ISSUE THREAD

**Issue by mkiosugadaikichi** [box/box-windows-sdk-v2#636]
When user owns many files,
BoxUserManager.MoverUserFolderAsync method takes longer time.

Current implementation, timeout is fixed default value.
HttpClient default timeout value is 100 seconds.
I think configurable timeout is useful.

**Comment by PJSimon** [comment]
@mkiosugadaikichi, thank you for opening this issue.  We will take a look ASAP and get back to you soon.  Thanks!

**Comment by sujaygarlanka** [comment]
@mkiosugadaikichi This issue has been solved by #681.
