### ISSUE TITLE
a deadlock occurs when obtaining an access token.

### ISSUE THREAD

**Issue by sin5** [box/box-windows-sdk-v2#638]
### Description of the Issue
In my Windows Forms application, a deadlock occurs when obtaining an access token.
I think that "ConfigureAwait (false)" is necessary for "await getResponse (request, isStream, httpRequest)" on line 40 of Box.V2/Request/HttpRequestHandler.cs

### Versions Used
.NET SDK:4.7.1

### Steps to Reproduce
```
        private void button1_Click(object sender, EventArgs e)
        {
            StreamReader reader = new StreamReader("./config.json");
            string json = reader.ReadToEnd();
            IBoxConfig config = BoxConfig.CreateFromJsonString(json);
            BoxJWTAuth boxJWT = new BoxJWTAuth(config);
            string token = boxJWT.AdminToken();  // <<== deadlock
        }
```

### Error Message, Including Stack Trace
No message due to deadlock.
The getResponse method of HttpRequestHandler class is trying to return "StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:".

**Comment by PJSimon** [comment]
@sin5, thank you for opening this issue.  We will take a look ASAP and get back to you soon.  Thanks!

**Comment by sujaygarlanka** [comment]
Hello @sin5, Thank you for investigating this issue. I took a look at line 40 in `HttpRequestHandler.cs` and I believe you are correct. We need to either add an `ConfigureAwait(false)` there or add an `await` on this line https://github.com/box/box-windows-sdk-v2/blob/86ded84643df0375b316d30e6af5e379622a3faf/Box.V2/JWTAuth/BoxJWTAuth.cs#L276. Could you please attach your application or a sample of the code that was failing for you? It will make it easier for us to test when we implement the fix.

**Comment by tjones0808** [comment]
once i hit the line of getting a token my app stops responding. has this been fixed on nuget yet?

**Comment by sin5** [comment]
Hello @sujaygarlanka , 　Thank you for your reply.
Attach a sample solution that will deadlock.

In my environment, I added await to the indicated location in BoxJWTAuth.cs, but it seems deadlock has occurred.

[BoxTest_638.zip](https://github.com/box/box-windows-sdk-v2/files/4341724/BoxTest_638.zip)

**Comment by tjones0808** [comment]
> Hello @sujaygarlanka , 　Thank you for your reply.
> Attach a sample solution that will deadlock.
> 
> In my environment, I added await to the indicated location in BoxJWTAuth.cs, but it seems deadlock has occurred.
> 
> [BoxTest_638.zip](https://github.com/box/box-windows-sdk-v2/files/4341724/BoxTest_638.zip)

Me as well. Added the await and still hangs when getting the token.

**Comment by sujaygarlanka** [comment]
@sin5 Thank you for the code! Will take a look.

**Comment by sin5** [comment]
Hello @sujaygarlanka ,
Yes, I tried .
But in my environment, I added 'await' to the indicated location in BoxJWTAuth.cs, but it seems deadlock has occurred.

**Comment by sujaygarlanka** [comment]
@sin5 To clarify, did you try just adding `ConfigureAwait (false)` to `await getResponse (request, isStream, httpRequest)` on line 40 of `Box.V2/Request/HttpRequestHandler.cs` and not adding await to BoxJWTAuth.cs?

**Comment by sin5** [comment]
@sujaygarlanka Yes, in my opinion, just add 'ConfigureAwait (false)' to line 40 of HttpRequestHandler.cs and do not add 'await' to BoxJWTAuth.cs.
Because, to add 'await' to BoxJWTAuth.cs, it is necessary to delete 'Result' in the same line, and the asynchronous process propagates to the caller.
As a result, the 'AdminToken' method itself must be asynchronous .
Or synchronize in the 'AdminToken' method.
However, if you synchronize with the 'AdminToken' method, the lock will still occur as before. (The last test I did.)
If the 'AdminToken' method is allowed to be asynchronous, this is a good idea. However, it may affect multiple code fixes and users.

**Comment by tjones0808** [comment]
@sin5 @sujaygarlanka hey guys, am I experiencing the same issue? I could really use some help here. This code works perfectly fine in my 4.5.1 console app. When I run this code in my 4.5.1 Windows UI App this hangs forever. 

![image](https://user-images.githubusercontent.com/10042391/77229363-deac7580-6b63-11ea-9ae7-94bc62ed9017.png)

**Comment by tjones0808** [comment]
@sin5 @sujaygarlanka 

> just add 'ConfigureAwait (false)' to line 40 of HttpRequestHandler.cs and do not add 'await' to BoxJWTAuth.cs.

This worked for me. Thanks.

**Comment by sam2332** [comment]
how do i fix this in my asp.net program? i have the module installed via nuget and i dont understand how to make the modifications to the HttpRequestHandler file.

**Comment by sam2332** [comment]
I am having the same issue using Package 'Box.V2.Core.3.22.0'
![image](https://user-images.githubusercontent.com/945622/78711574-30375d00-78e5-11ea-95c9-e8c9ce37c3a9.png)

error on the admin token line

**Comment by tjones0808** [comment]
You will need to clone the repo and make the change mentioned here in this
thread.

**Comment by sam2332** [comment]
Woah.... i didn't know it would mention it here... @tjones0808  can you confirm that i have applied the change correctly?

**Comment by sam2332** [comment]
now im having issues on line 276 of BoxJWTAuth.cs inside of Box.v2

the following line is hanging.

IBoxResponse<OAuthSession> boxResponse = this.boxService.ToResponseAsyncWithoutRetry<OAuthSession>(boxRequest).Result;

**Comment by tjones0808** [comment]
The only change I had to make was line 40 of HttpRequestHandler.cs
`                HttpResponseMessage response = await getResponse(request, isStream, httpRequest).ConfigureAwait(false);`

**Comment by BryceBarbara** [comment]
Why is this labeled as a question? It's quite obviously a bug.

**Comment by AlfredBr** [comment]
The fix is to add **.ConfigureAwait(false);**  to the end of line #41 in HttpRequesthandler.cs
I have verified that this works in my environment.

**Comment by AlfredBr** [comment]
We also need a **.ConfigureAwait(false);** at the end of line 71 in HttpRequestHandler.cs

![image](https://user-images.githubusercontent.com/14795095/81524509-7423e480-931f-11ea-944c-cec9ce1226cd.png)

**Comment by sujaygarlanka** [comment]
Box Windows SDK v3.23.0 released with a patch for this bug.
