### ISSUE TITLE
Please add "notification_email" field to user information

### ISSUE THREAD

**Issue by salexkidd** [box/box-windows-sdk-v2#639]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue

I'm using Box-windows-sdk-v2. I want to get notification_email field from User information, but SDK does not seem to this field. Could you add this field.

relevant code: 
https://github.com/box/box-windows-sdk-v2/blob/838a359cfd50c3a59999786555bc5130701b6697/Box.V2/Models/BoxUser.cs

### Versions Used
.NET Framework/Core: 3.1.0

### Steps to Reproduce

N / A 
### Error Message, Including Stack Trace
N / A

**Comment by Band-Aid** [comment]
The SDK is missing method to parse notification_email from the response.
 
```
    public class BoxEmailNotification
    {
        public const string FieldEmail = "email";
        public const string FieldIsConfirmed = "is_confirmed";


        public BoxEmailNotification(string email, bool value)
        {
            Email = email;
            IsConfirmed = value;
        }

        [JsonProperty(PropertyName = FieldEmail)]
        public string Email { get; private set; }

        [JsonProperty(PropertyName = FieldIsConfirmed)]
        public bool? IsConfirmed { get; private set; }
    }
```

**Comment by carycheng** [comment]
Thank you @salexkidd for the call out and @Band-Aid for the solution! We'll take a look at this and update you guys

**Comment by carycheng** [comment]
Hey @salexkidd we merged the change and it will go out with our next release. We will update you once it is released and something like this should work:
```
 var updates = new BoxUserRequest
            {
                Id = "12345",
                NotificationEmail = new BoxNotificationEmailField
                {
                    Email = "test@example.com"
                }
            };


BoxUser updatedUser = await client.UsersManager.UpdateUserInformationAsync(updates);
```

**Comment by salexkidd** [comment]
LGTM! Thx for your commit! :)
