### ISSUE TITLE
How to identify all the relay/workflows on a file or folder using .Net sdk

### ISSUE THREAD

**Issue by bmanju544** [box/box-windows-sdk-v2#643]
How to identify all the relay/workflows on a file or folder and also relay type like normal Task or Approval task using .Net sdk

**Comment by carycheng** [comment]
Hey @bmanju544, unfortunately that is not available at this time, however we will keep you updated if there is a change to the API and the ability to identify workflows on a file or folder is added.

However, normal tasks can be identified with this endpoint [here](https://developer.box.com/reference/get-files-id-tasks/). You can find the documentation for the .Net SDK [here](https://github.com/box/box-windows-sdk-v2/blob/master/docs/tasks.md#get-tasks-on-a-file).

Please let us know if you run into any issues, thanks!
