### ISSUE TITLE
How to get Box Notes file contents

### ISSUE THREAD

**Issue by bmanju544** [box/box-windows-sdk-v2#644]
How to get Box Notes file contents using Box .Net SDK  for different templates(Meeting Agenda, Calendar, Project Plan, Project Status, Newsletter)?

**Comment by sujaygarlanka** [comment]
@bmanju544 When you create a Box Note with a template, we do not store the information that the Box Note was created by a certain template. So, you cannot with an API call get all Box Notes created from a certain template. However, there are ways to implement this functionality.

When you create a Box Note, you can set metadata on the file that corresponds to what template was used to create the file either through an SDK call (https://developer.box.com/reference/post-files-id-metadata-id-id/) or through the Web App if the Box Note is being created online. 

Next, you can then query the files based on the metadata. So you can essentially make an API call that returns all files with a certain metadata value. So if you want all Box Notes with `Meeting Agenda` as the metadata value, you can do that. We are still working on the documentation for this. The method can be found [here](https://github.com/box/box-windows-sdk-v2/blob/0c995940aa29192dda5f06847bbeea34df6e381e/Box.V2/Managers/BoxMetadataManager.cs#L331). An example of how it can be used can be found [here](https://github.com/box/box-windows-sdk-v2/blob/0c995940aa29192dda5f06847bbeea34df6e381e/Box.V2.Test/BoxMetadataManagerTest.cs#L593). This is part of one of our tests, so a lot of the code you see is not important its use and just relates to our test. I hope this helps. Let us know if you have any questions!
