### ISSUE TITLE
How to get folders and files for a respective user using Box .NET SDK

### ISSUE THREAD

**Issue by praveendevireddy** [box/box-windows-sdk-v2#649]
How to get folders and files for a respective user using Box .NET SDK

**Comment by sujaygarlanka** [comment]
Hello @praveendevireddy, you can do this be creating a client for a user as described in our docs [here](https://github.com/box/box-windows-sdk-v2/blob/master/docs/authentication.md#as-user). Hope this helps!

**Comment by sujaygarlanka** [comment]
This question is covered by #652. I am closing this issue.
