### ISSUE TITLE
Connection token expires every 60 minutes. How to refresh the token in Box .NET SDK

### ISSUE THREAD

**Issue by praveendevireddy** [box/box-windows-sdk-v2#651]
Connection token expires every 60 minutes. How to refresh the token in Box .NET SDK

**Comment by sujaygarlanka** [comment]
@praveendevireddy You can create a `BoxJWTAuth` client found here https://github.com/box/box-windows-sdk-v2/blob/master/docs/authentication.md#server-auth-with-jwt. This works if you are using JWT authentication for your App. If you are using OAuth for your app, you should create an OAuth client here https://github.com/box/box-windows-sdk-v2/blob/master/docs/authentication.md#traditional-3-legged-oauth2. 

I would first take a look at our guides [here](https://developer.box.com/guides/authentication/select/) to figure out which authentication method to use. Once you choose, you can choose the appropriate client above.
