### ISSUE TITLE
using Box .NET SDK how to get all the users along with there Folders/Files, File Comments, tags

### ISSUE THREAD

**Issue by praveendevireddy** [box/box-windows-sdk-v2#652]
using Box .NET SDK I want to access all the user's information including user-specific Folders and Files, File Comments, tags.

**Comment by sujaygarlanka** [comment]
Hello @praveendevireddy, to do this you must first create a user client as shown [here](https://github.com/box/box-windows-sdk-v2/blob/master/docs/authentication.md#as-user). Afterwards, use that client to make calls to get folders, files, comments etc. Documentation for these calls can be found [here](https://github.com/box/box-windows-sdk-v2/tree/master/docs). An example would be to create user client then make the following call `BoxCollection<BoxItem> folderItems = await client.FoldersManager.GetFolderItemsAsync("0", 100);`. This will get all the files, folders, and weblinks found in the users root directory in Box. I hope this helps!
