### ISSUE TITLE
Using Box .NET SDK how to check the file is marked as favorites

### ISSUE THREAD

**Issue by praveendevireddy** [box/box-windows-sdk-v2#653]
I am using Box .NET SDK and getting all the folders and files from the Box.

While looping all the files I want to check is the file is marked as favorite or not.

**Comment by sujaygarlanka** [comment]
@praveendevireddy Pass in `collections` as a field value to this [method](https://github.com/box/box-windows-sdk-v2/blob/master/docs/files.md#get-a-files-information). This will return a collections value which will show you all the collections the file is a part of. If the file is part of the favorites collection, then you know it is marked as a favorite.

The fields parameter is explained [here](https://developer.box.com/guides/api-calls/request-extra-fields/).
