### ISSUE TITLE
Using Box.net SDK how to fetch Tags associated with a file

### ISSUE THREAD

**Issue by codingsisya** [box/box-windows-sdk-v2#656]
- As per SDK documentation, "Tags" property of BoxFile object should provide information about tags associated with respective file, but it is coming null always. File has tags. 

### Description of the Issue
Even though a File has tags associated with it, when we fetch file object using .net SDK and try to read Tags property of that file, it is always null. 

### Versions Used
.NET SDK latest version

### Steps to Reproduce
Upload a new file to your box
Add a Tag to that file
Run .NET SDK to fetch File properties
Tags property of that file object will be null

**Comment by sujaygarlanka** [comment]
@codingsisya A `tags` field parameter must be passed in to get the tags. More detail on fields can be found [here](https://developer.box.com/reference/get-files-id/). How to pass in fields to the SDK for this command can be found [here](https://github.com/box/box-windows-sdk-v2/blob/master/docs/files.md#get-a-files-information).
