### ISSUE TITLE
The .NET SDK - BoxClient.FoldersManager.CreateAsync Description Field Does Not Work

### ISSUE THREAD

**Issue by keithgagne** [box/box-windows-sdk-v2#657]
- [X] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I am creating a new folder in Box and include the Description field with text. The new folder gets created fine but it does not contain the description text. 

### Versions Used
.NET SDK: Box.V2 v3.22.0

### Steps to Reproduce
Example Code:
public Task<BoxFolder> CreateNewFolder(BoxClient userClient, string name, string description, string parentID)
{
     BoxFolderRequest folderRequest = new BoxFolderRequest
     {
          Name = name,
          Description = description,
          Parent = new BoxFolderRequest { Id = parentID }
     };
     return userClient.FoldersManager.CreateAsync(folderRequest);
}

### Error Message, Including Stack Trace
No error, new folder gets created but without the Description

[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by sujaygarlanka** [comment]
@keithgagne Our API does not allow setting the description when creating a folder. We will look into removing this option in the SDK or working to add this feature in the API. Will keep you update to date on any progress around this issue.
