### ISSUE TITLE
Deadlock in AdminToken()

### ISSUE THREAD

**Issue by BryceBarbara** [box/box-windows-sdk-v2#659]
I'm running into a deadlock caused by someone trying to improperly use async functions inside a non-async one.

https://github.com/box/box-windows-sdk-v2/blob/86ded84643df0375b316d30e6af5e379622a3faf/Box.V2/JWTAuth/BoxJWTAuth.cs#L276

Can we get someone to fix it so it doesn't do this?

**Comment by sujaygarlanka** [comment]
Duplicate here #638
