### ISSUE TITLE
Null Argument Exception

### ISSUE THREAD

**Issue by peter-shinydocs** [box/box-windows-sdk-v2#665]
- [ x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
Line 157 of BoxResourceManager.cs is calling AddRange with a null in cases where the folder doesn't exist in Box. This causes an ArguementException to be thrown from AddRange. AddRange should never receive a null.

### Steps to Reproduce
Call AutoPaginateLimitOffset with a folder that doesn't exist. 

### Expected Behavior
Not throw an exception

### Error Message, Including Stack Trace
Value cannot be null.
Parameter name: collection

### Versions Used
3.0.23

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by pvan-canada** [comment]
Hi. I don't get the opportunity to contribute much but I thought this would be a good give back. Simple fix but my integration tests aren't passing due to a SessionException ??? Any help would be more than welcome haha.

**Comment by sujaygarlanka** [comment]
@pvan-canada Thanks for the PR! Will take a look at this. Don't worry about integration tests passing. We only check that all unit tests passing.

**Comment by mwwoda** [comment]
Fixed via #666
