### ISSUE TITLE
Documentation: No documentation for Events (EventsManager)

### ISSUE THREAD

**Issue by jacquesvandermerwe** [box/box-windows-sdk-v2#670]
- [ X] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [X ] I have checked that the [API documentation][api-docs] doesn't solve my issue.

### Description of the Issue
There is no documentation that describes the EventManager and events endpoint. 

### Steps to Reproduce
Review the docs markdown files.

### Expected Behavior
Documentation for EventsManager

NA

### Screenshots
NA

### Versions Used
.Net SDK:NA
Windows: NA

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by PJSimon** [comment]
Hi @jacquesvandermerwe ,

Thanks for submitting this Issue! We will take a look and get back to you ASAP!

@PJSimon

**Comment by mwwoda** [comment]
Events documentation is already provided here https://github.com/box/box-windows-sdk-v2/blob/main/docs/events.md
