### ISSUE TITLE
Issue with Box App Private Key

### ISSUE THREAD

**Issue by baskarmib** [box/box-windows-sdk-v2#674]
- [X] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ ] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

We are using Azure Key Vault to store the Private Key and other credentials. It looks like there is some encoding issues. I have tried suggestions mentioned in previous issues but no luck.
https://github.com/box/box-windows-sdk-v2/issues/621

The Private Key is not getting loaded correctly. The same code works in local where the configuration values are read from local.settings.json file.

### Steps to Reproduce
1. Add the Private Key from Box Config JSON to Azure Key Vault as Key1 with value as below.
-----BEGIN ENCRYPTED PRIVATE KEY-----\r\nXXMMSDS\r\n-----END ENCRYPTED PRIVATE KEY-----\n
2. Add a Key as "BoxKey" in Azure Function Configuration and provide value using Key Vault Reference.
3. In code access the configuration value "BoxKey" using below syntax.

```
string jwtPrivateKey = Environment.GetEnvironmentVariable("BoxKey").ToString();
            log.LogInformation(jwtPrivateKey);
            config = new BoxConfig(Environment.GetEnvironmentVariable("boxClientID"),
                Environment.GetEnvironmentVariable("boxClientSecret"),
                Environment.GetEnvironmentVariable("boxEnterpriseID"),
                jwtPrivateKey,
                Environment.GetEnvironmentVariable("boxPassphrase"),
                Environment.GetEnvironmentVariable("boxPublicKeyId"));

            var session = new BoxJWTAuth(config);
            return session;

```
### Expected Behavior
This should create the user and admin client sessions.

### Error Message, Including Stack Trace
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: 
 ---> System.IO.IOException: -----END ENCRYPTED PRIVATE KEY not found
   at Org.BouncyCastle.Utilities.IO.Pem.PemReader.LoadObject(String type)
   at Org.BouncyCastle.Utilities.IO.Pem.PemReader.ReadPemObject()
   at Org.BouncyCastle.OpenSsl.PemReader.ReadObject()
   at Box.V2.JWTAuth.BoxJWTAuth..ctor(IBoxConfig boxConfig, IBoxService boxService)
   at Box.V2.JWTAuth.BoxJWTAuth..ctor(IBoxConfig boxConfig)

### Versions Used
.Net SDK: .Net Core 3.0
Box .Net SDK Latest Version.

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by sujaygarlanka** [comment]
@baskarmib Sorry for the delayed response. Is this still an issue?

**Comment by baskarmib** [comment]
What is the recommended approach? Do we need to use Secrets or Keys in Azure Key Vault to store the Private Key?

**Comment by sujaygarlanka** [comment]
@baskarmib Is this still an issue?

**Comment by baskarmib** [comment]
@sujaygarlanka we converted the Private Key to Base64 Format and stored the same in Azure Vault. This way it helped to resolve the issue.
