### ISSUE TITLE
How to get folder or File complete path information using Box .Net SDK

### ISSUE THREAD

**Issue by karthik161** [box/box-windows-sdk-v2#684]
How to get folder or File complete path information using Box .Net SDK

**Comment by sujaygarlanka** [comment]
Hello @karthik161, For file path information I would use the code [here](https://github.com/box/box-windows-sdk-v2/blob/master/docs/files.md#get-a-files-information) to get the file, then get the path collection information for that file. The code should look like below. The path collection object is described [here](https://developer.box.com/reference/resources/file/#param-path_collection).

```
BoxFile file = await client.FilesManager.GetInformationAsync(id: "11111");
BoxCollection<BoxFolder> pathCollection = file.pathCollection;
```

I hope this helps! Feel free to re-open this issue if you have any other questions regarding this issue.

**Comment by karthik161** [comment]
Thank your it was help full Sujay
