### ISSUE TITLE
How to identify whether a Folder shared with External/Internal user Using .Net SDK?

### ISSUE THREAD

**Issue by karthik161** [box/box-windows-sdk-v2#685]
How to identify whether a Folder shared with External/Internal user Using .Net SDK?

How to identify whether file/Folder is created by me or Shared by another user using .Net SDK?

**Comment by sujaygarlanka** [comment]
You can get the `created_by` field shown [here](https://developer.box.com/reference/resources/file/#param-created_by) for a file or folder to know who created the item. This can be done in .NET for a file like below. For a folder the call is very similar, I would take a look at the docs [here](https://github.com/box/box-windows-sdk-v2/tree/master/docs).

```
BoxFile file = await client.FilesManager.GetInformationAsync(id: "11111");
BoxUser user = file.CreatedBy;
```

**Comment by karthik161** [comment]
can you please let me know how to identify whether user is External user or Internal user?

**Comment by sujaygarlanka** [comment]
@karthik161 The best way to know whether the folder is shared with an external or internal user is get all the collaborations on a folder shown [here](https://github.com/box/box-windows-sdk-v2/blob/master/docs/collaborations.md#get-the-collaborations-on-a-folder). Afterwards, I would go through those collaborations and get the `accessible_by` for each collaboration. If any of the collaborations are accessible by someone with a login that is not part of the enterprise, then they are external. The API response for getting collaborations is [here](https://developer.box.com/reference/get-folders-id-collaborations/). If you have any other questions regarding this, feel free to re-open this issue.

**Comment by karthik161** [comment]
Hey Sujay thank you, i got it and thanks for your help for detailed explanation
