### ISSUE TITLE
Moving all folders from one user another user account

### ISSUE THREAD

**Issue by praveendevireddy** [box/box-windows-sdk-v2#686]
We are having a requirement where we need to move all the folders (excluding shared folders with the user) to another user's folder.

Ex:
There are 3 users, user1, user2 and user3
user2 has shared some folders with user1
need to move all users1 folders (excluding the folders shared by user2 to user1) to user3 folder

**Comment by sujaygarlanka** [comment]
@praveendevireddy This is the [method](https://github.com/box/box-windows-sdk-v2/blob/master/Box.V2/Managers/BoxUsersManager.cs#L325) that should solve your issue.
