### ISSUE TITLE
How to get user id from email address

### ISSUE THREAD

**Issue by praveendevireddy** [box/box-windows-sdk-v2#687]
I have a requirement where I will be reading a csv file which a list of user email address. For passing each user email address I need to get the user id.

**Comment by sujaygarlanka** [comment]
@praveendevireddy The only way is to list all enterprise users and find the user with the same email address. That user object with the same email address will also have a user ID. The method for list enterprise users is [here](https://github.com/box/box-windows-sdk-v2/blob/master/docs/users.md#get-enterprise-users). 

Please first check our developer docs found [here](https://developer.box.com/reference/) and our SDK docs found [here](https://github.com/box/box-windows-sdk-v2/tree/master/docs). If these documents don't answer your questions, then we would love to help.
