### ISSUE TITLE
HI Team, could you please let me know, how to get the user last logged in information using .Net SDK

### ISSUE THREAD

**Issue by karthik161** [box/box-windows-sdk-v2#689]
HI Team, could you please let me know, how to get the user last logged in information using .Net SDK

**Comment by sujaygarlanka** [comment]
@karthik161 There is no way to get the last logged in time off a user object. The only way would be to monitor the event stream for an enterprise and find when the user logged in. The docs on event streams can be found [here](https://developer.box.com/guides/events/for-enterprise/). The event stream methods in the .NET SDK can be found [here](https://github.com/box/box-windows-sdk-v2/blob/001f5ae01c8d62fdecdd4e0c18f5afe1eece248a/Box.V2/Managers/BoxEventsManager.cs). Feel free to re-open this issue if you have any more questions regarding this issue.
