### ISSUE TITLE
Box notes content is not getting as is

### ISSUE THREAD

**Issue by Rama-8844** [box/box-windows-sdk-v2#691]
Team, 

I am trying to download box notes and need to convert to word document.  But rich text format content is not downloading.  Requesting you to please let me know how to get and convert box template notes to word document as it is.

Thanks,
Ramakrishna T

**Comment by PJSimon** [comment]
Thanks for submitting this issue.  Unfortunately, it is missing the required checkbox fields that were provided in the initial Issue template.  Please re-create this issue and be sure to check the boxes at the top of the issue after you've performed each step.  Thanks for helping to streamline our process!
