### ISSUE TITLE
Is there any script/command to disable and enable box sync and Box drive?

### ISSUE THREAD

**Issue by karthik161** [box/box-windows-sdk-v2#701]
Hi Team,

is there any script/command to disable and enable box sync and Box drive?

**Comment by sujaygarlanka** [comment]
@karthik161 There is no API call to enable/disable box sync or drive for an enterprise. You can enable/disable Box sync for a user https://developer.box.com/reference/put-users-id/#param-is_sync_enabled. The method in the .NET SDK can be found [here](https://github.com/box/box-windows-sdk-v2/blob/master/docs/users.md#update-user). If you want to disable box sync or box drive for an enterprise without you using the API, there may be a way in the admin console. I would check our support docs for that https://support.box.com/hc/en-us/community/topics. Feel free to re-open this question if you have any follow-up questions.
