### ISSUE TITLE
Box SDK error on our file processing system

### ISSUE THREAD

**Issue by rul3rst4** [box/box-windows-sdk-v2#702]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
We've been using BOX SDK for a long time and we just switched from Oauth Standard authentication to a JWT Authentication on our service account because we were having issues with the Oauth Standard Token expiring.

It was working really great until day 22 of september. Now, we're getting the error bellow on almost every upload request we make... It doesn't follow any pattern, sometimes the same file can be uploaded later on.

We also have a problem where files larger than 80MB throw an error every time, so we cannot upload larger files on our system, since we rarely have them, we do it manually. (We've always had this problem, it doesn't started on day 22, but i'm sharing this problem to see if it's related).

I'm posting this as a question to understand what's happening.

I've tried to tracert requests to box.com and api.box.com, both of them are reaching the destination

### Steps to Reproduce

There is no much step to reproduce... We use the code bellow to upload the file.

### Expected Behavior
The file to be upload to BOX. The way it was working until 2 weeks ago.

### Error Message, Including Stack Trace
Error image:
![image](https://user-images.githubusercontent.com/37764417/95513792-48ba2a00-0991-11eb-8e0d-fc5e57db71a9.png)

### Screenshots
Code that does the upload...  We check the file size to decide wether we use chunked send or not.
![image](https://user-images.githubusercontent.com/37764417/95514263-06ddb380-0992-11eb-9ff3-eff808eb64bd.png)

### Versions Used
.Net SDK: Latest version of the .NET SDK V2. I've updated to see if the error was related to our outdated version.
Windows: Windows server 2008 R2 Standard SP 1

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-windows-sdk-v2/search?type=Issues

**Comment by sujaygarlanka** [comment]
@rul3rst4 We will take a look at this and get back to you ASAP!

**Comment by rul3rst4** [comment]
Ok, @sujaygarlanka . I'll be waiting. Thank you.
