### ISSUE TITLE
Getting "System.PlatformNotSupportedException: Operation is not supported on this platform." in UWP app with UseDotNetNativeToolchain set to true

### ISSUE THREAD

**Issue by MikeGilkeson** [box/box-windows-sdk-v2#714]
- [X] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [X] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [X] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [X] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
Calling BoxFoldersManager.GetFolderItemsAsync (or method that calls BoxResourceManager.AddDefaultHeaders) with a UWP application that has "Compile with .NET Native tool chain" checked throws PlatformNotSupportedException.

### Steps to Reproduce
1. Create a UWP app (or any app that compiles to .Net Native)
2. Reference Box SDK and call BoxFoldersManager.GetFolderItemsAsync
3. Build in release mode
4. Run the application in release mode, calling BoxFoldersManager.GetFolderItemsAsync will throw PlatformNotSupportedException

### Expected Behavior
No exception

### Error Message, Including Stack Trace
EXCEPTION: System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.CreateValueCallback.EndInvoke(IAsyncResult) + 0x1f
   at Box.V2.Managers.BoxResourceManager.GetNetCoreVersion() + 0x28
   at Box.V2.Managers.BoxResourceManager.GetBoxUAHeader() + 0x16
   at Box.V2.Managers.BoxResourceManager.AddDefaultHeaders(IBoxRequest) + 0x3d
   at Box.V2.Managers.BoxResourceManager.<ToResponseAsync>d__11`1.MoveNext() + 0x3f
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x5d
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x43
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x18
   at Box.V2.Managers.BoxResourceManager.<AutoPaginateLimitOffset>d__15`1.MoveNext() + 0xf9
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x5d
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x43
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x18
   at Box.V2.Managers.BoxFoldersManager.<GetFolderItemsAsync>d__2.MoveNext() + 0x225

### Versions Used
.Net SDK: 
Windows: Windows 10 1909

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-windows-sdk-v2/search?type=Issues

**Comment by hironytic** [comment]
Are there any updates on this issue?
This issue is severe because it prevents UWP apps from using Box SDK :cry:

The exception is thrown by accessing `Assembly.CodeBase` property in order to make User-Agent string.

https://github.com/box/box-windows-sdk-v2/blob/82962955281c39936358cb8b277c978debab29fd/Box.V2/Managers/BoxResourceManager.cs#L386

`CodeBase` property is not supported in UWP app because, in my understanding, it returns a file location on user's storage, which is supposed to be a privacy data.
Could you find another way to compose User-Agent string?

**Comment by cghersi** [comment]
We are experiencing the same Exception but in a slightly different environment:
1) The Exception is thrown only in the method BoxFilesManager.UploadAsync(...).
2) The Exception is thrown only on some machines, but we haven't been able to understand the pattern of the failing machines
3) We actually use the other methods like GetFolderItemsAsync(...) etc., with no problem.

We are using the NuGet package Box.V2.Core v.3.25.0.

**Comment by mwwoda** [comment]
The problem with composing the user-agent header on some platforms should have already been addressed by https://github.com/box/box-windows-sdk-v2/pull/851. If you are still having problems in your environment, feel free to reopen this issue with detailed steps explaining how to reproduce this problem so we can investigate it further.
