### ISSUE TITLE
Add support for new Client Credentials Grant Type

### ISSUE THREAD

**Issue by lurch89** [box/box-windows-sdk-v2#719]
### Is your feature request related to a problem? Please describe.
Per blog post (https://support.box.com/hc/en-us/articles/360056830074-Authenticate-apps-with-Client-Credentials-Grant-Type) the API now supports a Client Credential grant type that simplifies some app access. The post is from Nov 2020 and the last commit on the repo was Oct 2020.

### Describe the solution you'd like
Documentation and method support to allow a token to be generated with simply the client_id, client_secret, and enterprise_id (or user as box_subject_type).

### Describe alternatives you've considered
Manually generating an access token via RestSharp and a custom call. This requires extra objects and having to parse in the returned access token to the OAuthSession object. No support for autorenew or generating a new token without calling back to custom RestSharp method.

**Comment by PJSimon** [comment]
Hi @lurch89 ,

Thanks for submitting this enhancement request! This is on our roadmap (SDK-1589) as a feature we have prioritized to be implemented in the quarter or two.  When we have a more detailed timeline, we can update this GitHub Issue.  

We have some other updates coming for the .Net SDK, in the meantime, to bring it up-to-date with the latest API changes.

Thanks so much,

@PJSimon

**Comment by sujaygarlanka** [comment]
@lurch89 In the meantime, you can use the following authentication methods found in our docs [here](https://github.com/box/box-windows-sdk-v2/blob/master/docs/authentication.md).
