### ISSUE TITLE
We are getting a BoxSessionInvalidatedException for customer but not in our lab

### ISSUE THREAD

**Issue by eschneider272** [box/box-windows-sdk-v2#722]
### Description of the Issue
The issue only happens for the customer, in our lab it seems to work fine. But for the customer the session event doesn't seem to fire. The initial auth seems to work.

### Expected Behavior
No error

### Error Message, Including Stack Trace

"Error processing folder 131263188728. Error: Exception of type 'Box.V2.Exceptions.BoxSessionInvalidatedException' was thrown."	BOX_9479**

### Versions Used
BoxV2 version 3.13.1
.net 4.5

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-windows-sdk-v2/search?type=Issues

**Comment by sujaygarlanka** [comment]
Hello @eschneider272, This seems like an environment issue on you customer's end. Unless we have more information like the code that is being run and the .NET version they are running, etc., we can't help debug. Sorry!
