### ISSUE TITLE
Update of used packages

### ISSUE THREAD

**Issue by BenTheBest69** [box/box-windows-sdk-v2#724]
I'm wondering if you guys are planning to update the packages used by this with the latest?

It cause Dlls issues when you use later version of BouncyCastle.Crypto.dll, anything after 1.8.1 even if you mention that newer version of that dll is supported.

Thanks.

**Comment by mwwoda** [comment]
Hi @BenTheBest69. 

Thanks for reaching out to us! We have already updated the BouncyCastle library to version1.8.9 (which is the latest version at the moment) along with other dependencies like Newtonsoft.Json. If you have any questions related to other dependencies, feel free to reopen this ticket.

Thanks,
Mateusz
