### ISSUE TITLE
The SSL connection could not be established, see inner exception. Authentication failed because the remote party has closed the transport stream.

### ISSUE THREAD

**Issue by MuhammadZeshan382** [box/box-windows-sdk-v2#727]
I receive this exception after creating the connection with box API and when I call the BoxManager.Read(FileId). Please help me with that full exception details are attached below. 

Code is in .NET framework 4.6.1

![Capture222315](https://user-images.githubusercontent.com/57593874/113107388-4be5f280-921d-11eb-84d3-a7f5a4e8150d.JPG)

**Comment by swfree** [comment]
Hi @MuhammadZeshan382, thanks for submitting this issue! We will take a look and get back to you ASAP.

**Comment by swfree** [comment]
Hi @MuhammadZeshan382, is there anything about your network infrastructure that might be causing connection issues here? E.g. firewall or proxy server?
