### ISSUE TITLE
Box API Supports CollaborationRestricted, while the Windows SDK does not allow this in the BoxFolderRequestModel

### ISSUE THREAD

**Issue by Christian-Oleson** [box/box-windows-sdk-v2#731]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
The box API supports a field on the BoxFolderRequest which is:
is_collaboration_restricted_to_enterprise
This is not found in the Windows SDK and needs to be updated accordingly.

### Steps to Reproduce
1. See this param: https://developer.box.com/reference/put-folders-id/#param-is_collaboration_restricted_to_enterprise
2. Download the SDK
3. Validate the BoxFolderRequest.cs class does not have that field

### Expected Behavior
I expect the SDK models to match what the API spec indicates

### Versions Used
.Net SDK: Latest 3.x

**Comment by mwwoda** [comment]
Change is already merged under #732 and will be released with the new version of SDK.
