### ISSUE TITLE
Is it possible to create a Box client not having ClientId and ClientSecret but just with OAuth2 token?

### ISSUE THREAD

**Issue by mulykr** [box/box-windows-sdk-v2#748]
Hello!
In order to use the SDK I need to have ClientId and ClientSecret provided by Box app but is it possible to use SDK having just OAuth2 access token provided by 3rd-party service (I don't have ClientId and ClientSecret)? Other cloud storage SDKs provide a constructor which takes only an access token as a parameter, is it possible here?

**Comment by LawrenceAntony** [comment]
I too have the same use case. Can someone answer ?
