### ISSUE TITLE
CreateEnterpriseUserAsync throwing access_denied_insufficient_permissions - Access denied - insufficient permission

### ISSUE THREAD

**Issue by nthandu** [box/box-windows-sdk-v2#750]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
Create the app user throwing  access denied insufficient permission error when running the sample Box.V2.Samples.Core.AppUser.Create
I have created the custom app including the manage users scope and authorised the app. I have the co-admin permission and I have authorised the app.

### Steps to Reproduce
1). Clone  Box.V2.Samples.Core.AppUser.Create repo
2). Replace the client secrets json file
3. Run the application and it will fail at line invoking create enterprise user.
### Error Message, Including Stack Trace
Unhandled exception. Box.V2.Exceptions.BoxException: The API returned an error [Forbidden | a9f0183b757d] access_denied_insufficient_permissions - Access denied - insufficient permission
   at Box.V2.Extensions.BoxResponseExtensions.ParseResults[T](IBoxResponse`1 response, IBoxConverter converter)
   at Box.V2.Managers.BoxResourceManager.ToResponseAsync[T](IBoxRequest request, Boolean queueRequest)
   at Box.V2.Managers.BoxUsersManager.CreateEnterpriseUserAsync(BoxUserRequest userRequest, IEnumerable`1 fields)
   at BoxPlayground.Program.ExecuteMainAsync() in $\BoxPlayground\Program.cs:line 50
   at BoxPlayground.Program.Main(String[] args) in $\BoxPlayground\Program.cs:line 17
   at BoxPlayground.Program.<Main>(String[] args)
### Versions Used
.Net SDK: 
Windows: 

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-windows-sdk-v2/search?type=Issues

**Comment by mwwoda** [comment]
Hi @nthandu 
To create an enterprise user you need "manage users" scope, Enteprise access and your applications must be authorized by an admin. If you are still encountering this issue after following those steps, please fill a ticket to Box User services - see https://support.box.com/hc/en-us/articles/360043693434-API-Content-API-403-access-denied-insufficient-permissions-Errors as the problem could lie elsewhere and it is out of scope of the sdk.

Thanks,
@mwwoda
