### ISSUE TITLE
Cannot access a closed stream

### ISSUE THREAD

**Issue by jluzardo1971** [box/box-windows-sdk-v2#762]
Hi,

I'm getting an "System.ObjectDisposedException: 'Cannot access a closed Stream.'" error when trying to run this code:

        public void DownloadFile(System.IO.Stream stream, string fileName)
        {
            Task<BoxCollection<BoxItem>> task1 = Task.Run(() => client.FoldersManager.GetFolderItemsAsync("0", 500));
            BoxCollection<BoxItem> boxCollection = task1.Result;
            string fileId = "";

            foreach (BoxItem boxItem in boxCollection.Entries)
            {
                if (boxItem.Name == fileName)
                {
                    fileId = boxItem.Id;
                }
            }

            Task<System.IO.Stream> task2 = Task.Run(() => client.FilesManager.DownloadAsync(fileId));
            task2.Result.CopyTo(stream);
        }

I get it on the last line (task2.Result.CopyTo(stream). I can upload a file, get a list of files and delete files, I'm only having problems when trying to download a file. I don't have much experience with Box so it's probably something I'm doing wrong. Any help is appreciated.

**Comment by arjankowski** [comment]
Hi @jluzardo1971 ,

Thanks for submitting this issue! We will take a look and get back to you ASAP!

@arjankowski

**Comment by jluzardo1971** [comment]
Hi @mwwoda,

Thank You! I'm using the .NET framework. I downloaded the source code a few days ago because the NuGet package was missing some objects.
