### ISSUE TITLE
Folder collaborations can be either BoxUser or BoxGroup but AccessiblyBy property is only type BoxUser; cast is failing

### ISSUE THREAD

**Issue by cburnette** [box/box-windows-sdk-v2#77]
Basically when you get the collaborations on a folder the collaborations AccessibleBy properties can be either a BoxUser or a BoxGroup (groups can be collaborators).  However, in the BoxCollaboration class the AccessibleBy property is of type BoxUser.  Therefore when you ask for the collaborations of a folder that also has a group collaborated in, the SDK is unable to cast the BoxGroup object and set AccessibleBy.  An exception is thrown during the deserialization. 

/// <summary>

        /// The user who the collaboration applies to
        /// </summary>

        [JsonProperty(PropertyName = FieldAccessibleBy)]
        public BoxUser AccessibleBy { get; set; }

​​​​From quickly looking at it we may just want to change the property to be of type BoxEntity and then as a user of the SDK you just have to figure out how to cast it if they need the data.  Thoughts?

**Comment by brianytang** [comment]
It's up!
