### ISSUE TITLE
Box.V2 boxClient.Auth.AuthenticateAsync is throwing "An error occurred while sending the request"

### ISSUE THREAD

**Issue by schandra09net** [box/box-windows-sdk-v2#771]
Hello Team,

We are using Box.V2 in my C# WPF application, and while invoking below method getting this exception ,
<package id="Box.V2" version="2.14.0" targetFramework="net452" />

**Intialization to get AuthCode:**
var boxConfig = new BoxConfig(_boxAppClientID, _boxAppClientSecret, new Uri(_boxAppReturnUrl));
_boxClient = new BoxClient(boxConfig, session);

**Try to get AccessToken:**
![image](https://user-images.githubusercontent.com/52242195/141610295-53b54f29-e791-4321-9016-557f8fdc8319.png)
{"An error occurred while sending the request."}
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233088
    HelpLink: null
    InnerException: {"The request was aborted: Could not create SSL/TLS secure channel."}
    Message: "An error occurred while sending the request."
    Source: "Microsoft.Threading.Tasks"
    StackTrace: "   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)\r\n   at Box.V2.Auth.AuthRepository.<AuthenticateAsync>d__17.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Content.ContentProviderModule.Providers.BoxContentProvider.<<AuthenticateInternal>b__14_0>d.MoveNext() in D:\\Comapny\\Content\\Modules\\ContentProviderModule\\Providers\\BoxContentProvider.cs:line 119"
    TargetSite: {Void ThrowForNonSuccess(System.Threading.Tasks.Task)}

Can you please let me know?

**Comment by arjankowski** [comment]
Hi @schandra09net,

It's look like due to TLS conflict you are not able to make a connection to the server.

1) Can you specify what Windows version and .NET framework you are using?
2) Is there any place in your WPF app where you set ServicePointManager.SecurityProtocol property?
3) Can you also put this line `Console.WriteLine(ServicePointManager.SecurityProtocol);` in you `catch` blok and show us what it prints for further investigation?

@arjankowski

**Comment by schandra09net** [comment]
Hi @arjankowski:

Thanks for your reply, and answers below
1. Can you specify what Windows version and .NET framework you are using?
![2021-11-15_20h28_38](https://user-images.githubusercontent.com/52242195/141804609-575dd446-9b51-48eb-a971-66c2a2d01819.png)

![2021-11-15_20h29_11](https://user-images.githubusercontent.com/52242195/141805367-d8c3b396-c64a-4b5f-bbc7-ff9712df7772.png)

2. Is there any place in your WPF app where you set ServicePointManager.SecurityProtocol property?
No results found in Visual Studio with search "ServicePointManager.SecurityProtocol" or "ServicePointManager" or "ServicePointManager.SecurityProtocol"

3. Can you also put this line Console.WriteLine(ServicePointManager.SecurityProtocol); in you catch blok and show us what it prints for further investigation?

![2021-11-15_20h37_10](https://user-images.githubusercontent.com/52242195/141805405-a22c0e31-c4fc-4403-b739-8b1f22d41c51.png)

Please suggest.

**Comment by schandra09net** [comment]
Hi @arjankowski:

After adding this line in try block, issue is resolved, and getting all the box items.
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

![image](https://user-images.githubusercontent.com/52242195/141805907-44d08858-4f0f-4f90-b330-1d084c1a00d8.png)

Thank you.
