### ISSUE TITLE
Client credentials support

### ISSUE THREAD

**Issue by tallesl** [box/box-windows-sdk-v2#774]
Is there support for the `Server Authentication (Client Credentials Grant)` authentication method?

![image](https://user-images.githubusercontent.com/3655047/142629703-6ace8ebf-ce94-4b50-8333-90a5c5e12e81.png)

**Comment by arjankowski** [comment]
Hi @tallesl

Currently our SDKs doesn't support client credentials, but we have a plan to do this in the near future.

@arjankowski

**Comment by mwwoda** [comment]
Resolved via #799.
