### ISSUE TITLE
AuthRepository is throwing InvalidCastException when refresh the access token failed.

### ISSUE THREAD

**Issue by pika-shiro** [box/box-windows-sdk-v2#788]
### Description of the Issue
Unable to cast object of type 'Box.V2.Exceptions.BoxAPIException' to type 'Box.V2.Exceptions.BoxSessionInvalidatedException'

### Steps to Reproduce
Use a invalid refresh token to Refresh the access token.

### Expected Behavior
https://github.com/box/box-windows-sdk-v2/blob/main/Box.V2/Exceptions/BoxAuthenticationFailedException.cs#L29
The 'ex' is BoxAPIException, cannot cast to BoxSessionInvalidatedException.

### Versions Used
.Net 6.0
Windows 10
Box.V2.Core 4.1.0

**Comment by arjankowski** [comment]
Hi @ding-tea ,

Thanks for this contribution! We will review it ASAP!

@arjankowski

**Comment by lukedubber** [comment]
Having the same issue as well. Thanks for all your hard work!
