### ISSUE TITLE
Box Collaboration Forbidden exception does not include the ErrorCode "forbidden_by_policy" value, it is empty.

### ISSUE THREAD

**Issue by pandimurugan-a** [box/box-windows-sdk-v2#826]
We got the Forbidden exception while collaborating to Shield folder in box and the error message is " Box.V2.Exceptions.BoxAPIException: The API returned an error [Forbidden | s5h46dh2e1hyml6m.05dd0bec8c5cae65ff903a40774c844d1] forbidden_by_policy - Access denied by Shield policy", but we do not get the ErrorCode "forbidden_by_policy" in ex.ErrorCode to classify this exception.

https://developer.box.com/guides/api-calls/permissions-and-errors/common-errors/#403-forbidden
try {
// establish collaboration
}
catch (BoxAPIException ex) {

// ex.ErrorCode is empty. no value here

}

Please fix this.

**Comment by arjankowski** [comment]
Hi @pandimurugan-a 

Thank you for submitting this number! 
Could you please give me more information about it?

1) What operation were you performing on this folder?
2) Could you please show me the answer you got?
3) Could you execute this this operation with CURL and check if the answer will be the same as in SDK?

**Comment by arjankowski** [comment]
Hi @pandimurugan-a,

We plan to release a new version of this `box-windows-sdk` with this fix within two weeks. 

I'm closing this issue, but feel free to reopen it if the problem will still occurs.

Regards!
Artur
