### ISSUE TITLE
How to get response header and response body?

### ISSUE THREAD

**Issue by Yelich6** [box/box-windows-sdk-v2#837]
- [ x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
Sometimes uploading failed by using this sdk.
To check server logs on Box, Box support needs response headers and bodies which is returned from Box.
How do I need to implement to get it? 

### Expected Behavior
Get a response header and body and output it.

**Comment by arjankowski** [comment]
Hi @Yelich6 thank you for submitting this issue.

When request fails, all the data you asked for can found in `BoxAPIException` exception.
This exception is created based on actual response, so response headers you can find in
`ResponseHeaders` property but the body of response, which is mapped to `BoxError`,  you can find in `Error` property.

```
try
{
...

    var file = File.OpenRead(localFilePath);
    var bFile = await client.FilesManager.UploadUsingSessionAsync(file, remoteFileName, "0");
}
catch (BoxAPIException exp)
{
    Console.WriteLine($"Response headers:\n{exp.ResponseHeaders}\n");
    Console.WriteLine("Response error:");
    Console.WriteLine($"Message: {exp.Error.Message}");
    Console.WriteLine($"Status: {exp.Error.Status}");
    Console.WriteLine($"Code: {exp.Error.Code}");
    Console.WriteLine($"RequestId: {exp.Error.RequestId}");
}
```

Is this answer your question?

Regards,
Artur

**Comment by Yelich6** [comment]
Thank you very much for the reply. It looks very useful. Much appreciate.
