### ISSUE TITLE
Expose effective_access on shared links

### ISSUE THREAD

**Issue by kendomen** [box/box-windows-sdk-v2#842]
### Is your feature request related to a problem? Please describe.
We need a way to see the value of effective_access on shared links in order to set the access on shared links.
If we try to set a shared link to “company” and the effective_access is “collaborators”, we will get a “Forbidden” error. 

### Describe the solution you'd like
Expose effective_access by adding getter on BoxSharedLInk.cs

### Additional context
We have a business case to not allow "open" shared links on folders so we need a way to protect it without having the api throw an error.  Our files have different rules for "open" links so that is why we need a job to change "open" links on folders to either "company" or "collaborators".

**Comment by arjankowski** [comment]
@kendomen,
Thanks for submitting this issue and PR for this! 

@arjankowski
