### ISSUE TITLE
Request Timeout might not work if WiFi connection was off

### ISSUE THREAD

**Issue by 23W** [box/box-windows-sdk-v2#844]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
When application starts download some relatively big file (around 8Mb) from Box and WiFi connection has been lost or switched off at this moment, timeout exception will never raise and application hangs

### Steps to Reproduce
1. Run download operation `client.FilesManager.DownloadAsync()`
2. Wait 2 seconds and switch off WiFi connection
3. See error

### Expected Behavior
After timeout period (around 100 sec), timeout exception must be thrown

### Screenshots
![image](https://user-images.githubusercontent.com/11534020/182205727-c158d906-a8b7-4243-ba09-bc4b460cc458.png)

### App Example for test:
```
            string ClientId = "my-client-id";
            string ClientSecret = "my-secret-id;
            string RedirectUri = "https://my-redirect-uri.com/";

            var refr = "my-refresh-token;
            var acs = "my-access-token";
            var session = new OAuthSession(acs, refr, 3600, "bearer");

            var config = new BoxConfig(ClientId, ClientSecret, new Uri(RedirectUri));
            var client = new BoxClient(config, session);

            Console.WriteLine($"Start download {DateTime.Now}");

            try
            {
                var FileId = "my-file-id";

                using (var fileStream = new FileStream("MyFile.bin", FileMode.OpenOrCreate, FileAccess.Write, FileShare.Read, bufferSize: 4096, useAsync: true))
                using (var stream = await client.FilesManager.DownloadAsync(FileId))
                {
                    await stream.CopyToAsync(fileStream, 4096);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine($"Exception: {e.Message}");
            }

            Console.WriteLine($"End download {DateTime.Now}");
```

### Versions Used
Box SDK: 4.4.0
.Net SDK:  .Net Framework 4.7.2; .Net 6.0
Windows: 10

**Comment by 23W** [comment]
I see you create `HttpClient` with infinitive timeout (method `ClientFactory.CreateClient()`):
```
                var client = new HttpClient(handler)
                {
                    Timeout = Timeout.InfiniteTimeSpan // Don't let HttpClient time out the request, since we manually handle timeout cancellation
                };
```

I don't think it's a good idea.

**Comment by lukaszsocha2** [comment]
Hi @23W,
thanks for submitting this Issue! We will take a look and get back to you ASAP!
@lukaszsocha2

**Comment by lukaszsocha2** [comment]
Hi @23W ,
you can set this timeout when building a config:
` var config = new BoxConfigBuilder(ClientId, ClientSecret, new Uri(RedirectUri)).SetTimeout(TimeSpan.FromSeconds(100)).Build();`
It should cause timeout also with no internet connection. Hope this solves your issue.
Best,
@lukaszsocha2

**Comment by 23W** [comment]
@lukaszsocha2 
Thank you, i'll check but why default timeout doesn't work?
Another question: does not this BoxConfig's timeout stop downloading big file to early? I mean that HttpClient timeout works only when _wait_ response.

**Comment by 23W** [comment]
> Hi @23W , you can set this timeout when building a config: ` var config = new BoxConfigBuilder(ClientId, ClientSecret, new Uri(RedirectUri)).SetTimeout(TimeSpan.FromSeconds(100)).Build();` It should cause timeout also with no internet connection. Hope this solves your issue. Best, @lukaszsocha2

Nope, It didn't help
![image](https://user-images.githubusercontent.com/11534020/184334802-f75012bd-68a7-4529-9d59-878d7c2720b3.png)
It's been about 300 seconds, but there's no timeout exception.
