### ISSUE TITLE
Box.V2.Exceptions.BoxSessionInvalidatedException is thrown while using an access token , refresh token created couple hours back

### ISSUE THREAD

**Issue by bpendharkar** [box/box-windows-sdk-v2#85]
Hello, 

I just referenced the Box SDK for my application which I am planning to run every 24 hours.
To start, I manually executed the call in browser to get the 'code'
https://app.box.com/api/oauth2/authorize?response_type=code&client_id=<id>&state=<mystate>

Using the code, I issued a call in 'PostMan' client
https://api.box.com/oauth2/token with the body as grant_type, client_id, client_secret and the code above
The response : {
    "access_token": "AT", //ACCESS_TOKEN
    "expires_in": 3895,
    "restricted_to": [],
    "refresh_token": "RT", //REFRESH_TOKEN
    "token_type": "bearer"
}

===================================Code  ==============================
Saving the tokens as variables, I executed the following
 _boxConfig = new BoxConfig(CLIENT_ID, CLIENT_SECRET, new Uri("https://redirectUri"));
 var session = new OAuthSession(ACCESS_TOKEN, REFRESH_TOKEN, 86400, "bearer");
 _boxClient = new BoxClient(_boxConfig, session);
 _boxClient.Auth.SessionAuthenticated += Auth_SessionAuthenticated;
  _boxClient.Auth.SessionInvalidated += Auth_SessionInvalidated;
                    
 var boxItems = GetItems("0").Result;

---------------------------------------------------------------------------------------------------------------
// private methods
private async Task<BoxFolder> GetItems(BoxFolderRequest folderRequest)
        {
            var boxFolder =  await _boxClient.FoldersManager.CreateAsync(folderRequest);
            return boxFolder;
        }

  void Auth_SessionInvalidated(object sender, EventArgs e)
        {
            //do nothing
        }

   void Auth_SessionAuthenticated(object sender, SessionAuthenticatedEventArgs e)
        {
            ACCESS_TOKEN = e.Session.AccessToken;
            REFRESH_TOKEN = e.Session.RefreshToken;
        }
=====================================================================

Things work fine for the first hour, but after an hour I get a Box.V2.Exceptions.BoxSessionInvalidatedException  at boxClient.FoldersManager.CreateAsync which seems like the access token is expired without being able to refresh

Looking at some existing issues , I avoided use of client.Auth.RefreshAccessTokenAsync(ACCESS_TOKEN);

However, I do not seem to overcome this issue, the only way is to again get the code and fetch new tokens and things work fine which is not the ideal solution since I want the code to run as an automated process every 24 hours without popping up the browser to get the code.

In order to avoid the session invalidated exception,should I save the tokens in a database or a file and fetch them every 24 hours  I run the code ? Is there any thing I am missing here
I'd appreciate any help.

Thanks

**Comment by Rod-Sychev** [comment]
Hey,

Please refer to the issue #31 .

Cheers,
Rodion.

**Comment by bpendharkar** [comment]
Thanks .!!
I referred to it .
I was able to handle it by storing the token in a file and retrieving it while refreshing the token next time.

Thanks,
Bhushan

**Comment by gautampatluri** [comment]
Hi,

I am trying to run the application 
1)  I did not get any refresh token while creating our app key api. Where or how do i get it?
2) While working on this piece of code, I am facing issue with this line: 
var newSession = await client.Auth.RefreshAccessTokenAsync(access_token);
Error Msg:'Box.V2.Exceptions.BoxSessionInvalidatedException' was thrown.- bad request

Thanks
Gaumzi

**Comment by carycheng** [comment]
Hey @gautampatluri, 

Unfortunately we cannot generate a refresh token from the developer console where you generated the app key. However, it looks like you are using the correct call to retrieve a refresh token. I can take a look into why you are receiving this error. 

Thanks!

**Comment by gautampatluri** [comment]
Hey Carycheng,

Thank You for the response. It will be nice if you take look into or provide me a solution for the same.

Thanks!

**Comment by carycheng** [comment]
Hey @gautampatluri, 

For our own reporting purposes it would be greatly appreciated if you created a new ticket to track this. In this ticket it would be great if you provided:

1.) What [type of auth](https://developer.box.com/docs/authentication) are you using?
2.) Code chunk that's running into the issue - how did you get the access token?

**Comment by gautampatluri** [comment]
Hey @carycheng ,

1. I am using oAuth2
2.  I was able to get access token by using the URL https://api.box.com/oauth2/authorize?response_type=code&client_id=XXX&state=authenticated and URI was pointed to localhost. I was able to get the code* and it seems we need to use it immediately(10sec-15sec) . Using this i used postman to get the access token(Parameters - Grant Type , Client_id, client_secret, code*) and the result gave me access token and refresh token which got me most part of the issue resolved.

But now i run into refresh token issue where its not getting refreshed automatically.

Thank You.

**Comment by mattwiller** [comment]
Hi @gautampatluri — you need to exchange the __auth code__ you get from Box and immediately use [`AuthenticateAsync()`](https://github.com/box/box-windows-sdk-v2/blob/f8478d95006092498eaa5553cf369140d32210f5/Box.V2/Auth/AuthRepository.cs#L67) to authenticate the client.  From there, the SDK client should keep track of refreshing tokens for you.

```c#
/* do something to get the auth code */
BoxConfig boxConfig = new BoxConfig(clientID, clientSecret, redirectUri);
BoxClient client = new BoxClient(boxConfig);
await client.Auth.AuthenticateAsync(authCode);
/* use the client to make API calls */
```

**Comment by gautampatluri** [comment]
Hi @mattwiller ,
Could you please post refresh token code using SDK. I am using the above code already but its not fetching me the refresh token as it says expired.
Thanks!

**Comment by gautampatluri** [comment]
Hi @mattwiller ,
I am stuck at how will be an  automatic refresh be invoked when the SDK detects that the tokens have expired ?
Below is my code:
 if (dtb.Rows.Count > 0)
            {
                var config = new BoxConfig(CLIENT_ID, CLIENT_SECRET, new Uri("http://localhost"));
                client = new BoxClient(config);
                var session = await client.Auth.RefreshAccessTokenAsync(client.Auth.Session.AccessToken)
                var REFRESH_TOKEN = client.Auth.Session.RefreshToken;
               // await client.Auth.AuthenticateAsync(authCode);
            }
            else
            {
                var config = new BoxConfig(CLIENT_ID, CLIENT_SECRET, new Uri("http://localhost"));
                var session = new OAuthSession(DEV_ACCESS_TOKEN, REFRESH_TOKEN, 3600, "bearer");
                client = new BoxClient(config, session);
                csf.SaveToken(DEV_ACCESS_TOKEN, REFRESH_TOKEN);
            }
Else part is working fine as it goes the very first time but not the if section.
Please help!!

**Comment by mattwiller** [comment]
@gautampatluri I'm not sure exactly what your code above is trying to do — it looks like you might be confused about the differences between Developer Tokens, normal Access Tokens, Refresh Tokens, and Auth Codes.  The Box API has an [OAuth2 guide](https://developer.box.com/v2.0/docs/oauth-20) that explains a bit more about how exactly the flow is expected to work, but at a basic level there are a few different token types:

* An __Auth Code__ is the thing you get from the Box API at your redirect URL; it has a very short lifetime (60 seconds) and you are expected to immediately exchange it for a token pair.  The token pair consists of an __Access Token__ and a __Refresh Token__.
* An __Access Token__ is the thing you use to make authenticated API calls — it goes in the Authorization header and grants you access to one user's account.  An access token has a medium lifetime of one hour, and can be used as many times as you want until it expires.
* A __Refresh Token__ is the thing you send back to Box to get a new token pair when the __Access Token__ expires.  A refresh token has a long lifetime of 60 days, but can only be used one time — once you have used it to get a new token pair it does not work anymore, and you'll need to use the __Refresh Token__ from the new token pair instead.
* A __Developer Token__ is a special __Access Token__ that only grants access to your own personal Box account; it's used for testing your app and nothing else.  It lives for one hour like a normal __Access Token__, but it cannot be refreshed.

In general, your application should not be using Developer Tokens except for testing.  Normally, you will get an Auth Code and pass it to the `client.Auth.AuthenticateAsync()` method, letting the client use it to generate and refresh Access Tokens internally (see the code snippet I posted above).
