### ISSUE TITLE
.NET SDK: Crawl a folder structure to find every file

### ISSUE THREAD

**Issue by pixelnix** [box/box-windows-sdk-v2#877]
- [ x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I want to use the .NET SDK to crawl a folder with about 60,000 items and counting, spread across several subfolders; store all the file names with their metadata locally; then periodically check to find any new or updated items anywhere in said folder tree.  The items in this folder tree have a custom enterprise metadata template attached to them, containing a field "dateUploaded" that may be useful.

What's the best way to accomplish this with the SDK? It seems like I cannot use the SearchManager, as it doesn't allow a null query. Also, there seems to be a problem paginating search results for this many items -- the SDK throws an exception when the page number goes above 50, I believe. Am I missing something about the Search SDK that can be useful here?

Should I use the FoldersManager SDK to crawl the tree finding all folder items, then list every item in every folder in order to find all existing File items? Will pagination in this part of the SDK allow me to page thru, say, 30,000 files in one folder?

Once I've crawled all items once, is it best to use the MetadataManager SDK to issue metadata queries over that custom template, like "dateUploaded > :yesterday" in order to keep up with new files that arrive in these folders? (Presuming the template values are populated correctly). Or is there a better way using the Search or Folders SDK to keep up with new files?

### Versions Used
.Net SDK: 4.5.0

**Comment by mwwoda** [comment]
> the SDK throws an exception when the page number goes above 50

Can you please elaborate on what error you are getting? Perhaps you could also provide a stacktrace.

Listing folder items via the FoldersManager API seems like a reasonable approach for your use case to create the initial tree. I am not aware of any pagination limits there. The following step with the MetadataManager API also makes sense to me.

Alternatively you could consider using events API that should let you know when changes occurs (e.g. when file is updated) https://developer.box.com/guides/events/.
