### ISSUE TITLE
Authentication does not work with a project targeting .NET 4.5.1

### ISSUE THREAD

**Issue by Rod-Sychev** [box/box-windows-sdk-v2#88]
Hi there,

We are currently migrating our product from VS 2010 .Net 4.0 to VS 2013 .Net 4.5.1 and can't get the Box integration working as authentication cannot be completed.

Basically under the VS 2010 we were capable of retrieving the authentication & refresh tokens and then using them to retrieve the information about users files and folders.

Now in VS 2013 & .Net 4.5.1 the authentication part could never be passed and therefore the Box integration is currently not working at all.

We are using Box.V2 SDK as a dll installed through the Nuget.
Authentication code looks as follows:
![image](https://cloud.githubusercontent.com/assets/6485837/6118090/ee89b7f2-b087-11e4-9427-7da85997ae4c.png)
Please note that the breakpoint is never hit here.

While investigating the issue we integrated the Box.V2 SDK source code into our solution hoping to get better understanding of the failure but in vain. 
Even though the authentication part succeeds up to the point where the OAuthSession object could be retrieved via ExchangeAuthCode (ResponseObject contains all the required data) this session object is never made it back to the original caller, i.e. the execution is not continued after this method exits:
![image](https://cloud.githubusercontent.com/assets/6485837/6118253/ba37f214-b089-11e4-874b-7cec55ee4223.png)

We've also tried using the async/await mechanism however with no luck.

Any help is greatly appreciated.

**Comment by brianytang** [comment]
If you have the full source, can you setting the startup project to Box.V2.Samples.WPF? Then open the properties window of the project and target 4.5.1?

I'm running vs 2013 with .NET 4.5.5 and the authentication flow appears to be working for me in the sample project. Can you confirm the behavior of that project on your end?

**Comment by Rod-Sychev** [comment]
Yes, it's working fine targeting 4.5.1 that means that something is nor right with our code?
What exactly?

**Comment by brianytang** [comment]
With only the snippets above, I can only guess at what might be going on based on the symptoms.

How is the original call to the Box.V2 sdk being made? Is there any chance the call is wrapped in a task or coupled with additional async/await logic? Mixing the two is known to cause deadlocks:
http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

**Comment by Rod-Sychev** [comment]
Yes, the deadlock was the reason I couldn't get the tokens and save them in DB.
Thanks a lot for the link! That helped big time!

Now I wonder why this code was working as expected in 4.0?
Probably because it didn't use the async/await mechanism?
Only Tasks and the TResults?

**Comment by brianytang** [comment]
I'm not sure what the differences are between the 4.0 project and the migrated one, but I'm glad to hear things are working for you :).
