### ISSUE TITLE
The API returned an error [BadRequest] invalid_grant - Algorithm not allowed

### ISSUE THREAD

**Issue by satsnyder** [box/box-windows-sdk-v2#880]
**DOTNET NameSpace we used :**

using Box.V2;
using Box.V2.Config;
using Box.V2.JWTAuth;
using Box.V2.Models;

**.NET SDK Package Version :** <PackageReference Include="Box.V2.Core" Version="4.6.0" />

**TimeZone of machine where this programming running"
--------------------**
time zone : IST
TimeStamp : 22/12/2022 2:02AM IST

**Code Details:
--------------------**
string path = "C:\\Sps\\boxconfig\\969190330__config1.json";
FileStream jsonConfig = new FileStream(path, FileMode.Open);
var config = BoxConfigBuilder.CreateFromJsonFile(jsonConfig).Build();
var session = new BoxJWTAuth(config);
var token = await session.AdminTokenAsync();
BoxClient client = session.AdminClient(token);

**Error Details:
------------------**
Box.V2.Exceptions.BoxAPIException
HResult=0x80131500
Message=The API returned an error [BadRequest] invalid_grant - Algorithm not allowed
Source=Box.V2.Core
StackTrace:
at Box.V2.JWTAuth.BoxJWTAuth.<GetTokenAsync>d__14.MoveNext()
at Box.V2.JWTAuth.BoxJWTAuth.<AdminTokenAsync>d__12.MoveNext()
at Program.<<Main>$>d__0.MoveNext() in C:\Users\SatheeshAvula\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 20
![box-sdk-1 (1)](https://user-images.githubusercontent.com/121499794/209674810-9372a620-0c3d-420e-b9c7-4e3ebf3bda38.png)

**Box Support Follow up links:
------------------**
https://support.box.com/hc/en-us/requests/2758979

**Comment by lukaszsocha2** [comment]
Hi @satsnyder,
the error message says that the JWT assertion we are sending has not allowed algorithm type - so let's check it. Can you copy the value of the variable `assetion` during authentication process, which is available [here](https://github.com/box/box-windows-sdk-v2/blob/main/Box.V2/JWTAuth/BoxJWTAuth.cs#L166) and then paste it to JWT decoder, e.g. https://jwt.io/ . In the header there should be an entry with: `"alg": "RS256"`. Let me know if you have the same algorithm there.
Best,
@lukaszsocha2

**Comment by satsnyder** [comment]
I'm using the nuget library, not the git hub code; how can I get the assertion? please advise

![image](https://user-images.githubusercontent.com/121499794/209691916-d9974800-f748-4162-887c-0205c59d3f5e.png)

**Comment by satsnyder** [comment]
I managed to debug it by following these steps:

I cloned this repo, removed Nuget, and added a.net project reference. That's it; I'm able to debug it.

I copied the hash to that given url and, after that, decoded the header section, alg: "none."

How can we do this?

![image](https://user-images.githubusercontent.com/121499794/209692899-98039da6-6997-47f8-9756-6ba746fbeba3.png)

**Comment by lukaszsocha2** [comment]
I should be set by .NET Box SDK, but maybe you don't have all required dependencies. The algorithm is supposed to be set in this line https://github.com/box/box-windows-sdk-v2/blob/389c317482c558404506d4627a7d89a33d57bdf8/Box.V2/JWTAuth/BoxJWTAuth.cs#L90. Can you check what is returned by `SecurityAlgorithms.RsaSha256` ?

**Comment by satsnyder** [comment]
It's not even entering there, as if condition is not satisfied, the box configuration's JWTPrivateKey and JWTPrivateKeyPassword are empty. For your information, I'm using the RSA key to authenticate, not the JWT( I mean i configured my RSA Key in BOX and downloaded the config and using that config JSON)

![image](https://user-images.githubusercontent.com/121499794/209694181-6b3e05b6-c54a-4604-ac03-666845348830.png)

**Comment by lukaszsocha2** [comment]
In your JWT config file, which you downloaded from Box Developer Console, do you have any value set to `privateKey` or the value is empty ?

**Comment by lukaszsocha2** [comment]
I assume it is empty then you should paste your private key there or generate a new RSA keyPair in DeveloperConsole. The new config file will be downloaded automatically. Use this config file as it is already filled with private key - there is no need to do anything manually.

**Comment by satsnyder** [comment]
Yeah, its empty, i already configured the public key, still the private key is not showing its empty always

**Comment by lukaszsocha2** [comment]
Can you remove existing Public Keys and Generate a new one using Box Developer Console.  `Generate a Public/Private Keypair` should cause downloading new config with all required values.

**Comment by arjankowski** [comment]
Hi @satsnyder,

I just wanted to confirm if the solution proposed by Łukasz resolved your problem?
