### ISSUE TITLE
BoxEntity does not have parent object initialized in Box.v2 .bet SDK

### ISSUE THREAD

**Issue by InfiUser** [box/box-windows-sdk-v2#893]
### Description of the Issue
I am getting Enterprise events using EventsManager.EnterpriseEventsAsync
while debugging when i hover on the Box entity object inside BoxEnterpriseEvent it contains object names 'Parent' 
which is not initialized in the BoxEntity object 

### Steps to Reproduce

using latest .net sdk Box.v2 

` BoxEventCollection<BoxEnterpriseEvent> enterpriseEvents = boxClient.EventsManager.EnterpriseEventsAsync(500, null, event_type, offsetDate,null).Result;
                  
                    List<string> reocurrenceFolderList = new List<string>();
                    foreach (BoxEnterpriseEvent entry in enterpriseEvents.Entries)
                    {
                        BoxEntity source = new BoxEntity();
                    }
`
### Expected Behavior
i should be able to access source.Parent 

### Error Message, Including Stack Trace
'BoxEntity' does not contain a definition for 'Parent' and no accessible extension method 'Parent' accepting a first argument of type 'BoxEntity' could be found (are you missing a using directive or an assembly reference?)	

### Screenshots
![Screenshot (22)](https://user-images.githubusercontent.com/109527673/221566299-ec018b28-f7ae-4375-a682-d37d1189a0e1.png)

![Screenshot (21)](https://user-images.githubusercontent.com/109527673/221566308-f84ca4e8-d28f-4ba6-a466-56c926b3acdf.png)

### Versions Used
.Net SDK: 5.1.0

**Comment by mwwoda** [comment]
Hi @InfiUser 
The `Source` property is of type `BoxEntity`, which is a very generic type used throughout the SDK that contains a very minimal amount of information. If you want to access some event-specific properties, such as the `Parent` in this case you should cast `Source` to the appropriate C# type based on the `type` property. Examples of types used for events are `BoxFileEventSource`, `BoxFolderEventSource`, `BoxWebLinkEventSource`.

In your case the returned type looks to me like `BoxFileEventSource` so your code should look more or less like this
```
var enterpriseEvents = await adminClient.EventsManager.EnterpriseEventsAsync(500, eventTypes: new[] {"UPLOAD"});
foreach (BoxEnterpriseEvent entry in enterpriseEvents.Entries)
{
    if (entry.Source is BoxFileEventSource fileEvent)
    {
        // do something with fileEvent
        Console.WriteLine(fileEvent.Parent.Id);
    }
}
```
