### ISSUE TITLE
SDK Errors When Using JWT Auth with Custom Base URLs

### ISSUE THREAD

**Issue by trevordebard** [box/box-windows-sdk-v2#895]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
When using a custom base URL, JWT auth will always fail with the error shown below. This occurs because the constructJWTAssertion [function call](https://github.com/box/box-windows-sdk-v2/blob/d789081f548957ac471a9c4d36e80ae053ca98e5/Box.V2/JWTAuth/BoxJWTAuth.cs#L268) to build the JWT uses `_boxConfig.BoxApiHostUri` instead of `new Uri(https://api.box.com/oauth2/token)`

It looks like the other language SDKs handle this by ensuring "https://api.box.com/oauth2/token" is a constant when generating a token.

Implementation in Other SDKs:
- [Python](https://github.com/box/box-python-sdk/blob/5def3385ced4293bf4230a543e046c0e79e29352/boxsdk/auth/jwt_auth.py#L161)
- [Java](https://github.com/box/box-java-sdk/blob/c1dcc9a731b7a6893e57cc77791a364f48c5cc12/src/main/java/com/box/sdk/BoxDeveloperEditionAPIConnection.java#L490)
- [Node](https://github.com/box/box-node-sdk/blob/69bc9b5e4459d067790cb40355bf8b6eacfd7a30/src/token-manager.ts#L389)

### Steps to Reproduce
1. Configure the client to change the base url to "http://localhost" 
2. Creation of the token will fail because the JWT will have an aud value of "http://localhost/oauth2/token". 

```csharp
var reader = new StreamReader("box_config.json");
var json = reader.ReadToEnd();
var config = BoxConfigBuilder.CreateFromJsonString(json).SetBoxApiHostUri(new Uri("http://localhost:8081")).Build();
var session = new BoxJWTAuth(config); // JWT will be generated with wrong aud here
var token = await session.AdminTokenAsync(); 
client = session.AdminClient(token);
return client;
```

### Error Message, Including Stack Trace
```json
{"error":"invalid_grant","error_description":"Please check the 'aud' claim. The value for 'aud' is invalid"}
```

### Suggested Change
Always use https://api.box.com/oauth2/token when generating a JWT

Please let me know if I am missing something or if there are any workarounds to this that I may not be aware of. Thanks!

**Comment by lukaszsocha2** [comment]
Hi @trevordebard,
thanks for posting this issue. We will try to fix it asap.
Best,
@lukaszsocha2

**Comment by lukaszsocha2** [comment]
Hi @trevordebard,
may I ask what is your use case that you want to change base url to `localhost`, but still keep `box.api.com` in `aud` field?

**Comment by mwwoda** [comment]
We'll release a new package with this fix sometime this week.
