### ISSUE TITLE
Replace deprecated BouncyCastle with BouncyCastle.Cryptography

### ISSUE THREAD

**Issue by TFoxik** [box/box-windows-sdk-v2#908]
### Is your feature request related to a problem? Please describe.
Mixed dependencies when using box and BouncyCastle.Cryptography and generally best practice to not use the deprecated library

### Describe the solution you'd like
Replace already deprecated and not maintained BouncyCastle https://www.nuget.org/packages/BouncyCastle with BouncyCastle.Cryptography https://www.nuget.org/packages/BouncyCastle.Cryptography/

### Additional context
I was replacing deprecated BouncyCastle with BouncyCastle.Cryptography. During this, I also wanted to update box version but noticed that this is still referencing the old already deprecated BouncyCastle. This might cause problems with mixed dependencies but also it's a bad practice to use deprecated library

**Comment by mwwoda** [comment]
It would definitely make sense to replace it. I have added it to our backlog (SDK-3154). Also, if you want to contribute, feel free to do so.

**Comment by mwwoda** [comment]
Fixed by #909 
Will be shipped with the new version of the SDK.
