### ISSUE TITLE
Deserialization Error with BoxSignRequestSingerInputContentType when Fetching Sign Requests with Attachments

### ISSUE THREAD

**Issue by i-tachiiri** [box/box-windows-sdk-v2#912]
When trying to retrieve the current signature status from a signature request that includes attachments, I encounter the following error:

```
client.SignRequestsManager.GetSignRequestByIdAsync(SignRequestId);
xxx.GetAwaiter().GetResult();

Error:
{"Error converting value \"attachment\" to type 'Box.V2.Models.BoxSignRequestSingerInputContentType'. Path 'signers[2].inputs[18].content_type', line 1, position 4076."}
```

I'm not sure of the cause and I consulted ChatGPT. Here is its response. Is this understanding correct? If so, is there a way to fix it? If not, could you guide me on how to retrieve information from a signature request that includes attachments?

According to the Box API documentation, the valid values for BoxSignRequestSingerInputContentType are as follows:

document
fields
The value "attachment" does not exist in this enumeration, which is likely why the deserialization is failing.

There are two possible solutions:

Fix the part where signers[2].inputs[18].content_type is "attachment". This requires modifying this value before calling the API, or changing the API's response.

Modify the Box.V2.Models.BoxSignRequestSingerInputContentType type. This is only possible if you are the maintainer of this library and have direct access to the source code. You could solve the error by adding the value "attachment" to this enumeration.

**Comment by mwwoda** [comment]
This fix will be released with the next version of the sdk.
