### ISSUE TITLE
Not able to Get File details from GetFolderItemsAsync SDK Method

### ISSUE THREAD

**Issue by Kartheepan008** [box/box-windows-sdk-v2#928]
- [X ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ ] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
Not Able to get Field details.
### Steps to Reproduce

```
List<string> fields = new List<string> {

                        "typedID",
                        "type",
                        "id",
                        "date",
                        "extension",
                        "name",
                        "fileIDHash",
                        "url",
                        "parentFolderID",
                        "lastUpdatedByName"
                    };

                var items = await client.FoldersManager.GetFolderItemsAsync(FolderID, 1000, autoPaginate: true,fields: fields);
```

### Screenshots

![image](https://github.com/box/box-windows-sdk-v2/assets/149568115/8c0fab51-fe43-44fa-bb43-83e864a5da68)

### Versions Used
.Net SDK: Windows SDK for v2 of the Box API. The SDK is built for .NET Core and includes JWTAuth support 5.6.0
Windows: Windows 10

[sdk-docs]: ./docs
https://github.com/box/box-windows-sdk-v2/blob/main/docs/folders.md#get-a-folders-items

**Comment by congminh1254** [comment]
Hi @Kartheepan008 

I can see from your code and your screenshot, you are not specify the correct fields, as we don't have any fields like "typedID", "date", "fileIDHash", "parentFolderID", "lastUpdatedByName".

For the full list of the fields name, you can check it [here](https://developer.box.com/reference/resources/items/)

Best,
Minh

**Comment by Kartheepan008** [comment]
Im looking to get below Field Values  on C# response  but couldnt find the respective field names on the URL that you mentiond. Can you please point us to list of all supported field names so that we will pass it as List<string> on GetFolderItemsAsync Method
"CreatedAt"
,"CreatedBy"
,"ContentCreatedAt"
,"ContentModifiedAt"
,"ModifiedAt"
,"ModifiedBy"
,"OwnedBy"
,"Metadata"
,"Description"

but couldnt find the field names for it  so we tried the field names from the site API response but it didnt help


![image](https://github.com/box/box-windows-sdk-v2/assets/149568115/f846b64b-27a6-4820-bd46-52ed36ee1737)

![image](https://github.com/box/box-windows-sdk-v2/assets/149568115/5dde5063-85ed-45bc-bd8e-d588605667f3)

**Comment by congminh1254** [comment]
Here you can file the list of fields: [File](https://developer.box.com/reference/resources/file--full/) [Folder](https://developer.box.com/reference/resources/folder--full/) and [Weblink](https://developer.box.com/reference/resources/web-link/)

**Comment by Kartheepan008** [comment]
Thanks a lot for the quick response able to fetch the  file details now
