### ISSUE TITLE
Timeout is not fired with large files, file is not uploading and task is frozen

### ISSUE THREAD

**Issue by fsmirnoff** [box/box-windows-sdk-v2#93]
I have an issue with uploading files larger than 2GB. After calling UploadAsync I don't get any response from SDK, no exceptiions, no timeouts, no progress, network is not used by the process from the very begining (looks like it doesn't even try to upload the file). I was trying several times and every time it's the same: await is waiting forever. With file of 1.8GB everything works ok. My box.com plan allows files up to 5GB.
The source is:
using (var fileStream = new FileStream(filePath, FileMode.Open, FileAccess.Read))
{
   file = await boxClient.FilesManager.UploadAsync(req, fileStream, timeout: TimeSpan.FromHours(1));
}

**Comment by brianytang** [comment]
This should work. I just used the sample app in the SDK to upload a 3 gig file.

The fact that you're saying the await waits forever (ie. after your specified timeout of an hour nothing happens), potentially sounds like there may be a deadlock. Are there other places in the code where blocking code is used? eg. Task.Result etc.

**Comment by fsmirnoff** [comment]
Looks like you used win 8.1 sample for your upload. As WPF sample doesn't contain upload functionality I added it (I'm developing a windows service, so I can't use win 8.1 libraries). Also I updated SDK with the latest sources and switched to .Net Framework 4.5.1. And the problem I reported has gone. But I got another issue which looks to be not connected to file size and happens sometimes after 2 minutes of upload and sometimes after an hour. Looks like input stream is closed somewhere before it has been read to the end.

The code I added to the WPF sample is:
MainWindow.xaml.cs:
private async void ButtonBase_OnClick(object sender, RoutedEventArgs e)
        {
            try
            {
                await _main.UploadAsync();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message + "\r\n" + ex.StackTrace);
            }
        }
MainViewModel.cs:
public async Task UploadAsync()
        {
            using (var fileStream = new FileStream("c:/dropboxtestlocal/1.mov", FileMode.Open, FileAccess.Read))
            {
                BoxFileRequest req = new BoxFileRequest()
                {
                    Name = "1.mov",
                    Parent = new BoxRequestEntity() {Id = "0"}
                };
                BoxFile f = await Client.FilesManager.UploadAsync(req, fileStream, timeout: TimeSpan.FromMinutes(240));
            }
        }
The exception is System.ObjectDisposedException {"Cannot access a closed file."}
![box_exc2](https://cloud.githubusercontent.com/assets/11723980/7053212/0b9bb4f8-de3c-11e4-9552-3e2780e74a89.png)

**Comment by coolboy** [comment]
@fsmirnoff The UploadAsync() is not that stable when doing large files, please try UploadUsingSessionAsync in our latest code

Feel free to reopen the issue
