### ISSUE TITLE
Please sign the Box.V2.DLL

### ISSUE THREAD

**Issue by rere13852** [box/box-windows-sdk-v2#939]
### Is your feature request related to a problem? Please describe.
The Windows's Smart App control feature requires that ALL of the executables being signed by their vendor.
We use your Box.V2.DLL in our product, so this Box.V2.dll should be signed as well - if we want to run on Windows where the Smart App control features is on.

### Describe the solution you'd like
To sign not only the nuget package itself but the dll inside it as well.

### Describe alternatives you've considered
n/a

### Additional context
n/a

**Comment by mhagmajer** [comment]
Please refer to the answer on Box Community Forum: https://forum.box.com/t/net-sdk-dll-is-not-signed/1825.

tl;dr coming in [box-dotnet-sdk-gen](https://github.com/box/box-dotnet-sdk-gen)
