### ISSUE TITLE
How to get children folders when there are more than 10,000

### ISSUE THREAD

**Issue by mikeren2014** [box/box-windows-sdk-v2#942]
I believe BoxClient.FoldersManager.GetFolderItemsAsync() is equilavent with API https://api.box.com/2.0/folders/230155851619/items, but why doesn't have usemarker and marker parameters?

Since it has limitation of 1000, and offset is limited to less than 10000, how do we get all children folders if there are more than that?

**Comment by lukaszsocha2** [comment]
Hi @mikeren2014,
we have recently added a new method: `Task<BoxCollectionMarkerBased<BoxItem>> GetFolderItemsMarkerBasedAsync()` to `BoxFoldersManager` (see the pr: https://github.com/box/box-windows-sdk-v2/pull/936), but it not yet released. A new SDK package with the new method should be published early next week. This method will allow to get more than 11000 items from folder. I'm closing this issue as it already has been addressed.
Best,
@lukaszsocha2

**Comment by arjankowski** [comment]
Hi @mikeren2014,
I've released the new [v5.7.0](https://github.com/box/box-windows-sdk-v2/releases/tag/v5.7.0) with the mentioned fix.
Please take a look into this [doc](https://github.com/box/box-windows-sdk-v2/blob/main/docs/folders.md#get-a-folders-items) to see how to use this new added method!
