### ISSUE TITLE
Can not sort by date when get items in folder.

### ISSUE THREAD

**Issue by shironeko269** [box/box-windows-sdk-v2#952]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
Get bad request when calling await boxClient.FoldersManager.GetFolderItemsAsync("0", limit: 1000, offset: 0, fields: ......, sort: "date", direction: BoxSortDirection.DESC);

### Error Message, Including Stack Trace
"Error converting value "date" to type 'Box.V2.Models.BoxSortBy'.Path 'order[1].by', line 1, position 22453."

but it mentions here that it accept the "date" value.
![image](https://github.com/box/box-windows-sdk-v2/assets/62126440/d14281c7-56e3-4550-9874-60de35df5267)

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-windows-sdk-v2/search?type=Issues

**Comment by lukaszsocha2** [comment]
Hi @shironeko269,
thanks for reaching us. We will look at this issue and try to resolve it as soon as possible. 
Best,
@lukaszsocha2
