### ISSUE TITLE
Refresh token expiring after 3 hours

### ISSUE THREAD

**Issue by rajeevprasanna** [box/box-windows-sdk-v2#96]
Hi,
 I am using Box ios API in my iphone application. I am able to generate access token and refresh token after user granting permission with oauth2 flow and then access files in Box application.

But after sometime around 3 hours, i am getting below error : {"error":"invalid_grant","error_description":"Refresh token has expired"}

Not sure why this is happening. As per documentation, refresh token has to live for 60days. But why it is expiring. And one more thing, while looking at Box API, they are changing both access token and refresh token. Why changing refresh token when access token has to change as per standard oauth protocol standards.

Can someone help us

**Comment by Rod-Sychev** [comment]
Hey,

Yeah, that's the way Box does it, which is weird for me too.
Leads to an overhead and tons of complications in development process.

The bottom line you need to store your tokens somewhere and then re-create the BoxClient each time you make an API call or keep the BoxClient alive somehow.
Please note that if the token is expired the Box API would exchange it without you knowing it so make sure to check every time whether it's same or not.
Or you could subscribe to events: SessionAuthenticated & SessionInvalidated.
As far as I understand it's a bad practice to refresh token yourself.

#31 is a good source in this regard too.

**Comment by brianytang** [comment]
iOS related issues should be posted on the respective github page. 

Refresh tokens do live for 60 days, however if a refresh token is used in that time to generate a new set of access/refresh tokens -- which are then used -- it will expire the original refresh token.
