### ISSUE TITLE
Get the retention policy applied to a file

### ISSUE THREAD

**Issue by shironeko269** [box/box-windows-sdk-v2#968]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I want to get the retention policy which is applied to a file directly but I can not find how to do it with the SDK.
When I select a file on Box page, I can see it call the api like images below

![image](https://github.com/user-attachments/assets/4a8145fb-ed29-4ba1-aa8e-6334a016494b)
<img width="333" alt="WXWorkCapture_17223972458614" src="https://github.com/user-attachments/assets/b37beb64-42d6-4daf-8ec1-446f1f71dff3">

the response has the retentionPolicy info of the file which is the one I need. How can I achieve that ? 
I'm working on C# .NET 8.0 and Box.V2 Version=5.7.0

**Comment by arjankowski** [comment]
Hi @shironeko269,

At the moment, Box does not expose any public endpoint in its API that allows directly retrieving the retention policy assigned to a folder or file.
What our public API offers is the ability to retrieve retention policy and then retrieve retention policy assignments for a selected retention (you can read about it [here](https://developer.box.com/guides/retention-policies/)).

The request you are showing is internal and not publicly available. Such requests are created for the Box frontend and often execute public APIs sequentially.

If you think such an API would be useful, I encourage you to add your improvement idea to [Box Pulse](https://pulse.box.com/forums/909778-product-feedback). This way, there is a chance that the retention team will add such a method.

Best regards.
