### ISSUE TITLE
About the exist time for authorization code

### ISSUE THREAD

**Issue by shironeko269** [box/box-windows-sdk-v2#969]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

<img width="865" alt="WXWorkCapture_17241484502888" src="https://github.com/user-attachments/assets/de338ac7-edf3-4d91-9718-b5b24841acc0">

I would like to ask is there any way to extend the exist time for authorization code ? Currently, it expired too fast for us.

**Comment by lukaszsocha2** [comment]
Hi @shironeko269,
there is no way to to extend the time of this short-lived authorization code. What is the authentication flow, which you are using right now? Why would you need it to be extended? Have you considered using another auth method like JWT or CCG?
Best,
@lukaszsocha2

**Comment by shironeko269** [comment]
@lukaszsocha2  Thank you for your prompt reply
![image](https://github.com/user-attachments/assets/3adbe505-e337-4efe-a7ab-dd375fece597)

Currently our app wants to support multiple authentication methods. The other methods work fine but for the user authentication method, when it comes to the step of using the authorization code to create an OAuthSession, sometimes the authorization code might expire due to latency or slow network. So I just want to know if there is a way to extend the time of this short-lived authorization code.

**Comment by lukaszsocha2** [comment]
Hi @shironeko269,
unfortunately this is not currently possible to extend that time. Maybe a retry mechanism could do the job on your side to retry authentication attempts, which failed due to token expiration?
Best, @lukaszsocha2
