### ISSUE TITLE
Setting an expiration date when uploading a file

### ISSUE THREAD

**Issue by jamesSampica** [box/box-windows-sdk-v2#970]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
Is there a way to set an expiration date when uploading a file? I basically want to do something like this...

I can do this when managing files directly in box through the file context menu, as seen below.

```csharp
var fileRequest = new BoxFileRequest
{
    Name = "test.pdf",
    ExpirationAt = DateTimeOffset.Now.AddDays(1) // ExpirationAt doesn't exist
};

await boxClient.FilesManager.UploadAsync(fileRequest, fileContents);
```

### Steps to Reproduce
N/A

### Expected Behavior
N/A

### Error Message, Including Stack Trace
N/A

### Screenshots
![image](https://github.com/user-attachments/assets/9b4a26c9-242a-4941-b9e8-0acbc0d88d5d)
![image](https://github.com/user-attachments/assets/2c691e5a-d320-4fb2-a6a9-06cd581907e5)

### Versions Used
.Net SDK: 5.8.0
Windows: Windows Server 2022

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-windows-sdk-v2/search?type=Issues

**Comment by lukaszsocha2** [comment]
Hi @jamesSampica,
unfortunately Box API currently doesn't support setting expiration during upload ([API docs](https://developer.box.com/reference/post-files-content/)) or updating the file ([API docs](https://developer.box.com/reference/put-files-id/)).
You can try to achieve something similar using [Retention Policy](https://developer.box.com/reference/resources/retention-policy/) with "permanently_delete" disposition action. See [docs](https://github.com/box/box-windows-sdk-v2/blob/main/docs/retention-policies.md) for more details.
Best,
@lukaszsocha2

**Comment by jamesSampica** [comment]
Thanks for getting back to me. Is this something that is supported in the newer generated SDK or can I put in an enhancement to support this here or somewhere else?

**Comment by lukaszsocha2** [comment]
Hi, this in not supported by Box API so it cannot be supported by any SDK. You can submit a post on [Box Pulse](https://pulse.box.com/forums/909778-product-feedback) to add API support for this field. If it gets many votes, maybe your query will be prioritised.

**Comment by jamesSampica** [comment]
Got ya, thank you
