### ISSUE TITLE
GetCollaborationsAsync returns null AccessibleBy for pending collaborations

### ISSUE THREAD

**Issue by saguiitay** [box/box-windows-sdk-v2#98]
Add a collaboration to a folder (either via the regular web UI, or using the AddCollaborationAsync method of the API). Don't approve the collaboration...

Call GetCollaborationsAsync on the folder - you will get the correct number of collaboration entries, however for the pending entry, the AccessibleBy field will be null.

Notice that the value is null in the JSON returned from the server (which means this is a server-side issue, and not a client/parsing issue).

**Comment by brianytang** [comment]
Yeah that's currently the expected behavior from the API. Inviting a user that does not have a box account will result in a null AccessibleBy field.
