### ISSUE TITLE
FileLoadException on client construction

### ISSUE THREAD

**Issue by rssteffey** [box/box-windows-sdk-v2#99]
I receive " first chance exception of type 'System.IO.FileLoadException' occurred in Box.V2.dll" when attempting to call new BoxClient(config, session).

As far as I can tell, both config and session are 100% correctly created.  (Tokens and auth code are accurate)

The package is installed through Nuget.  I can't actually see any documentation for BoxClient in the file browser so I'm wondering if that's part of the issue

**Comment by rssteffey** [comment]
Just for additional info, after a database call to get my stored tokens, I initialize with:

<pre>
<code>
string AT = query.AccessToken;
string RT = query.RefreshToken;
OAuthSession session = new OAuthSession(AT, RT, 3600, "bearer");
BoxConfig config = new BoxConfig(client_id, client_secret, null);
BoxClient client = new BoxClient(config, session);
</code>
</pre>

My app's page has redirect_uri set to "https://localhost", and I've tried just about every option for the redirect parameter before finally just leaving it null for now.

**Comment by Rod-Sychev** [comment]
Hey,

It looks like you are missing some dll.
Can you get more information in the InnerException?
Usually it tells you exactly which one has failed to load.

**Comment by coolboy** [comment]
Closing old issues

Feel free to reopen it.
